### ISSUE TITLE
replace('\n','') will be updated to replace('\n ','') when saving case by RIDE

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1427] opened 2015-06-03 09:20 UTC
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1387) by ying_zhu... on 11 Nov 2014_

In my test case, there's one text: replace('\n','')

If I write &amp; save this test case using RIDE, this text will be automatically updated to: replace('\n&lt;br&gt;','')
It caused my test points can't be verified.

**Comment by yanne** [comment] 2015-06-05 20:23
Where in the test case you have this text? Can you attach a sample line before and after writing it with RIDE. I cannot reproduce this.

**Comment by Nyral** [comment] 2019-05-23 23:28
@HelioGuilherme66 Not reproducible for me.

**Comment by HelioGuilherme66** [comment] 2019-12-01 17:51
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 17:51 UTC
Labels: bug, pending, prio-medium
