### ISSUE TITLE
RIDE hangs when renaming a resource file keyword

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1252] opened 2015-06-03 06:44 UTC
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1213) by fabiol... on 4 Mar 2013_

Steps.

Rename a keyword from an external resources file

RIDE goes to a non-responding state (freezes), elapsed time from the progress window never increases

RIDE does recover eventually, after about a minute and a half, and it renames the keyword.

I am running RIDE 1.1 running on Python 2.7.2 (in windows). 

Similar problem has been posted in <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1142" title="RIDE hangs while renaming keyword"> issue 1142 </a> (marked as won't fix). I was not sure where to comment, so I created a new issue.

I run ride with debug console mode, and attached is the print_stacks() output.

**Comment by yanne** [comment] 2015-06-03 06:44
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1213#c1) by @mkorpela on 4 Mar 2013*


Do you have a small example case where this happens?

**Comment by yanne** [comment] 2015-06-03 06:44
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1213#c2) by fabiol... on 4 Mar 2013*


No unfortunately, it is a big project and I do not know what is causing the problem to make you an small example. Is the attached debug information giving you any hints?. 

1) We do use blank spaces when naming keywords, and sometimes dashes "_"

2) We do have keywords having the same name in several resource files, to allow us re-usability of test cases between environments. Basically we only import the resource file we need from a master resource file imported by every test suite but keywords with the same name can be in resource files located in the same directory as the resource file we are using

Do you think item 2 can cause the problem?

**Comment by yanne** [comment] 2015-06-03 06:44
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1213#c3) by @pekkaklarck on 5 Mar 2013*


This issue has been reported also as part of <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1142" title="RIDE hangs while renaming keyword"> issue 1142 </a>. Comment 15 in that in that issue contains print_stacks() output that might be interesting.

**Comment by yanne** [comment] 2015-06-03 06:44
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1213#c4) by @mkorpela on 5 Mar 2013*


The debug stack seems to indicate that RIDE is currently processing unknown? variables.. Have to take a closer look later.

**Comment by yanne** [comment] 2015-06-03 06:44
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1213#c5) by fabiol... on 5 Mar 2013*


yes i posted the comment 15, but I was not sure if there was any point on commenting on a "won't fix" issue, so I opened a new one. Sorry about that

I guess renaming a keyword from "Text edit" tab is treated different by RIDE, because doing that takes no time.

**Comment by HelioGuilherme66** [comment] 2020-01-12 18:49
Closing because was not reproducible on 1.7.4.1dev0, Windows10, wxPython 4.0.7post2 and Python 2.7.16.

**Closed by HelioGuilherme66** 2020-01-12 18:49 UTC
Labels: bug, prio-medium
