### ISSUE TITLE
The full file path to pycharm is not available in ride

### ISSUE THREAD

**Issue by xiaoyouxiu** [robotframework/RIDE#2542] opened 2023-02-17 10:33 UTC
This is my pycharm directory
![image](https://user-images.githubusercontent.com/71994911/219619164-2a567b7d-ea30-4f0a-a0de-051501fd2021.png)
This is the directory for ride
![image](https://user-images.githubusercontent.com/71994911/219619492-ba1c3b64-ea9a-4612-a681-19cf089e7be4.png)
Meanwhile, the directory in ride is cluttered and inconsistent with pycharm
![image](https://user-images.githubusercontent.com/71994911/219619685-9635a412-b751-40f8-9550-99b2ac12431e.png)
![image](https://user-images.githubusercontent.com/71994911/219619957-a07005b5-25c0-4df7-ad08-5eb37eb1f37f.png)
This is the version I used:
![image](https://user-images.githubusercontent.com/71994911/219620260-ce8b9bd9-f3ea-474a-b48b-76d66628a478.png)
![image](https://user-images.githubusercontent.com/71994911/219620315-773effb2-e778-4aad-95b5-0ef6e422891f.png)
I hope to get help soon. Thank you

**Comment by HelioGuilherme66** [comment] 2023-02-17 11:04
Seems that the name of folders got mixed up, maybe because they start with `Setup_and_Teardowns`.

**Comment by xiaoyouxiu** [comment] 2023-02-20 01:54
I changed the other two file names, the setups_and_teardowns file is now normal, but the other two are not shown in ride directly, why is this, what should I do?
![376b50a6c373b5bd7877a38b134da543](https://user-images.githubusercontent.com/71994911/219991418-652494ac-31bb-46fe-870a-f9be9868980a.png)

**Comment by xiaoyouxiu** [comment] 2023-02-20 02:09
I just found out that the contents of the setups_and_teardowns file are still the same as before, but because of my renaming operation, the contents of the other two files were automatically moved and entered into the commit. This means that after I renamed the files, they are the same as before

**Comment by HelioGuilherme66** [comment] 2023-02-20 10:04
Some things come to my mind:

- Don't use PyCharm and RIDE at the same time
- RIDE may detect changes in files/folders on the opened project, and ask to Reload project. If you answer No, those changes will be reverted.
- RIDE may need to reload the project to fully update the Project Tree. You may close RIDE and reopen it, to force that.

If this Issue was a momentarily thing, caused by renaming of files or using at same time as in PyCharm, please close it.
Thanks.

**Comment by xiaoyouxiu** [comment] 2023-02-21 07:34
But this problem still exists until now. And it has nothing to do with the problem you mentioned above, the version I used before did not have this situation, it appeared after I upgraded. Here is the information of my previous version, please help me to check again
![1b215072631b3c48a7798558495f26b9](https://user-images.githubusercontent.com/71994911/220278046-eea9e719-e764-4672-ae50-a6a38ff6993a.png)

**Comment by xiaoyouxiu** [comment] 2023-02-21 07:43
I just found out that I created a new folder in RIDE, I made sure I saved it, then I opened RIDE again and it disappeared. But when I open pycharm, I see it
![53B1E291-760C-468a-9BDA-DE74B22C1F39](https://user-images.githubusercontent.com/71994911/220279685-88dcc8fa-b02c-4f5e-aa34-345162bae305.png)
![FE236971-280D-4c8c-AF1D-E70A814060C9](https://user-images.githubusercontent.com/71994911/220279718-1d6b0654-17ef-461f-bf10-2e08ee76e5be.png)
![39E41CE8-3EAA-4e59-AA56-BA763C5F3F8F](https://user-images.githubusercontent.com/71994911/220279981-6e092029-4762-43cd-8679-7dd64bcddc32.png)

**Comment by HelioGuilherme66** [comment] 2023-02-21 15:18
This is getting more complicated to understand the problem, because now you mention a different one.
RIDE in Test Suites explorer, shows folders with test cases with the simple folder icon, and the ones with resource files with  the spanner tool. Non project files are not shown in this view (and _maybe_ no empty folders).
When you create a new test suite as a directory, you are creating an `__init__.robot`  file. Why it does not show, I don't know for now.
There is the Files explorer view, where the new folders and all files are shown (in Windows, maybe files without extension are not shown). To be sure to refresh this tree view, we need to collapse and expand the folder needing to be updated (this is undocumented). This Files explorer, for sure will show all folders and files like you see in PyCharm.

Please clarify the problem you are finding.

**Comment by xiaoyouxiu** [comment] 2023-02-23 02:54
I don't quite understand what you mean, my current phenomenon is that some of the folders are not displayed in RIDE, and at the same time my new directory is not displayed when I reopen RIDE. But these files exist in my actual path
![image](https://user-images.githubusercontent.com/71994911/220811434-26c625bd-42b6-48e3-bb62-bbedfce61fe2.png)
![image](https://user-images.githubusercontent.com/71994911/220811581-dee0cc51-4601-4ef6-b71b-09c73dece988.png)

**Comment by xiaoyouxiu** [comment] 2023-02-23 07:16
I downgraded the version of RIDE to 2.0b2, RIDE failed to open, I downgraded to 2.0b1 again, open normal, and my file directory display normal. I hope this will help you!

**Closed** 2023-07-24 15:49 UTC
Labels: pending, analyze
