### ISSUE TITLE
RIDE closes when the grid view is dragged with the mouse

### ISSUE THREAD

**Issue by AndrewNewell2** [robotframework/RIDE#1483] opened 2015-07-20 21:33 UTC
When editing tests in the Grid View and dragging to select mulitple cells, RIDE will close without saving changes. Very frustrating.

RIDE v 1.4
Python 2.7.6
Xubuntu 14.04

**Comment by yanne** [comment] 2015-07-21 05:03
Is there any traceback in the terminal window? Do you drag horizontally or vertically? Which wxPython version you are using?

I cannot reproduce this on Ubunutu 15.04/wxPython 2.8.12.1/Python 2.7.9

**Comment by AndrewNewell2** [comment] 2015-07-27 20:17
Hi Janne,

We use the same version of wxPython as you.  The dragging action was anywhere within the grid in any direction. The only further comment I can make about the dragging action and the click were initiated as one movement.

RIDE was started from the desktop shortcut so no traceback was available.  I have now started using the terminal to launch RIDE so any future issues can be logged.

I have since done a full system update with the current stable Selenium Server/Firefox(33) combination. Still using Xubuntu 14.04.  I have been using this configuration for a week now and I have not had the crashing issue again.

My issue can be closed and, should it arise again I will re-raise with more information.

Regards
Andrew

**Comment by yanne** [comment] 2015-08-06 07:28
Thanks, I'll close this for now.

**Closed by yanne** 2015-08-06 07:28 UTC
