### ISSUE TITLE
Problem to install RIDE on Windows 7

### ISSUE THREAD

**Issue by marcio1973** [robotframework/RIDE#1624] opened 2016-03-30 14:48 UTC
Hi,

I try to install RIDE on Windows 7 but have a problem when run ride

I install Python 2.7.11 (python-2.7.11.msi)
Then i use pip to install robotframework-3.0
Then i install wxPython 2.8.12.1 - win32 - unicode (wxPython2.8-win32-unicode-2.8.12.1-py27.exe)
Then i use pip to install robotframework-ride-1.5.2.1

But when i try to run ride i receive this message:

```
C:\Users\marcio.almeida.3>ride.py
Wrong wxPython version.
You need to install wxPython 2.8.12.1 with unicode support to run RIDE.
wxPython 2.8.12.1 can be downloaded from `http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/`
```

How can i fix this?

**Comment by Mohorelien** [comment] 2016-03-30 15:47
I think you have installés python 64bit. You should install the 32bit one or install ride and wxputhon 64 bit instead.

**Comment by Mohorelien** [comment] 2016-03-30 15:48
Damned french keyboard...

**Comment by marcio1973** [comment] 2016-03-30 16:41
Hi Mohorelien,

It´s 32 bits, look

```
C:\Users\marcio.almeida.3\Downloads\WebDemo>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

```

**Comment by HelioGuilherme66** [comment] 2016-03-30 19:08
I am not sure but, I think that reboot is required.
If that is not enough, then see if it exists a file "wx.pth" at
C:\\Python27\Lib\site-packages. That file should contain the name of the
folder of wx installation (usually in that same folder).
To test wx you can just do:
python
import wx
print wx.VERSION   # optional
(no error should occur)

**Comment by marcio1973** [comment] 2016-03-30 19:30
Hi HelioGuilherme66,

I reboot and don´t work.

I have the "wx.ph" and it´s ok, it´s point to C:\Python27\Lib\site-packages\wx-2.8-msw-unicode

and the wxPython it´s ok too


```
C:\Users\marcio.almeida.3>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> print wx.version()
2.8.12.1 (msw-unicode)
>>> print wx.VERSION
(2, 8, 12, 1, '')
>>>

```

**Comment by HelioGuilherme66** [comment] 2016-03-30 21:03
(...) I have the "wx.ph" and it´s ok, it´s point to
C:\Python27\Lib\site-packages\wx-2.8-msw-unicode

Try to remove the full path and leave only wx-2.8-msw-unicode

**Comment by marcio1973** [comment] 2016-03-31 12:39
Hi Helio,

Inside the "wx.ph" it´s only wx-2.8-msw-unicode

I put the full path here to show the right location of the folder

**Comment by HelioGuilherme66** [comment] 2016-07-14 23:51
Hello @marcio1973,
Are you still not using RIDE due to the reported problem?
If the problem is solved, please close this issue. Thanks.
(Post here what was the solution)

**Comment by sunaysshah** [comment] 2017-04-11 11:39
Is this issue resolved?? I am facing similar issue

**Comment by shivajighadge** [comment] 2017-05-06 17:10
I am facing same issue please help...

**Comment by Naveennani777** [comment] 2017-07-14 05:41
Hi All,
          I am facing issue after installing RIDE in windows . When I execute  ride.py from command prompt , It exits from cmd window. Please  help me on resolving this issue.
 Installed softwares:
=============
Python 2.7.8
wxpython 2.8.12.1
python packages , setuptools and pip
robotframework dependencies
robotframework
robotframework-ride
robotframework-requests
robotframework-debuglibrary
robotframework-sshlibrary


Logs:
====
print wx.version()

>> import wx
>> print wx.version()
2.8.12.1 (msw-unicode)
>>

**Comment by HelioGuilherme66** [comment] 2017-07-14 08:37
@Naveennani777 What is the error message, when ride.py exits command window? Please paste here the output.

Does it work when you run the following code?
```
C:\python27\python.exe  -c "from robotide import main; main()"
```

**Comment by Naveennani777** [comment] 2017-07-14 09:38
Hi Helio,
              Thanks alot . This command worked for me. Now am able to see RIDE as GUI . Thanks for your support. 
![ride_from_windows](https://user-images.githubusercontent.com/25869304/28207109-129fe49e-68a6-11e7-8b55-fccc4ee009f6.png)

**Comment by Naveennani777** [comment] 2017-07-14 09:46
Hi Helio,
              Thanks alot for your support. This command worked for me and attached screenshot after executing command.
![ride_from_windows](https://user-images.githubusercontent.com/25869304/28207458-6a088794-68a7-11e7-9423-8ca697c62ad3.png)

**Comment by baumannchristian** [comment] 2018-02-07 07:46
I have the very same issues as @marcio1973, followed all the given instructions, same outcome, same result.
Help would be much appreciated!

Thx,
Christian

**Comment by Barajin** [comment] 2018-03-22 22:37
Thank you Helios, worked for me too :D

**Comment by HelioGuilherme66** [comment] 2019-05-23 23:25
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Closed by HelioGuilherme66** 2019-05-23 23:25 UTC
