### ISSUE TITLE
Not able to automate, continues integration testing 

### ISSUE THREAD

**Issue by Nall11G** [robotframework/RIDE#1673] opened 2017-01-05 10:11 UTC
I am having regression test suite 10 cases, I have designed the TC and execute the script for very first time the script is running, but the next time again I am going to execute the Test Cases, the script cannot be work properly and also I'm not getting any issue, the script is running there is no end and it could not be produce any result...

Note: Test case was prepared and executed by RIDE - with python

**Comment by HelioGuilherme66** [comment] 2017-01-05 16:38
This is not enough information for us to help. The first thing you should try to see is if the problem is with RIDE or with Robot Framework. You would run the test suite from a command line with `pybot` or `robot`. If the same happens then it is not RIDE problem and you should close this Issue.

If you are certain that it is a RIDE problem, then you should set the loglevel to DEBUG or TRACE to locate where is getting stuck. Also it could be important to know what Libraries your tests would be using.

**Comment by Nall11G** [comment] 2017-01-10 11:16
Yes..I am working on RIDE tool.  When Test cases are executed very first time the script is running, but the next time it cannot be run properly, the test cases are still running and it cannot produce any debug or result. So I'm not able to find the problem whether it is a browser/RIDE/script problem. 

I am using Selenium2Library files and the executed profile type is pybot. Could you please take a look and suggest to me the solution.

**Comment by IonutAursulesei** [comment] 2017-05-23 15:05
Hi,
I have the same problem. 
Open RIDE, run 1 TC for first time  -> test pass and logs are generated. 
Run the same TC for the second time, the test is finished, but RIDE is not generating any logs/report, is still running.
Thank you,

**Comment by bhajojo** [comment] 2017-05-23 15:23
Open the task manager , kill the running instances of the browsers 

Let's say you were executing scripts on chrome..Kill the old chrome instances . You will be able to see the logs

**Comment by IonutAursulesei** [comment] 2017-05-24 06:32
I try this: 
-run the TC from RIDE -> no logs in the interface for ride
-run the TC from CMD -> logs ok
@bhajojo
I have tried also your method, it's works but can I do this automatic? There is a ride command or something because I can't do this manual every time. :(

PS; it works fine also if I run jenkins job.

**Comment by bhajojo** [comment] 2017-05-24 06:57
Create a keyword to kill the browsers and call it as teardown in your test

**Comment by HelioGuilherme66** [comment] 2019-06-01 20:30
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)

**Closed by HelioGuilherme66** 2019-06-01 20:30 UTC
Labels: invalid
