### ISSUE TITLE
Undo (CTRL-Z) does not restore file state to not changed

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#479] opened 2015-06-02 09:47 UTC
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448) by jerry57 on 5 May 2010_

Mac OS X 10.6.3
python 2.6.1
jython 2.5.1
ride 0.22.1
robotframework 2.1.3

When I edit a test case that already exists and undo the edit, the file
shows as requiring a save (has asterisk next to suite name).  If I undo all
the way back to original state, then the file shouldn't need to be saved.

**Comment by robotframework-ride** [comment] 2015-06-02 09:47
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448#c1) by @yanne on 28 Jun 2010*


Mac OSX is not currently supported platform at NSN, who is the sponsor of RF core development team. In addition to that, we have only limited access to Mac OSX machines to even test possible fix(es).

Contribution to fix and test this issue is more than welcome.

**Comment by robotframework-ride** [comment] 2015-06-02 09:47
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448#c2) by @yanne on 9 Aug 2010*


Not an OSX-only issue.

I consider this only a minor annoyance though.

**Comment by robotframework-ride** [comment] 2015-06-02 09:47
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448#c5) by @jussimalinen on 13 Aug 2010*


This is not trivial to fix with the current "dirty" handling. CTRL-Z only works while editing grid, but there also other fields (like doc) in the file that can cause it become flagged dirty.. So simply unflagging file as undirty when undo history is empty will not do.

Bigger changes are needed.

**Comment by robotframework-ride** [comment] 2015-06-02 09:47
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448#c7) by laurent.carbonnaux on 9 Jun 2011*


I reproduce this problem too and I find it a bit annoying in fact.
My exact problem comes from the fact that :
- I can not launch the tests if some files are unsaved
- I can not save a file unless it is checked-out from Perforce (where all my TC are)

=&gt; so in the case I modify by mistake a non-checked-out test case, even if I do UNDO, I am stuck in a "non saved" status, and my only way out is to close completely RIDE and re-open it. Not great (but I can live with that of course)

Laurent

**Comment by robotframework-ride** [comment] 2015-06-02 09:47
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448#c8) by @mkorpela on 9 Jun 2011*


@&#8288;Laurent: I'm not familiar with Perforce so could you explain a bit why you can not save files that are not in version control?

**Comment by robotframework-ride** [comment] 2015-06-02 09:47
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448#c9) by laurent.carbonnaux on 9 Jun 2011*


@&#8288;mikko: In my case the file *is* in Perforce, but I did not checked-out it. So it is set as read-only on my computer (that's the way perforce work). So I have a "not saved status in RIDE" and a "can not save status in Windows/perforce". If UNDO of RIDE would remove this "not saved status" I would be OK and could go on (ie. launch my tests)

**Comment by robotframework-ride** [comment] 2015-06-02 09:47
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448#c10) by @mkorpela on 9 Jun 2011*


@&#8288;Laurent: I see why the current behavior is a real problem to you.
As Jussi has pointed out the undo mechanism is nontrivial so I was thinking if there could be also other ways to improve your situation.

Would it solve your problem if RIDE did not allow editing of read-only files?

**Comment by robotframework-ride** [comment] 2015-06-02 09:47
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448#c11) by laurent.carbonnaux on 9 Jun 2011*


Indeed. That would be perfect !

**Comment by robotframework-ride** [comment] 2015-06-02 09:47
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448#c12) by @mkorpela on 9 Jun 2011*


I'll update <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=157" title="RIDE should not allow editing read-only files"> Issue 157 </a> based on this discussion.

**Comment by robotframework-ride** [comment] 2015-06-02 09:47
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=448#c13) by @mkorpela on 22 Aug 2013*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1272" title="Unsaved state persistant"> Issue 1272 </a> has been merged into this issue.

**Comment by yanne** [comment] 2015-06-07 16:00
Duplicate of #987

**Comment by HelioGuilherme66** [comment] 2019-12-30 00:11
Still valid 4 years later :(

**Comment by HelioGuilherme66** [comment] 2020-07-11 20:29
This is improved with the fix for #2229 but not complete :)

**Comment by HelioGuilherme66** [comment] 2022-09-05 11:52
On new version 2.0b2, Ctrl-Z (Undo) resetting to saved state is working on Text Editor, but not on Grid Editor.

I am closing this, because it is dated from 2010. If needed we open a new issue.

**Closed by HelioGuilherme66** 2022-09-05 11:52 UTC
Labels: prio-low, bug
