### ISSUE TITLE
robotframework web manage platform

### ISSUE THREAD

**Issue by wuhaifengsf** [robotframework/RIDE#1817] opened 2019-02-01 07:19 UTC
hi，I am a robotframework user from China. Have you ever thought about doing robotframework web manage platform?If not, what is based on what considerations?

**Comment by HelioGuilherme66** [comment] 2019-02-01 09:12
Can you please clarify? Are you talking about test management web application (like TestLink)?

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:05
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:05 UTC
Labels: not-a-bug, pending
