### ISSUE TITLE
Click on Edit->Clear selected, python console shows "UnboundLocalError: local variable 'is_item_expanded' referenced before assignment"

### ISSUE THREAD

**Issue by yiyunfeiyan** [robotframework/RIDE#1669] opened 2016-12-06 02:12 UTC
Traceback (most recent call last):
  File "D:\Program Files\Python27\lib\site-packages\robotide\ui\actiontriggers.py", line 377, in __call__
    action.act(event)
  File "D:\Program Files\Python27\lib\site-packages\robotide\action\action.py", line 86, in act
    self.action(event)
  File "D:\Program Files\Python27\lib\site-packages\robotide\controller\ui\treecontroller.py", line 59, in OnClearSelect
ed
    self._tree.DeselectAllTests(self._tree._root)
  File "D:\Program Files\Python27\lib\site-packages\robotide\ui\tree.py", line 667, in DeselectAllTests
    self._for_all_tests(item, lambda t: self.CheckItem(t, checked=False))
  File "D:\Program Files\Python27\lib\site-packages\robotide\ui\tree.py", line 654, in _for_all_tests
    if not is_item_expanded:
UnboundLocalError: local variable 'is_item_expanded' referenced before assignment

I have checked the file tree.py, the variable 'is_item_expanded' need to have initial value before use. There will be a error if the 'if not' state in line 639 has not been excuted.

**Comment by HelioGuilherme66** [comment] 2019-10-18 23:26
@Nyral Please confirm if bug still exists. I could not reproduce on Linux Fedora 30 with python 3.7 (current development version). Thanks.

**Comment by HelioGuilherme66** [comment] 2019-12-25 18:22
Closing because is not reproduced with Python 2.7.13 with wx version 4.0.7.post2 in Windows.

**Closed by HelioGuilherme66** 2019-12-25 18:22 UTC
Labels: bug, fixed, prio-medium

**Comment by Nyral** [comment] 2019-12-25 22:31
Sorry, I did not see your message. I remember being able to reproduce this, but not what I did. It's likely that I have fixed this together with another PR.
