### ISSUE TITLE
"Make scalar/list variable body" shortcuts(ctrl+1, ctrl+2) cursor position

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#1944] opened 2019-06-10 13:59 UTC
Grouping several related issues into 1:
Subissiue 1:
in older ride versions when I used ctrl+1/ctrl+2 shortcuts on empty cells, a new variable was created and the cursor(carette) for entering the text (variable name) was already put into the middle between brackets:
${<cursor>}
but now it's outside the brackets on the right, so I have to manually put it back into the middle between the brackets every time:
${}<cursor>

Subissiue 2:
When selecting whole cell and trying to envelope (cover) all the text within that cell into a variable I expect it work like this:
cell text -> ${cell text}
but it doesn't work, instead I get the new brackets on the right from text:
cell text -> cell text${}

**Comment by HelioGuilherme66** [comment] 2019-06-10 18:53
@povar81 The first case, I cannot reproduce (on Linux with current development version), the cursor is inside the brackets. The second case, has an easy workaround, which is to select all text (for example with Ctrl+a) and then press Ctrl+1, Ctrl+2 or Ctrl+5.

**Comment by Nyral** [comment] 2019-06-10 19:07
@HelioGuilherme66 I figured out what he means. Here's a comparison between an older RIDE version and latest one.

old:
![2019-06-10_22-04-02](https://user-images.githubusercontent.com/39315668/59219831-0ed5e980-8bcc-11e9-9fe8-2bfc9031c159.gif)

new:
![2019-06-10_22-05-59](https://user-images.githubusercontent.com/39315668/59219836-109fad00-8bcc-11e9-8ce2-4366a641f6d1.gif)

**Comment by HelioGuilherme66** [comment] 2019-06-10 19:17
@Nyral Old version is what number? wxPython 2.8.12.1?
The grid has two different modes, the Navigation mode, where you don't type text and arrow keys move the selected cell. The other is Edit mode, you clicked the cell and can type text. In Edit mode, Ctrl+#, would create the variable placeholder with the caret inside brackets, or selected text.
There is room for improvement, if you want to make a PR :).

**Comment by Nyral** [comment] 2019-06-10 19:26
Something like that :) I'll work on this one.

**Comment by povar81** [comment] 2019-06-11 07:33
Ctrl+#? 
But it comments out the whole row, it has nothing to do with creating new variables...

**Comment by HelioGuilherme66** [comment] 2019-06-11 08:28
Ctrl+# was my abbreviated way to say Ctrl+1, Ctrl+2 and Ctrl+5. @povar81 Sorry for the confusion.

**Comment by povar81** [comment] 2019-06-18 07:59
> @Nyral Old version is what number? wxPython 2.8.12.1?
> The grid has two different modes, the Navigation mode, where you don't type text and arrow keys move the selected cell. The other is Edit mode, you clicked the cell and can type text. In Edit mode, Ctrl+#, would create the variable placeholder with the caret inside brackets, or selected text.
> There is room for improvement, if you want to make a PR :).
Yes, I'm talking about the Edit mode, Ctrl+1 creates variable placeholder, with the caret outside the brackets, that's the problem.

**Comment by Nyral** [comment] 2019-06-18 20:54
@povar81 What?

**Comment by povar81** [comment] 2019-06-21 14:30
> @Nyral Old version is what number? wxPython 2.8.12.1?
> The other is Edit mode, you clicked the cell and can type text. In Edit mode, Ctrl+#, would create the variable placeholder with the caret inside brackets, or selected text.
> There is room for improvement, if you want to make a PR :).
Sorry, but I don't understand what exactly do you mean. 
You're saying that "Ctrl+#, would create the variable placeholder with the caret inside brackets" but it doesn't! The caret is outside, that's the problem.

**Comment by povar81** [comment] 2019-12-02 15:21
It's partially fixed in RIDE 1.7.4rc1.dev, however the behaviour is still different (counter-intuitive I'd say):

Subissiue 1: when I double-clik a cell, and hit ctrl+1/ctrl+2 the cursor (focus) IS indeed inside the brackets now, however the both the middle and right bracket are marked (selected), and so when I enter some text the right bracket gets deleted (rewritten with new text). I have to manually hit right or click in the middle again, or manually write the right closing bracket ("}").

**Comment by povar81** [comment] 2019-12-02 15:25
Subissue 2 is not fixed : 
cell is not covered in brackets at all, neither empty cell, nor filled with text cell, nothing happens when I put cursor on some cell and press ctrl+1, while in older versions it used to cover (envelope) the whole cell between the brackets, as well as all the text in the cell.

**Comment by HelioGuilherme66** [comment] 2019-12-02 17:32
We did not make any code change related to this issue.

**Comment by HelioGuilherme66** [comment] 2020-07-18 21:13
@povar81 This issue should be fixed in current development and soon to be pre-released Beta.

**Closed** 2020-07-18 21:18 UTC
Labels: enhancement, fixed, prio-low
