### ISSUE TITLE
the new ride v1.7.3.1 can not support the project that chinese in path

### ISSUE THREAD

**Issue by sheyu** [robotframework/RIDE#1803] opened 2019-01-25 07:40 UTC
my project directory is just like this:

D:\project\无纸化\中文
--测试用例
------mysuit.txt
then load the project and try run a case.  ride print the follow message

'ascii' codec can't encode characters in position 11-13: ordinal not in range(128)

i know the problem is encode/decode， but i do now how or where to fix it.

**Comment by HelioGuilherme66** [comment] 2019-01-26 00:32
This happens with latin characters too, for example:
E:\tests\primeirª

**Comment by HelioGuilherme66** [comment] 2019-02-25 00:10
@sheyu I did not find a way to fix this on Python 2.7. However if you install from current master on Python 3, this problem should not happen.

**Comment by HelioGuilherme66** [comment] 2019-05-02 00:25
@sheyu Please test with the new 1.7.4 Alpha version, this bug should be fixed.
See the command to install at [Release Notes](https://github.com/robotframework/RIDE/blob/master/doc/releasenotes/ride-1.7.4.rst)

**Comment by matthewdy** [comment] 2019-07-24 08:58
@HelioGuilherme66 how did we fix it? May I know the commit ID ?

**Comment by HelioGuilherme66** [comment] 2019-07-24 21:39
@matthewdy So you confirm it is fixed on 1.7.4a1? If so it should also work with 1.7.4b1dev1.
```
pip install -U https://github.com/robotframework/RIDE/archive/master.zip
```

From the [Release notes of 1.7.4a1](https://github.com/robotframework/RIDE/blob/master/doc/releasenotes/ride-1.7.4.rst#robot-framework-ide-174a1) it was fixed by #1880

**Comment by lvjh** [comment] 2019-07-29 04:52
![Uploading image.png…]()

**Comment by lvjh** [comment] 2019-07-29 04:55
ride 1.7.4a1  already happen Chinese 。

![微信截图_20190729125340](https://user-images.githubusercontent.com/5357291/62022678-fbc0bc80-b1ff-11e9-8163-4cfe5a219b68.png)

**Comment by HelioGuilherme66** [comment] 2019-08-02 20:12
@lvjh Can you please confirm with current 1.7.4b1dev1 ?

```
pip install -U https://github.com/robotframework/RIDE/archive/master.zip 
```

**Comment by Tony36051** [comment] 2019-08-03 02:56
I have got the same issue, mbcs can fix on py2.7, but not py3.7.
I have checked the old version code of testrunner.py, directly decode with UTF-8 is OK on both py3.7 and py2.7. (tested in windows 7)
@HelioGuilherme66 Could you please consider make it decode with 'UTF-8'?


```python
def pop(self):
        result = ""
        for _ in xrange(self._queue.qsize()):
            try:
                result += self._queue.get_nowait()
            except Empty:
                pass
        return result.decode('UTF-8')
```

**Comment by Tony36051** [comment] 2019-08-03 10:20
> I have got the same issue, mbcs can fix on py2.7, but not py3.7.
> I have checked the old version code of testrunner.py, directly decode with UTF-8 is OK on both py3.7 and py2.7. (tested in windows 7)
> @HelioGuilherme66 Could you please consider make it decode with 'UTF-8'?
> 
> ```python
> def pop(self):
>         result = ""
>         for _ in xrange(self._queue.qsize()):
>             try:
>                 result += self._queue.get_nowait()
>             except Empty:
>                 pass
>         return result.decode('UTF-8')
> ```

sorry, I made mistake.   I got wrong with debug in pycharm 2018, but it's ok in pydev or cmd

**Comment by HelioGuilherme66** [comment] 2019-08-25 21:57
The original path problem should be fixed (at least with Python 3.7.4).

**Closed by HelioGuilherme66** 2019-08-25 21:57 UTC
Labels: bug, fixed, prio-medium

**Comment by ghosthark** [comment] 2019-09-09 06:28
Console output returns Chinese scrambling code
![image](https://user-images.githubusercontent.com/36031842/64507635-d4383600-d30d-11e9-9a69-1d609a04133f.png)
![image](https://user-images.githubusercontent.com/36031842/64507653-e1552500-d30d-11e9-8c95-d6076801529f.png)

**Comment by HelioGuilherme66** [comment] 2019-09-09 12:53
@Joker8zl That is not the problem on this issue. This issue made possible to execute using paths with chinese characters.

There are other issues for the wrong output or log window.

Due to the many variants of systems configurations, the most important thing is that robot can execute the test, and the characters are correctly shown in the report and log.

Please locate an open issue and attach a small example test file, so I can try to reproduce on my systems, Thanks.
