### ISSUE TITLE
Ride-1.5.2.1 can not show keywords by pressing F5

### ISSUE THREAD

**Issue by Leowyys** [robotframework/RIDE#1830] opened 2019-02-19 05:43 UTC
After opening ride, i press F5 to show keywords, but it shown error :
Traceback (most recent call last):
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\ui\keywordsearch.py", line 211, in OnActivate
    if self._plugin.have_keywords_changed():
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\ui\keywordsearch.py", line 64, in have_keywords_changed
    self._update()
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\ui\keywordsearch.py", line 69, in _update
    self.all_keywords = self.model.get_all_keywords()
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\controller\project.py", line 210, in get_all_keywords
    return self.get_all_keywords_from(ctrl.datafile for ctrl in self.datafiles if ctrl.datafile)
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\controller\basecontroller.py", line 103, in get_all_keywords_from
    return self._namespace.get_all_keywords(*datafiles)
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\namespace.py", line 101, in get_all_keywords
    kws.update(self._get_default_keywords())
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\namespace.py", line 106, in _get_default_keywords
    return self._lib_cache.get_default_keywords()
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 89, in get_default_keywords
    return self._default_kws[:]
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 49, in _default_kws
    self.__default_kws = self._build_default_kws()
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 93, in _build_default_kws
    for keywords_in_library in self._default_libraries.values():
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 43, in _default_libraries
    self.__default_libraries = self._get_default_libraries()
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 101, in _get_default_libraries
    default_libs[name] = self._get_library(name, args)
  File "F:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 61, in _get_library
    if time.time() - last_updated > 10.0:
TypeError: unsupported operand type(s) for -: 'float' and 'unicode'

**Comment by HelioGuilherme66** [comment] 2019-02-19 14:08
@Leowyys Is this a first time installation of RIDE 1.5.2.1? Did you installed a newer version and downgraded to 1.5.2.1?
If you don't mind loosing configurations and library help, you can (with RIDE closed), delete the folder:
```
%APPDATA%\RobotFramework\ride
```

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:14
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:14 UTC
Labels: pending
