### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by UIDR5343** [robotframework/RIDE#1641] opened 2016-06-28 09:33 UTC
command: pybot.bat 
--argumentfile 
c:\users\uidr5343\appdata\local\temp\RIDEa8f9vj.d\argfile.txt 
--listener 
D:\Tool\Common\Python\v2.7.3\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:50740:True 
C:\Users\UIDR5343\Desktop\New\pkg\art46\prv\robottests\Calculator.robot
[Error 2] The system cannot find the file specified

**Comment by HelioGuilherme66** [comment] 2016-06-28 12:19
What version of RIDE?
Does the file C:\Users\UIDR5343\Desktop\New\pkg\art46\prv\robottests\Calculator.robot really exists?

**Comment by UIDR5343** [comment] 2016-06-28 23:52
Hi,

I am creating my own test script Calculator.robot (as in the screenshot).

My RIDE is of version 1.3

Nevertheless, I am also facing the same issue if I run the available test 
script TargetTestDemo.txt


Regards,
Patrick

**Comment by HelioGuilherme66** [comment] 2016-06-29 00:16
The version 1.3 is very old (2014). Many bugs were fixed since then. Could you upgrade to 1.5.2.1? It works with latest robotframework 3.0.

**Comment by UIDR5343** [comment] 2016-06-29 00:19
Hi,

Can you please kindly share the steps on how to upgrade it? Thank you.

Regards,
Patrick

**Comment by HelioGuilherme66** [comment] 2016-06-29 11:09
Open a command window (cmd) and type:
pip install -U robotframework-ride

(If you don't have pip installed, you may upgrade python and it will include it or install manually by running get-pip.py (search google)).
There are other ways.

**Comment by UIDR5343** [comment] 2016-06-30 07:17
Hi,

I have installed the robotframework (as you can see the folder 'robot' in 
my pyhton folder).




However, when I invoke the RIDE, by clicking 
..\pkg\art46\prv\robottests\start_ride.bat, there is nothing happening. 
The RIDE UI does not appear.

Please kindly advise. Thank you.

Regards,
Patrick

**Comment by HelioGuilherme66** [comment] 2016-07-14 23:36
@UIDR5343  is this problem still happening? If not, please close this issue. Thanks.

**Comment by UIDR5343** [comment] 2016-07-14 23:48
Hi,

Per our last conversation, I have upgraded the RIDE to the latest version 
of 1.5.2.1, the RIDE can not be invoked. After I clicked the 
..\pkg\artemmis\prv\robottests\start_ride.bat, the UI did not appear.



Please kindly assist. Thank you.

Regards,
Patrick

**Comment by HelioGuilherme66** [comment] 2016-07-15 00:02
The file ..\pkg\artemmis\prv\robottests\start_ride.bat is not part of RIDE.
The usual way to start RIDE is just by running `ride.py` or locating the main file and start like for example:
```
pythonw c:\python2.7\lib\site-packages\robotide\__init__.py
```
For more troubleshooting, please post here the result of:
```
pip list
```

**Comment by UIDR5343** [comment] 2016-07-15 00:32
Hi,

The content of  ..\pkg\artemmis\prv\robottests\start_ride.bat is

@echo off
pythonw.exe -c "from robotide import main; main()"

Please kindly advise if this will execute the same command like 
pythonw c:\python2.7\lib\site-packages\robotide\__init__.py
I am having problem to run:
pip list

Please kindly advise the steps to do it. Thank you.

Regards,
Patrick

**Comment by HelioGuilherme66** [comment] 2019-06-01 20:28
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)

**Closed by HelioGuilherme66** 2019-06-01 20:28 UTC
Labels: invalid
