### ISSUE TITLE
Not able to see run tab

### ISSUE THREAD

**Issue by malli02422** [robotframework/RIDE#2617] opened 2023-08-04 11:51 UTC
Hi,
I have installed ride robotframework-ride 2.0.6 and when try to open it is showing the Ride. 
But in that only showing Edit and Text Edit I didn't find any option for Run.
Please help me r
![rideissue](https://github.com/robotframework/RIDE/assets/10920419/2478b5e3-89f7-4039-a04c-d6c4ede3fd3d)

**Comment by HelioGuilherme66** [comment] 2023-08-04 13:54
@malli02422 See Tools->View RIDE Log
Probably there is an error detecting robot installation.

**Comment by HelioGuilherme66** [comment] 2023-09-21 22:56
Closing because it is not something we can reproduce.

**Closed by HelioGuilherme66** 2023-09-21 22:56 UTC
Labels: pending, not-a-bug
