### ISSUE TITLE
Bad file descriptor error in RIDE log after OK-ing a 'Library' dialog

### ISSUE THREAD

**Issue by MichaelHallik** [robotframework/RIDE#1518] opened 2015-09-08 08:48 UTC
Setup:

Win7
Python 2.7.10
RF 2.9.1
RIDE 1.5a2

Preconditions & actions
1. Open RIDE.
2. I a resource (e.g. a keyword node), double-click a Library import statement so as to open the Library dialog.
3. _Optionally:_ Change something trivial, e.g. a comment.
4. Click the 'OK' button.

Expected result:

The dialog is closed. Possible changes have been saved.

Actual result:

Identical to the expected result, but, additionally, the RIDE log prints an error:

20150908 10:41:09.462 [INFO]: Found Robot Framework version 2.9.1 from 'C:\Python27\Lib\site-packages\robot'.
20150908 10:41:09.462 [INFO]: Started RIDE 1.5a2 using python version 2.7.10 with wx version 2.8.12.1 in win32.
20150908 10:41:28.646 [WARN]: Library import handling threw an unexpected exception

Traceback (most recent call last):
[Errno 9] Bad file descriptor
  File "C:\Python27\Lib\site-packages\robotide\spec\librarymanager.py", line 40, in run
    if not self._handle_message():
  File "C:\Python27\Lib\site-packages\robotide\spec\librarymanager.py", line 64, in _handle_message
    self._handle_fetch_keywords_message(message)
  File "C:\Python27\Lib\site-packages\robotide\spec\librarymanager.py", line 73, in _handle_fetch_keywords_message
    keywords = self._fetch_keywords(library_name, library_args)
  File "C:\Python27\Lib\site-packages\robotide\spec\librarymanager.py", line 83, in _fetch_keywords
    print 'FAILED', library_name, err

**Comment by yanne** [comment] 2015-10-21 15:44
This does not reproduce in OS X or Linux. I'll try to get access to a Windows machine.

**Comment by sheyu** [comment] 2015-12-15 08:38
i have the same problem.
i found that my testcase's path have chinese, just like  '/testcase/平台/login.txt' , replace it. it will be working.

**Comment by HelioGuilherme66** [comment] 2019-12-01 18:14
Closing because cannot reproduce.

**Closed by HelioGuilherme66** 2019-12-01 18:14 UTC
Labels: pending
