### ISSUE TITLE
Can not see grid in Edit Settings - test case

### ISSUE THREAD

**Issue by nenadfemic** [robotframework/RIDE#2039] opened 2019-10-31 18:24 UTC
just see a little button settings in test case, but nothing load below with rows 1,2,3...
Use Python 3.8, and robotframework 3.1.2,RIDE version 1.7.3.1
![image](https://user-images.githubusercontent.com/6898640/67975357-33cb0780-fc14-11e9-868c-eb3abd28924a.png)

**Comment by HelioGuilherme66** [comment] 2019-10-31 19:09
@nenadfemic I never tested before in python 3.8. But you should try to install from releases 1.7.4b2 or from current master.

**Comment by aimorari** [comment] 2019-11-01 13:12
> @nenadfemic I never tested before in python 3.8. But you should try to install from releases 1.7.4b2 or from current master.

Unfortunately, but it does NOT help :-(

**Comment by Nyral** [comment] 2019-11-03 14:02
Look in Tools > View RIDE log and tell us if you see any error, otherwise start RIDE from command line and check there.

Also run `pip list` in command line and give us the output.

**Comment by nenadfemic** [comment] 2019-11-04 10:25
> 
> 
> Look in Tools > View RIDE log and tell us if you see any error, otherwise start RIDE from command line and check there.
> 
> Also run `pip list` in command line and give us the output.
Hi Nyral

log:

20191104 11:24:02.435 [WARN]: Importing test library "XvfbRobot" failed

Traceback (most recent call last):
Importing test library 'XvfbRobot' failed: ModuleNotFoundError: No module named 'XvfbRobot'
Traceback (most recent call last):
  File "c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robotide\lib\robot\utils\importer.py", line 153, in _import
    return __import__(name, fromlist=fromlist)
PYTHONPATH:
  C:\Users\luka-emilija\AppData\Local\Programs\Python\Python38-32\Scripts
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\python38.zip
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\DLLs
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib
  c:\users\luka-emilija\appdata\local\programs\python\python38-32
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\win32
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\win32\lib
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\Pythonwin
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robotide\spec
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robotide\lib
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robotide\contrib\testrunner\../../lib
  c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robotide\contrib\testrunner\../../lib
  File "c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robotide\spec\libraryfetcher.py", line 24, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 49, in TestLibrary
    libcode, source = importer.import_class_or_module(import_name,
  File "c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robotide\lib\robot\utils\importer.py", line 72, in import_class_or_module
    self._raise_import_failed(name, err)
  File "c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robotide\lib\robot\utils\importer.py", line 109, in _raise_import_failed
    raise DataError('\n'.join(msg))


20191104 11:24:02.965 [INFO]: Found Robot Framework version 3.1.2 from c:\users\luka-emilija\appdata\local\programs\python\python38-32\lib\site-packages\robot.

20191104 11:24:02.965 [INFO]: Started RIDE 1.7.3 using python version 3.8.0 with wx version 4.0.7.post1 in win32.

**Comment by nenadfemic** [comment] 2019-11-04 10:27
![image](https://user-images.githubusercontent.com/6898640/68114348-1a68da80-fef6-11e9-8d62-0fcf0e822502.png)

**Comment by HelioGuilherme66** [comment] 2019-11-04 12:56
@nenadfemic Please install newer RIDE. That problem should be fixed in current Beta2 or in Current development version (command is `pip install -U https://github.com/robotframework/RIDE/archive/master.zip`).

**Comment by Sopasman** [comment] 2019-11-04 18:20
> @nenadfemic Please install newer RIDE. That problem should be fixed in current Beta2 or in Current development version (command is `pip install -U https://github.com/robotframework/RIDE/archive/master.zip`).

I have some problem and the newer Ride doesn´t work.

**Comment by HelioGuilherme66** [comment] 2019-11-04 22:59
@Sopasman Just referring you have the same problem, does not help to identify the root cause.
Please provide the output of `pip list`, and there are more troubleshoot tips, you can use, like running on a command window. There are many variables involved in the use of RIDE. Is this problem happening only with Python 3.8?

**Comment by Sopasman** [comment] 2019-11-05 11:02
@HelioGuilherme66 my bad. So, i'm running Python 3.8.0 (32 bit) and the pip list is:

![image](https://user-images.githubusercontent.com/57367727/68202383-87927380-ffbb-11e9-982c-cb424e060e7a.png)

**Comment by Sopasman** [comment] 2019-11-05 11:03
Now i will try with other version of Python and figure out if the problem continuous.

**Comment by Sopasman** [comment] 2019-11-05 11:27
With the Python 3.7.4 the Edit tab works fine. I have just uninstall the Python 3.8 and change to Python 3.7.4

**Comment by mohitkathpal19** [comment] 2019-11-05 20:52
@HelioGuilherme66 I am also facing the same issue. Below is the log from ride.py in command line.
C:\WINDOWS\system32>ride.py
module 'urllib' has no attribute 'Request'
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\wx\core.py", line 3285, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "c:\python38\lib\site-packages\wx\lib\scrolledpanel.py", line 157, in _SetupAfter
    self.SetVirtualSize(self.GetBestVirtualSize())
RuntimeError: wrapped C/C++ object of type TagsDisplay has been deleted

C:\>pip list
Package                                Version
-------------------------------------- -------------
aniso8601                              3.0.2
appdirs                                1.4.3
attrs                                  19.3.0
bcrypt                                 3.1.7
beautifulsoup4                         4.8.1
cached-property                        1.5.1
certifi                                2019.9.11
cffi                                   1.13.1
chardet                                3.0.4
client                                 0.0.1
configparser                           4.0.2
cryptography                           2.8
cx-Oracle                              7.2.3
defusedxml                             0.6.0
et-xmlfile                             1.0.1
idna                                   2.8
importlib-metadata                     0.23
isodate                                0.6.0
jdcal                                  1.4.1
jsonpatch                              1.24
jsonpointer                            2.0
jsonref                                0.2
jsonschema                             3.1.1
lxml                                   4.4.1
more-itertools                         7.2.0
numpy                                  1.17.3
oauthlib                               3.1.0
openpyxl                               3.0.0
paramiko                               2.6.0
Pillow                                 6.2.1
pip                                    19.3.1
py4j                                   0.10.8.1
pycparser                              2.19
Pygments                               2.4.2
PyNaCl                                 1.3.0
PyPubSub                               3.3.0
pyrsistent                             0.15.5
python-dateutil                        2.8.0
pytz                                   2019.3
pywin32                                225
requests                               2.22.0
requests-oauthlib                      1.2.0
requests-toolbelt                      0.9.1
robotframework                         3.1.2
robotframework-databaselibrary         1.2.4
robotframework-excellib                2.0.0
robotframework-extendedrequestslibrary 0.5.5
robotframework-httplibrary             0.4.2
robotframework-requests                0.6.2
robotframework-ride                    1.7.4rc1.dev0
robotframework-selenium2library        3.0.0
robotframework-seleniumlibrary         4.1.0
robotframework-sshlibrary              3.4.0
robotframework-sudslibrary-aljcalandra 1.1
robotframeworklexer                    1.1
scp                                    0.13.2
selenium                               3.141.0
setuptools                             41.2.0
six                                    1.12.0
soupsieve                              1.9.4
suds                                   0.4
suds-jurko                             0.6
suds-py3                               1.3.4.0
urllib3                                1.25.6
valedictory                            0.9.0
waitress                               1.3.1
WebOb                                  1.8.5
WebTest                                2.0.33
wxPython                               4.0.7.post1
xlrd                                   1.2.0
xlutils                                2.0.0
xlwt                                   1.3.0
zeep                                   3.4.0
zipp                                   0.6.0

**Comment by HelioGuilherme66** [comment] 2019-11-05 23:43
Thanks all.
Looks like the problem is when using Python 3.8 and on Windows.
The code of RIDE is considering Python 2.7 and Python 3.7. We want to clear code to only use Python 3.7, which will be done in RIDE 2.0. For now, we will not investigate a fix on Python 3.8.
(If someone finds a fix, they can propose a Pull Request, and we may consider to include in 1.7.4)

**Comment by nenadfemic** [comment] 2019-11-06 20:55
Hello everyone,

Yes, problem was in last  version Python 3.8. I am replace this version with  3.7.4, and now work all fine. Thanks everyone for fast and detail support.
![image](https://user-images.githubusercontent.com/6898640/68337099-113b6180-00e0-11ea-83e0-25a3651268f5.png)

**Comment by HelioGuilherme66** [comment] 2020-02-22 18:01
Fixed by #2128

**Closed by HelioGuilherme66** 2020-02-22 18:01 UTC
Labels: Python3.8, bug, fixed, os: windows
