### ISSUE TITLE
F2 to edit a cell causes the last cell's contents to be displayed

### ISSUE THREAD

**Issue by StephaneSavard** [robotframework/RIDE#1813] opened 2019-01-29 15:25 UTC
1. In any testcase, select any grid cell with text and edit the text.
2. Select any other grid cell, and press F2.

-- ISSUE: the contents of the previous grid cell (or an empty cell) is displayed instead of the current grid cell. To workaround, press escape, and press F2 again, and the correct text will now be displayed in the editing field.

**Comment by HelioGuilherme66** [comment] 2019-01-30 10:57
Did only reproduce when copied text to memory. Other situation is when pressing F2, it clears the existing cell content.

**Comment by HelioGuilherme66** [comment] 2020-07-06 17:15
Closing because can be tested on soon to be pre-released, v2.0b1.

**Closed by HelioGuilherme66** 2020-07-06 17:15 UTC
Labels: bug, fixed, prio-low
