### ISSUE TITLE
Getting the "Robot Framework installation not found" error after a successful test

### ISSUE THREAD

**Issue by CCostigan** [robotframework/RIDE#1468] opened 2015-06-10 20:54 UTC
This is in 1.4b2  - Should not be seeing that error since it just finished a run and all tests passed (meaning robot framework is installed and working).  It looks like the if condition in _create_error_log_message in testrunner\runprofiles.py is always evaluating to True

**Comment by HelioGuilherme66** [comment] 2015-06-10 23:18
That was fixed in 1.4b3.
See Janne's post:

> Hi all,
>
> 1.4 beta 2 contained a bug in test runner plugin, which complained about
> missing Robot Framework installation even after successful test execution.
> This has been fixed, and 1.4b3 has been uploaded to PyPi[1]. If there's a
> need, I can create a Windows installer also.
>
> [1] https://pypi.python.org/pypi/robotframework-ride/1.4b3
>

(pip install robotframework-ride==1.4b3)

**Comment by yanne** [comment] 2015-06-11 13:32
Duplicate of #1464

**Closed by yanne** 2015-06-11 13:32 UTC

**Comment by mainguyen0826** [comment] 2016-03-28 08:39
![rf](https://cloud.githubusercontent.com/assets/18112718/14074438/1905deda-f4fb-11e5-9f5b-b82c01dd2e0f.png)
I'm a newbie, may I know why I got this error?

**Comment by pradhan41** [comment] 2018-02-18 03:46
I am too getting the same error , ride was launched successfully , anyone found solution for it, please share !

**Comment by HelioGuilherme66** [comment] 2018-02-18 15:43
@pradhan41 This is a Closed Issue, so the problem should not happen any more. What is the version of RIDE? How did you installed it? Did you actually installed Robot Framework, run a test case and got the message?

**Comment by pradhan41** [comment] 2018-02-18 16:03
That's correct , I installed ride and ride opens successfully and I get above error when i run the test cases .Ride details 

RIDE -- Robot Framework Test Data Editor
RIDE 1.5.2.1 running on Python 2.7.14. 
 
This is my output from pip freeze 

C:\WINDOWS\system32>pip freeze
robotframework==3.0.2
robotframework-ride==1.5.2.1
robotframework-seleniumlibrary==3.1.0
selenium==3.9.0
six==1.11.0

Error on console :
command: pybot.bat --argumentfile c:\users\nex2pqg\appdata\local\temp\RIDEclig0g.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:56207:False C:\Python27\NewProject
[Error 2] The system cannot find the file specified

**Comment by HelioGuilherme66** [comment] 2018-02-18 17:54
If you open a command window, and enter `pybot --version` will it work? If not, you probably don't have C:\Python27\Scripts added to the PATH environment variable.
If for some reason there is no `pybot`but only `robot`, then create a pybot.bat file starting `robot %*` and place it on a directory reached from %PATH.

**Comment by pradhan41** [comment] 2018-02-18 20:33
Pybot --version return below ,I do see pybot.bat file in the script and added that to the environment variable and still get the same error . i am not sure if I am adding environment variable in the way you are describing 
C:\WINDOWS\system32>pybot --version
Robot Framework 3.0.2 (Python 2.7.14 on win32)

**Comment by pradhan41** [comment] 2018-03-22 17:13
I continue to face the above issue , any update on the @HelioGuilherme66 ?Thanks again

**Comment by HelioGuilherme66** [comment] 2018-03-22 22:57
@pradhan41 I see that you always run the commands from `C:\WINDOWS\system32`. If you `cd C:\` and then try `pybot --version`, will it work? If not then the PATH is not correctly set.

**Comment by pradhan41** [comment] 2018-03-23 15:02
I tried that I do get the Pybot version 

c:\>pip freeze
robotframework==3.0.2
robotframework-ride==1.5.2.1
robotframework-seleniumlibrary==3.1.0
selenium==3.9.0
six==1.11.0

c:\>Pybot --version
Robot Framework 3.0.2 (Python 2.7.14 on win32)

c:\>

**Comment by AvishekDhar** [comment] 2018-12-12 09:38
> If you open a command window, and enter `pybot --version` will it work? If not, you probably don't have C:\Python27\Scripts added to the PATH environment variable.
> If for some reason there is no `pybot`but only `robot`, then create a pybot.bat file starting `robot %*` and place it on a directory reached from %PATH.

> This idea really worked but i just copied another .Bat file and renamed it to pybot.bat . Opened the file and typed " @echo off
python -m robot.run %* “ 
save the file> again run the test and this time it passed. Thanks @HelioGuilherme66

**Comment by AjinkyaMhaskar** [comment] 2018-12-27 11:13
> If you open a command window, and enter `pybot --version` will it work? If not, you probably don't have C:\Python27\Scripts added to the PATH environment variable.
> If for some reason there is no `pybot`but only `robot`, then create a pybot.bat file starting `robot %*` and place it on a directory reached from %PATH.


Thank You @HelioGuilherme66, This worked for me as well.

**Comment by krishnakanth19** [comment] 2019-04-20 15:35
I'm also facing the same issue. I've applied the above solution. It is not trowing error but tests are not running.

![image](https://user-images.githubusercontent.com/23556113/56459367-fc9bb400-63af-11e9-94b2-6df19aacd508.png)

**Comment by Brian-Pai** [comment] 2019-05-24 03:56
I'm also have the same issue and applied the above solution. The RIDE still not work and show "Robot Framework installation not found".
My environment as below:
OS: win10
python 2.7.16
robotframework==3.1.1
robotframework-ride==1.7.3
wxPython==4.0.6

Have any one can help us? Thanks!

![robot](https://user-images.githubusercontent.com/4993950/58301782-84933480-7e1a-11e9-851d-a3cad92c14de.png)

**Comment by Brian-Pai** [comment] 2019-05-24 04:22
Hi all,
I found this to be a problem with installing the robotframework 3.3.1 
Because I installed the robot 3.3.1, 
the folder (C:\Python27\Scripts) didn't have pybot.bat/ robot.bat this 2 files.

Then I uninstall robot 3.3.1 and re-install robotframework-3.0.1. It work and the folder (C:\Python27\Scripts) have pybot.bat/ robot.bat this 2 files.

**Comment by AnteroGasalho** [comment] 2019-07-05 11:36
> @pradhan41 This is a Closed Issue, so the problem should not happen any more. What is the version of RIDE? How did you installed it? Did you actually installed Robot Framework, run a test case and got the message?

Hi, I'm getting the ame error! I only upgrade the robot framework: pip install robotframework --upgrade . Then I open my RIDE, select one of my test and immediately appears the pop-up with this error. RIDE version installed 1.5.2.1. Robotframework upgraded to 3.1.2 (2019/06/05)

**Comment by HelioGuilherme66** [comment] 2019-07-08 00:58
@AnteroGasalho Only by chance I saw your comment. You should have learned that RIDE 1.5.2.1 is looking for `pybot.bat` and not `robot.exe`.
Our new version of RIDE has options to select `pybot.bat`, `robot.bat` or `robot.exe` (name is "robot 3.1").

**Comment by AnteroGasalho** [comment] 2019-07-08 15:42
> @AnteroGasalho Only by chance I saw your comment. You should have learned that RIDE 1.5.2.1 is looking for `pybot.bat` and not `robot.exe`.
> Our new version of RIDE has options to select `pybot.bat`, `robot.bat` or `robot.exe` (name is "robot 3.1").

Thanks the problem is solved by updating RIDE.

**Comment by pradhan41** [comment] 2019-07-08 17:46
Thanks this solves this issue :)

**Comment by chidambaram1991** [comment] 2020-10-24 09:56
@HelioGuilherme66 Facing UI screen(that grid ) got disappear for created test suites in the 1.4b3 ride version. (after i installed again using (pip install robotframework-ride==1.4b3))

(
![Ride_1 4b3_screen not visible for test suite issue](https://user-images.githubusercontent.com/35648336/97078906-4a305700-160d-11eb-8de4-1372f714c928.png)
Refer screenshot attached)

**Comment by HelioGuilherme66** [comment] 2020-10-25 14:08
@chidambaram1991 you should install the current released version, 1.7.4.2, don't add the version to pop command

**Comment by CapWilder** [comment] 2022-08-22 06:26
Add these to your bash_profile

1) Open terminal and type "open -e .bash_profile" without the quotes.

2) Copy paste the below commands at the end of the file-
PATH="/Users/***{your username}***/Library/Python/3.10/bin:${PATH}"
export PATH
PATH="/Users/***{your username}***/Library/Python/2.7/bin:${PATH}"
export PATH

3) Save the file and then restart ride.

**Comment by HelioGuilherme66** [comment] 2022-08-22 11:09
@CapWilder Thanks for posting in a Closed issue, opened in 2015, this is not useful.
