### ISSUE TITLE
Stop Test cases does not works in case of custom scripts

### ISSUE THREAD

**Issue by simplyviks** [robotframework/RIDE#1767] opened 2018-08-30 10:54 UTC
Environment :- Linux
RIDE 1.5.2.1 running on Python 2.7.12. 
Robot Framework 3.0.2 (Python 2.7.12 on linux2)
======================================
1. Issue description: i am using a custom script the content of that script is as below
mvn -P ride-profile verify 
2. Now if i want to stop the script and i press stop buttom in RIDE, it just says "SENDING STOP SIGNAL"
whereas the script continues to run 
3.When i printed the process PID in send_stop_signal() its NONE.

 def send_stop_signal(self):
        if self._process:
            print self._pid_to_kill

4. Is it a know issue?
5. Same is observed with "pybot" runner profile.

**Comment by Nyral** [comment] 2019-06-01 19:19
@HelioGuilherme66 I'm guessing this is because the custom scripts do not listen for the stop signal.

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:03
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:03 UTC
Labels: pending
