### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb2 in position 12

### ISSUE THREAD

**Issue by dxlove** [robotframework/RIDE#1626] opened 2016-04-09 15:53 UTC
Traceback (most recent call last):
  File "E:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplug
in.py", line 367, in OnTimer
    self.OnProcessEnded(None)
  File "E:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplug
in.py", line 334, in OnProcessEnded
    self.get_current_profile())
  File "E:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py"
, line 251, in get_output_and_errors
    self._process.get_errors(), self._process.get_returncode()
  File "E:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py"
, line 308, in get_errors
    return self._error_stream.pop()
  File "E:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py"
, line 400, in pop
    return result.decode('UTF-8')
  File "E:\Python27\Lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb2 in position 12: invalid
start byte

**Comment by Nyral** [comment] 2019-06-01 17:13
@dxlove Is this still reproducible on latest release?

**Comment by HelioGuilherme66** [comment] 2019-12-01 18:25
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 18:25 UTC
Labels: pending
