### ISSUE TITLE
RIDE crashes when renaming keywords or test cases

### ISSUE THREAD

**Issue by technigirl** [robotframework/RIDE#1822] opened 2019-02-06 21:30 UTC
When trying to rename a keyword, RIDE crashes.  A message is briefly flashed in the GUI when this happens, but it disappears too fast for me to catch it.  The issue sometimes occurs when renaming test cases, especially if characters are added, but sometimes renaming a test case only results in the validation error (written up in a separate issue).

On the terminal where RIDE was launched, there is a segmentation fault error:

LiveoakMBP-02:Data melissa$
[1]+  Segmentation fault: 11  ride.py

It is possible to get around this by renaming the file directly, instead of through RIDE, but that's kind of a pain.

My environment:
Mac OSX (Mojave)
Ride 1.74dev
Python 3.7

**Comment by HelioGuilherme66** [comment] 2019-02-06 21:39
@technigirl Are you available to chat at Slack? 

>NEW Join our #ride channel in Robot Framework Slack: https://robotframework.slack.com (signup page: https://robotframework-slack-invite.herokuapp.com/)

If not, please explain if renaming in the Tree or in the Grid editor.

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:06
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:06 UTC
Labels: pending
