### ISSUE TITLE
Library import shows red 

### ISSUE THREAD

**Issue by manojpaul8** [robotframework/RIDE#2634] opened 2023-09-03 15:08 UTC
RIDE Version: v2.0.6

Python Interpreter Version: 3.10

Operating System and Its Version: Windows 10

We have created the team's repository as a Python package in the form of a .whl file. However, when we attempt to import files from the Python package, the library imports appear in red.

Please note that despite the red coloring, importing actually works as expected. There are no issues when running the scripts. The red color indication can be confusing to users, as it might suggest a problem that does not exist.

![image](https://github.com/robotframework/RIDE/assets/143950707/0bb32f6a-6f3e-453e-9649-690a7bb4a452)

**Comment by manojpaul8** [comment] 2023-09-28 21:06
Quick Update:

This Import issue is turning out to be a serious problem for us.

Import does not work on some PCs and user needs to re-import few times until they do not see the error. How many times we need to re-import varies from PC to PC.

Please prioritize this ticket as we are waiting for this fix.

**Comment by HelioGuilherme66** [comment] 2023-09-28 21:32
@manojpaul8 If we don't have logs indicating why the import failed, we can't do anything about this. Sometimes it takes a bit of time for the library clear the red color (and may need to move between Tabs, Editor, Run, or Test Cases).
Also if your library does not have proper documentation, it will show red, because **it failed to import keywords documentation**.
Your users should know these "issues", and may continue to work, since the Run of the tests work as expected.

**Comment by JFoederer** [comment] 2023-09-29 07:39
You can find more details about the failure in RIDE's logging. Best is to check this directly after RIDE startup:
![image](https://github.com/robotframework/RIDE/assets/32476108/ddc98a8d-9ecb-4ca1-91dc-cc571336b36d)

Most common reason for this type of issue where the library shows red in the editor, but the tests do run, is when you have unresolved dependencies in either the import of the library files or the `__init__` of your library class.

If you open a regular Python prompt and you try to import that same library from there, do you see the same error as in the RIDE log?

**Comment by HelioGuilherme66** [comment] 2023-12-11 16:58
Closing because (OR statements):
- Issue report is does not have enough or relevant info
- No follow up from reporter
- Not anything we can reproduce
- Reducing the number of opened issues

**Closed by HelioGuilherme66** 2023-12-11 16:58 UTC
Labels: BAD_ISSUE_REPORT
