### ISSUE TITLE
Scroll bug in HelioGuiherme66-fix-#1588 Branch

### ISSUE THREAD

**Issue by ChthonicOne** [robotframework/RIDE#1696] opened 2017-05-10 19:43 UTC
This bug only manifests itself if you have a keyword that is longer than the window, and you wish to insert and edit keywords in various places. As soon as you start typing, the scroll bar jumps back to the last place you viewed, which can prevent you from seeing what you are doing.

This bug was produced on Centos 6.8 with Python 2.7.6 and wxPython 3.0.2.

This bug is minor but annoying. Scrolling the mouse wheel can correct the position problem when it occurs, but it will happen again if you move to a different area of the keyword to edit/add lines.

**Comment by Nyral** [comment] 2019-06-01 18:47
@ChthonicOne Can you record yourself reproducing this bug? That would help us a lot to understand what is happening.

Either way, I think this issue is from wxPython bug (the GUI library we are using).

**Comment by HelioGuilherme66** [comment] 2019-12-01 18:31
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 18:31 UTC
Labels: pending
