### ISSUE TITLE
Few Libraries are not importing from autoitlibrary

### ISSUE THREAD

**Issue by mshoa** [robotframework/RIDE#2164] opened 2020-03-16 07:15 UTC
Error:
20200316 12:41:53.487 [WARN]: Importing test library "C:\Users\moshoaib\AppData/Local/Continuum/anaconda3/Lib/site-packages/RobotFramework/Extensions/AutoItLibrary/tests/" failed

Traceback (most recent call last):

  File "C:\Users\moshoaib\AppData\Local\Continuum\anaconda3\lib\site-packages\robotide\spec\librarymanager.py", line 86, in _fetch_keywords
    library_name.replace('/', os.sep), os.path.abspath('.'))
  File "C:\Users\moshoaib\AppData\Local\Continuum\anaconda3\lib\site-packages\robotide\spec\xmlreaders.py", line 99, in get_path
    return _resolve_path(name.replace('/', os.sep), basedir)
  File "C:\Users\moshoaib\AppData\Local\Continuum\anaconda3\lib\site-packages\robotide\spec\xmlreaders.py", line 116, in _resolve_path
    raise robotapi.DataError

Anything which i am not doing it right!!

**Comment by HelioGuilherme66** [comment] 2020-03-16 11:30
@mshoa This report has bad quality, we cannot investigate much.
Does your test case run from the command window?
What is the Library import statement on the test?
Can you paste here a minimal reproducible example?

**Comment by mshoa** [comment] 2020-03-16 11:56
@HelioGuilherme66 I tried to import the dll file from the command line, but even that failed. 

Error: 
""Importing test library 'C:\Users\moshoaib\AppData\Local\Continuum\anaconda3\Lib\site-packages\RobotFramework\Extensions\AutoItLibrary\AutoItX3.dll' failed: Not a valid file or directory to import.""

even if i just keep the directory it fails to import the directory files.

**Comment by HelioGuilherme66** [comment] 2020-03-16 12:02
Robot does not import DLLs. Go check the User Guide, try to learn how to import and use AutoItLibrary.

Instead of creating an Issue, you should ask on Slack, StackOverflow, Google Group and before that do a good search on Internet.

Closing because this is not RIDE issue.

**Closed by HelioGuilherme66** 2020-03-16 12:02 UTC
Labels: pending
