### ISSUE TITLE
Wrong del key behavior in Text Edit search edit box

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1309] opened 2015-06-03 07:42 UTC
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1271) by renaud... on 21 Aug 2013*

In the Text Edit tab, if you strike the del key to correct something in the search edit box (with the focus on it), it deletes a character in the source instead.

OS: Windows XP
RIDE: 1.1 
Python 2.6.6.

**Comment by yanne** [comment] 2015-06-07 09:15
This is a duplicate of #1367

**Closed by yanne** 2015-06-07 09:15 UTC
Labels: bug, prio-medium
