### ISSUE TITLE
RIDE doesnt preserve last opened Directory

### ISSUE THREAD

**Issue by kstbinom** [robotframework/RIDE#1608] opened 2016-02-29 13:36 UTC
If i close RIDE and open it again, there is no open Directory.
But the default directory is set in settings.cfg

**Comment by HelioGuilherme66** [comment] 2016-02-29 13:57
You must be using an outdated version of RIDE. What version is it (and OS)?
Have you selected that Directory with test files before, from RIDE? (no just editing settings.cfg)

**Comment by kstbinom** [comment] 2016-02-29 14:05
Hey,
I use RIDE 2.0a1 with Python 2.7.3 on Windows 7.
I have selected a Directory with test files before in RIDE.

**Comment by HelioGuilherme66** [comment] 2016-02-29 14:25
That is an experimental version, you are not supposed to create Issues, but communicate through other channels.
That problem caused deliberately because it would crash RIDE. This is fixed in current development.
But if you are using wxPython 2.8.12.1 is better to use the official version.
For this testing is better to use Slack, or Robotframework's Google User Group.

**Comment by HelioGuilherme66** [comment] 2019-05-21 23:04
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Closed by HelioGuilherme66** 2019-05-21 23:04 UTC
