### ISSUE TITLE
RIDE can not enter strings into the Library name inputbox 

### ISSUE THREAD

**Issue by Linhan-Shenzhen** [robotframework/RIDE#1746] opened 2018-04-30 04:20 UTC
Environment:      
windows7-x64    python3.6   robotframework-3.0.4   ride-1.7.1   wxpython-4.0.1

when i add import Library, can not enter strings into the Library name inputbox ,  
the Resource path inputbox is the same situation 
![default](https://user-images.githubusercontent.com/38828352/39421015-b678b172-4c99-11e8-953e-027f09faebe8.png)

**Comment by Linhan-Shenzhen** [comment] 2018-04-30 04:32
Through my attempt ， put the cursor on the input box， press the tab key two times，it can be entered，hope that it can be entered directly 。thanks for upgrating to python3 ！

**Comment by HelioGuilherme66** [comment] 2018-04-30 12:40
@Linhan-Shenzhen That bug is fixed on my latest release, 1.7.2.
https://github.com/HelioGuilherme66/RIDE/releases/tag/v1.7.2

**Comment by Linhan-Shenzhen** [comment] 2018-04-30 14:32
@HelioGuilherme66 
OK！  i will try it，thanks！

**Comment by Linhan-Shenzhen** [comment] 2018-04-30 14:50
@HelioGuilherme66 
 Which version of Pywin32 do I need to download ?   I have seen that the build221+ version of pywin32  Have been transferred to github:
[](https://github.com/mhammond/pywin32/releases)

**Comment by HelioGuilherme66** [comment] 2018-04-30 15:33
I use 220. RIDE only uses this library to create the Desktop Shortcut. (But I think PyAutoIT also needs it).

**Comment by Linhan-Shenzhen** [comment] 2018-04-30 16:31
I use 223 version of pywin32， its ok， Create the Desktop Shortcut is ok.
But this D:\Python36\pythonw.exe  -c "from robotide import main; main()"  does not work,
I modify it to  D:\Python36\python.exe D:\Python36\Scripts\ride.py 
My environment :   windows7-x64  python3.6.5

**Comment by Linhan-Shenzhen** [comment] 2018-04-30 17:05
RIDE-1.7.2, the Library name inputbox can not be entered directly too.
is there other friends meeting the same problem?
Maybe it's the other reason.

**Comment by HelioGuilherme66** [comment] 2019-05-23 23:51
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Closed by HelioGuilherme66** 2019-05-23 23:51 UTC
