### ISSUE TITLE
Lines starting with # but not with #SPACE maybe removed from Text Editor

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2526] opened 2023-01-24 21:43 UTC
With the introduction of parsing `#` lines before *** sections, was considered to be `# ` valid comments.
This causes to not consider content starting with `#` but not followed by a space.
It also, causes Grid Editor to show blank screen, which is solved by removing those commented lines or by adding a space.

This is important bug and must be fixed in next 2.0rc1 release.

**Comment by Harm10** [comment] 2023-01-24 23:29
Also assign this to me? Is this more prio than completing the missing shortcuts to Text editor?

**Comment by JFoederer** [comment] 2023-01-25 10:59
I would opt for a solution that does not remove any data entered by the user.

**Comment by HelioGuilherme66** [comment] 2023-01-25 11:00
@Harm10 If you find a fix create a PR from a branch. I keep assigned to me, because I know where the code is.
Take care because this is very sensitive core code :).

**Comment by Harm10** [comment] 2023-01-25 14:09
@HelioGuilherme66  Reading your comment leads me to the conclusion that this involves some other part of the code than I am working on at the moment. If so, I think it is wiser you try to resolve this and I will continue on Text editor and when finished solve the problem in the Grid editor for multiple cell selection and inserting the sharp comment.
If it is easily explained where the problem resides you can explain that to me via Slack?

**Closed** 2023-01-29 22:05 UTC
Labels: prio-high, bug, fixed, CURRENT DEVELOPMENT

**Comment by JFoederer** [comment] 2023-01-30 10:46
I can confirm that the issue is fixed in RIDE 2.0rc1
