### ISSUE TITLE
Python not responding - robotframework 3.0.4

### ISSUE THREAD

**Issue by BartoszLeczycki** [robotframework/RIDE#1751] opened 2018-05-25 13:21 UTC
Hello everybody,
I have prepared everything to start using robotframework:
```
chromedriver==2.24.1
Pygments==2.2.0
robotframework==3.0.4
robotframework-ride==1.7.1
robotframework-selenium2library==3.0.0
robotframework-seleniumlibrary==3.1.1
selenium==3.12.0
six==1.11.0
wxPython==4.0.1
```

I can start it, but after few seconds everything is hanging, I am getting messages:
![image](https://user-images.githubusercontent.com/28060263/40546135-a7e7212c-602e-11e8-9583-30d34035d026.png)

In task manager:
![image](https://user-images.githubusercontent.com/28060263/40546147-ae08ed42-602e-11e8-8e33-ad0b528e6cfd.png)

In console I got that:
```
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\wx\core.py", line 2158, in Notify
    self.notify()
  File "c:\program files\python36\lib\site-packages\wx\core.py", line 3315, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "c:\program files\python36\lib\site-packages\robotide\editor\editors.py", line 154, in _collabsible_changed
    self._store_settings_open_status()
  File "c:\program files\python36\lib\site-packages\robotide\editor\editors.py", line 89, in _store_settings_open_status
    self._settings.IsExpanded()
RuntimeError: wrapped C/C++ object of type Settings has been deleted
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\wx\core.py", line 2158, in Notify
    self.notify()
  File "c:\program files\python36\lib\site-packages\wx\core.py", line 3315, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "c:\program files\python36\lib\site-packages\robotide\editor\editors.py", line 154, in _collabsible_changed
    self._store_settings_open_status()
  File "c:\program files\python36\lib\site-packages\robotide\editor\editors.py", line 89, in _store_settings_open_status
    self._settings.IsExpanded()
RuntimeError: wrapped C/C++ object of type Settings has been deleted
```

Does anybody know what is going on? 
I was trying to fix it in may different ways, eg set highest priority or change Minimum processor state to biggesr value
I also upgrade all stuff and still same bug.
Thanks for helping me

**Comment by HelioGuilherme66** [comment] 2018-05-26 00:58
@BartoszLeczycki The version of RIDE you are using is from my fork at [here](https://github.com/HelioGuilherme66/RIDE). Issues should be reported there.
Please see the Wiki on my project, for the known problems when using wxPython different from 2.8.12.1.
You could install and try a newer version, but there is no assurance of hangings or crashes.
(Problems happen frequently when using the Grid Editor and navigating in the project tree. It is safer to use the Text Editor.)

**Comment by Nyral** [comment] 2019-06-01 19:11
@BartoszLeczycki Have you tried out latest release? Does the issue still occur? If it is, then please provide more info about when RIDE becomes non responsive.

**Comment by HelioGuilherme66** [comment] 2019-12-01 18:53
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 18:53 UTC
Labels: pending
