### ISSUE TITLE
Running of unselected test-case

### ISSUE THREAD

**Issue by chevi** [robotframework/RIDE#1571] opened 2016-01-21 08:21 UTC
Hi

I regularly catch the problem, which can be reproduced sometimes by this steps to reproduce:
1. Autosave is ON
2. Select test-case in RIDE and run test1
3. After test finished, unselect test1 and select test2. Run test

Result:
Runned test1 - which is not selected
![screenshot at 11-14-44](https://cloud.githubusercontent.com/assets/1729590/12475026/d932605c-c030-11e5-9195-acd480d859f2.jpg)

Expected:
Runned only selected tests

**Comment by HelioGuilherme66** [comment] 2016-01-21 12:26
Please give more info about versions:
RIDE, wxPython, Operative System

From your screenshot we see the tests have equal starting names, maybe that is interfering. Did you wait some seconds before starting the test2 run?

**Comment by chevi** [comment] 2016-01-21 12:53
This issue sometimes reproduced in our team on different laptops more than 2 years already. Tests have different names. Yes, I wait, time doesn't make role on this. I suppose that problem in part of select/unselect test-case or maybe with autosave

OS: OS X El Capitan 10.11.2 / Ubuntu 14.04
wxPython 2.8.12.1 (gtk2-unicode)
RIDE 1.5.1 running on Python 2.7.6. (but was on prev versions too)

**Comment by StefanIGit** [comment] 2016-06-01 10:37
I have the same problem only sometimes :D of cause and right now.
Selected is 1 TC but executed are 2.
The TC which is run but not selected is a finished one I run some minutes before, then I created a new TC the currently selected one. But I cannot reproduce it that way.

Closing and reopening RIDE "fixes" the problem.

Win 7 x64
20160531 13:49:46.986 [INFO]: Found Robot Framework version 2.9.2 from 'C:\Python27\lib\site-packages\robot'.
20160531 13:49:46.986 [INFO]: Started RIDE 1.5 using python version 2.7.9 with wx version 2.8.12.1 in win32.

**Comment by StefanIGit** [comment] 2016-09-29 06:39
Ups I meant issues 1463.
Can I change this?

**Comment by HelioGuilherme66** [comment] 2016-09-29 12:25
I found that when Test Cases names have wildcards, like '?' or '*' they will actually be applied. This is a feature of Robot Framework, which is also performed by RIDE. Please confirm that your tests are not using those symbols.

Below is the output of tests run with robot (which is exactly the same with RIDE):
```
C:\>robot Example.robot
==============================================================================
Example
==============================================================================
test1                                                                 | PASS |
------------------------------------------------------------------------------
test2                                                                 | PASS |
------------------------------------------------------------------------------
test?3                                                                | PASS |
------------------------------------------------------------------------------
test4                                                                 | PASS |
------------------------------------------------------------------------------
test*1                                                                | PASS |
------------------------------------------------------------------------------
test6                                                                 | PASS |
------------------------------------------------------------------------------
Example                                                               | PASS |
6 critical tests, 6 passed, 0 failed
6 tests total, 6 passed, 0 failed
==============================================================================
Output:  C:\output.xml
Log:     C:\log.html
Report:  C:\report.html

C:\>robot -t test2 Example.robot
==============================================================================
Example
==============================================================================
test2                                                                 | PASS |
------------------------------------------------------------------------------
Example                                                               | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\output.xml
Log:     C:\log.html
Report:  C:\report.html

C:\>robot -t test? Example.robot
==============================================================================
Example
==============================================================================
test?                                                                 | PASS |
------------------------------------------------------------------------------
test1                                                                 | PASS |
------------------------------------------------------------------------------
test2                                                                 | PASS |
------------------------------------------------------------------------------
test4                                                                 | PASS |
------------------------------------------------------------------------------
test*                                                                 | PASS |
------------------------------------------------------------------------------
Example                                                               | PASS |
5 critical tests, 5 passed, 0 failed
5 tests total, 5 passed, 0 failed
==============================================================================
Output:  C:\output.xml
Log:     C:\log.html
Report:  C:\report.html

C:\>robot -t test* Example.robot
==============================================================================
Example
==============================================================================
test?                                                                 | PASS |
------------------------------------------------------------------------------
test1                                                                 | PASS |
------------------------------------------------------------------------------
test2                                                                 | PASS |
------------------------------------------------------------------------------
test4                                                                 | PASS |
------------------------------------------------------------------------------
test*                                                                 | PASS |
------------------------------------------------------------------------------
test6 no wildcard                                                     | PASS |
------------------------------------------------------------------------------
Example                                                               | PASS |
6 critical tests, 6 passed, 0 failed
6 tests total, 6 passed, 0 failed
==============================================================================
Output:  C:\output.xml
Log:     C:\log.html
Report:  C:\report.html
```

**Comment by chevi** [comment] 2016-09-29 12:46
Hi

No, tests doesn't have such symbols
My tests from first message have names:

- Report - Redo
- Report - created
- Report - approved

It's like RIDE is still remember old choice of tests.

**Comment by StefanIGit** [comment] 2016-09-29 14:29
Here it us the same no wildcarsd in test caes or test suite or resource or library names and not in file or folder names.

It feels like the deselect event does not always remove the test from list and select and again deseletc does not fix it. I have to restart Ride.

**Comment by StefanIGit** [comment] 2016-11-17 12:51
I have autosave disabled  to check if it related and no it is not.
I had it just a few minutes ago.
I do start the TC by F8 hot key, then it asks me if I want to save and I press Enter (Yes)

Next try use ctrl+s the F8.... to be continued

**Comment by verybadsoldier** [comment] 2016-12-20 11:03
I can say that the problem is that RIDE passes an `argfile.txt` to pybot which contains unselected testcases. This is the log output when I run pybot from RIDE:
`command: pybot.bat -L TRACE --argumentfile c:\users\robin\appdata\local\temp\RIDEdsl_s0.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:58947:False C:\Projects\testing\robot-framework-testing\trunk\robot-framework-test
`

This is the content of `argfile.txt`:
```
--outputdir
--outputdir
c:\users\robin\appdata\local\temp\RIDEdsl_s0.d
-C
off
-W
168
--suite
Robot-Framework-Test.SC4
--test
Robot-Framework-Test.SC4.SC4-91.1-Bildformat ist einstellbar
--suite
Robot-Framework-Test.SC4
--test
Robot-Framework-Test.SC4.SC4-64.1-Bildzaehler manuell ruecksetzbar
```

The test `Robot-Framework-Test.SC4.SC4-64.1-Bildzaehler manuell ruecksetzbar` is not selected in RIDE, only `Robot-Framework-Test.SC4.SC4-91.1-Bildformat ist einstellbar` is.

**Comment by StefanIGit** [comment] 2018-01-17 07:58
I can reproduce it this way...

- Create new projekt
- add 1 TC or more
    like "test case 1" with "log | blablup"
- Save all

- select this TC
- rename the TC (press Enter to finish the rename)
- deselect
- save it, does not matter if manual or auto save
- click Run Test or F8 or Start on Run tab

TC "test case 1" will be run, not question about no TC selected.
If u have more than 1 TC in this suite only the renamed one will be executed.


Side note, while looking into this for me really annoying  error I added this print in testrunnerplugin.py
`
    def OnTestSelectedForRunningChanged(self, message):
        print 'OnTestSelectedForRunningChanged: %s' %message.tests
        self._names_to_run = message.tests
`
this  show me this:
`
OnTestSelectedForRunningChanged: set([(u'selectLost', u'selectLost.test case 2 -1'), (u'selectLost', u'selectLost.test case 1 5cfdfg5')])
OnTestSelectedForRunningChanged: set([(u'selectLost', u'selectLost.test case 2 -1 54654'), (u'selectLost', u'selectLost.test case 1 5cfdfg5')])
OnTestSelectedForRunningChanged: set([(u'selectLost', u'selectLost.test case 2 -1 54654'), (u'selectLost', u'selectLost.test case 1 5cfdfg5')])
OnTestSelectedForRunningChanged: set([(u'selectLost', u'selectLost.test case 2 -1 54654'), (u'selectLost', u'selectLost.test case 1 5cfdfg5')])
`
first I selected "test case 2 -1"
then renamed it "test case 2 -1 54654"
Now I can Select or Deselect "test case 2 -1 54654" but the TC is not removed from the message.tests

**Comment by HelioGuilherme66** [comment] 2018-02-03 20:03
@chevi @verybadsoldier Just some comments about this issue. But first I hope you are still using RIDE ;)
- I have been trying to debug this, even on my fork on [latest release 1.7.1](https://github.com/HelioGuilherme66/RIDE/releases/tag/v1.7.1) which is still present.
- I am reproducing 100% it with latest comment from @StefanIGit.
- The problem is when renaming test case there is no messaging to TestRunner, so it run the test based on its python object address (which is the same as before renaming).
- It may look simple to fix, but it is not. I will take much more time to fix this (and any brave contributor will be very welcome to help me ;) ).
- There is a workaround to not restarting RIDE, which is to open another test suite and open again the initial one. This clears memory objects.

**Comment by simplyviks** [comment] 2018-08-30 17:37
Hi,

I have a requirement where in i want to write the argumentfile.txt as below
--test
test_scenario1
--test
test_scenario2

if you note i just want the test case name and not the longName(X.Y.Z.test_scenario1), how can i achieve it inside testrunner.py

code snippet from testrunner.py
 def _create_standard_args(
            self, command, profile, pythonpath, console_width, names_to_run):
        standard_args = []
        standard_args.extend(profile.get_custom_args())
        self._add_tmp_outputdir_if_not_given_by_user(command, standard_args)
        self._add_pythonpath_if_in_settings_and_not_given_by_user(
            command, standard_args, pythonpath)
        # Have to use short options, because of long option was changed in
        # RF 2.8 -> 2.9, and we don't necessarily know the installed version.
        #standard_args.extend(["-C", "off"]) # --consolecolor
        #standard_args.extend(["-W", console_width]) # --consolewidth
        for suite, test in names_to_run:
            print "test:" + test
            standard_args += ['--test', test ]
        return standard_args


Any help will unblock me , Thanks in advance!!

**Closed** 2019-10-27 18:50 UTC
Labels: bug, prio-low
