### ISSUE TITLE
stop button not working in case of sleep or external program start

### ISSUE THREAD

**Issue by bernulabese** [robotframework/RIDE#1648] opened 2016-08-26 11:38 UTC
To recreate the problem:
**\* Settings ***

**\* Test Cases ***
forever runner
    sleep    300

When the tester presses the stop button the robot continue the sleep and stops after the 300 seconds.  The same happens when a program start by python ssh.

**Comment by simplyviks** [comment] 2018-08-30 10:49
i am also facing this issue, is it broken?

**Comment by Nyral** [comment] 2019-05-24 00:09
@HelioGuilherme66 Double pressing the stop button will force close the execution, but report will be incomplete.

On the other hand single button press will wait for the step currently running at that moment to finish and then skip directly to teardown keyword (if available). What do you think?

**Comment by HelioGuilherme66** [comment] 2019-05-24 12:59
@Nyral We cannot do anything about this because is by design of `robot`. It will expect two STOP signals.

**Comment by HelioGuilherme66** [comment] 2019-05-24 13:00
Closed because (use OR operator):

- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)

**Closed by HelioGuilherme66** 2019-05-24 13:00 UTC
