### ISSUE TITLE
Collapse/expand works on the entire treeview

### ISSUE THREAD

**Issue by Soothsilver** [robotframework/RIDE#1844] opened 2019-03-01 11:09 UTC
If you click the expand/collapse button next to a suite, the entire treeview becomes blank, appears to collapse/expand various nodes (even other than the chosen suite), and after a couple of seconds enters the expected state (the proper collapse/expand). 

In RIDE 1.5.2.1, only the selected suite was collapsed/expanded, and faster.

This is on Windows 10, Python 2.7, RIDE 1.7, wxPython 4.0.4.

By the way, thank you for taking care of RIDE again. It looks way prettier now and it even appears faster (in other cases).

**Comment by Nyral** [comment] 2019-06-01 17:04
@HelioGuilherme66  I can't reproduce this.

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:22
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:22 UTC
Labels: pending
