### ISSUE TITLE
Import Library Spec XML does nothing

### ISSUE THREAD

**Issue by CMTaylor** [robotframework/RIDE#1872] opened 2019-04-04 17:30 UTC
My main reason to try upgrading RIDE to the 1.7.3.1 version was to get Import Library Spec XML working again (it didn't work in the old 1.5.2.1 version I was using). It still doesn't work! Importing an appropriate XML file appears to do nothing, even after restarting RIDE. This used to work way back when you had to hand-copy the XML files to a "special place". I haven't seen it work since.

**Comment by HelioGuilherme66** [comment] 2019-04-07 23:58
@CMTaylor I did not find this problem. I will see if for example adding SikuliX XML file would work.
You have the option to Import XML file on the settings section. If that fails, there should be in RIDE Log the error output. Please see if you can give more info. Thanks.

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:31
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:31 UTC
Labels: pending

**Comment by oudinolivier** [comment] 2020-04-13 15:17
I just came accross the same issue with HttpRequestLibrary and DbLibrary, and it turns out it was a Spec XML file info was missing.

I had the Spec XML file for SeleniumLibrary working without any problem...
So I compared all three files together:
- At the beginning of the file, you'll see an empty "version" markup
- I found out version is mandatory for the process inside RIDE to work
- I added the missing info manually and it works like a charm :)

Hope this helps
