### ISSUE TITLE
Remebering the customized (visual) Editor column widths

### ISSUE THREAD

**Issue by VipSaran** [robotframework/RIDE#1450] opened 2015-06-03 13:33 UTC
Currently (RIDE v1.3, Windows 32-bit on Windows 7 64-bit) when columns widths are resized, leaving the current view forgets those customizations.

It would be usable for Editor to remember the customized column widths (per view) for the current session.

**Comment by yanne** [comment] 2015-06-07 09:05
This is a duplicate of #1361

**Closed by yanne** 2015-06-07 09:05 UTC
Labels: enhancement, prio-low

**Comment by VipSaran** [comment] 2015-06-17 11:23
This doesn't seem to work (i.e. columns manually resized are not remembered), regardless if Auto size columns is off or on.

**Comment by yanne** [comment] 2015-06-27 12:54
Yes, it is not implemented yet. I just closed this, because the issue already existed as #1361. We'll try to have only one open issue per a feature request :)

**Comment by VipSaran** [comment] 2015-06-27 13:00
:+1: 
It's clear, sorry. Dunno how I missed the "duplicate" comment...
