### ISSUE TITLE
System freezes on Windows 10

### ISSUE THREAD

**Issue by Soothsilver** [robotframework/RIDE#1843] opened 2019-03-01 10:52 UTC
When using RIDE with large suite (1,000 tests), if you're using Windows 10, RIDE randomly causes the entire system to freeze for 10 seconds up to 1 minute when you click on anything in the RIDE window. I've seen this happen on many computers, all of them with Windows 10. It never happens on Windows 7.

This happens both in RIDE 1.5.2.1 (with recommended wxPython) and with RIDE 1.7.3.1 (I tested with wxPython 4.0.4, Python 2.7).

**Comment by HelioGuilherme66** [comment] 2019-03-01 10:57
Is that a single test file with 1,000 tests? Or a directory with many test files?
Being a problem existing in 1.5.2.1, it proves that was not caused by resent code changes.
Reports of slow performance when using many test cases, are known, and are in my TODO list to analyse.

**Comment by Soothsilver** [comment] 2019-03-01 11:05
It is a directory with many directories. There are about 150 files which in total have 1000 test cases.

**Comment by HW71** [comment] 2019-05-08 15:54
Hi all,

just wanted to join in here since I encounter exactly the same issue. Recently we switched laptops from Windows 7 to Windows 10, and now unfortunately RIDE freezes the whole system for 10 seconds or so. That is:

- impossible to switch to other applications (neither by task bar, nor by <Alt-Tab>)
- even graphs of Windows Task Manager freezes

Actually it looks somehow related to leaving focus from main application window, because I see this quite often when right-clicking on a test suite in order to get the context menu up. This doesn't work most of the times - instead system freezes, and after 10 seconds the context menu shows-up. :-(

Today I tried to avoid to brng-up the context menu. Instead I selected / deselected tests manually. This seemed to help in the beginning, but after running RIDE for several hours I encountered the same issue again.

Similar to @Soothsilver we have tons of test suites containing 1.000+ test cases. I can provide some more details with accurate numbers on that, if needed.

Thanks so much in advance & kind regards!

Cheers, Erik

**Comment by EPMageshwari** [comment] 2019-06-24 06:08
Any update on this issue? I am also seeing the windows freeze, when using RIDE.

**Comment by HW71** [comment] 2019-06-24 06:22
Hi @EPMageshwari 

not from my side - sorry. We're still struggling with this issue and some of us now use a Windows 7 VM in order to overcome this issue.

Besides closing RIDE frequently and reloading the test suite I'm currently working on I didn't find a reliable solution for this. Even loading less test cases (by selecting a test suite located lower in the hierarchie) just seems to postpone the freezes a bit - but it's not a guarantee that this problem doesn't show-up after an hour or so.

Cheers, Erik

**Comment by Soothsilver** [comment] 2019-06-24 17:19
Hi, I don't have a fix, but I have a reimplementation of RIDE at https://github.com/Soothsilver/snowride, which I created precisely to avoid this bug. Of course, it doesn't have the long-term stability or full-featuredness of RIDE, but if you're going as far as running RIDE in a VM, it may be worth trying.

**Comment by HW71** [comment] 2019-06-24 18:36
Hi @Soothsilver ,

thanks a lot for the hint - will give it a try tomorrow! :-)

Cheers, Erik

**Comment by HelioGuilherme66** [comment] 2019-06-25 08:31
Things to investigate:
- Is RIDE looking for all keywords documentation when a folder is opened?
-- Remedy: Only look for documentation from opened test suite.
- Is Tree element too big to process and it slows down RIDE readiness?
-- Remedy: Have a "high-water" marker to stop loading Tree, or,
                  Have Tree to be loaded in background, or,
                  Have a switch to hide Tree on user choice (last resort solution).

**Comment by Soothsilver** [comment] 2019-06-25 19:53
The strange thing is that it's not just RIDE which freezes. I also considered that it might be documentation (I  have maybe twenty XML files and twenty Python files loaded into RIDE in that big project) but if it was RIDE processing slowing down the system, I would expect only RIDE to freeze.

What happens instead is that the entire operating system freezes -- you can move the mouse pointer but do nothing else. That's why I suspected something related to the tree view control but I never managed to create a reproducible test case.

**Comment by Nyral** [comment] 2019-06-25 21:49
@Soothsilver It's simple to reproduce. 

- Load a 50 suites (with ~50 test cases each)
- Expand all in tree
- Start scrolling down using mouse wheel (important)
- During scrolling the GUI will start lagging (i.e. it continues to scroll without you doing anything). 
- When that happens click on another GUI element in RIDE or on another window/taskbar/etc.
Every window/taskbar/etc you click on will become frozen. After a while everything else freezes too. If you wait a bit longer it will recover (time depends on how many tests you loaded).

During this event, the CPU usage does not become high. Ctrl+Alt+Delete also doesn't activate until the freeze passes. It's really weird.

**Comment by Soothsilver** [comment] 2019-06-26 07:57
Thanks, @Nyral. I can reproduce using your steps perfectly. Indeed not even Ctrl+Alt+Delete works.

**Comment by Nyral** [comment] 2019-06-26 18:38
@Soothsilver I'm glad you managed to. I've also tried to kill the python process during this freeze (with a separate scripts that has a timer). That was unsuccessful as well (RIDE window becomes blank).

First we need to figure out where the issue is coming from. If it's from wx, then we can request help from those developing it. In order to prove this we need to run the Tree separately from RIDE.

**Comment by Temizzi** [comment] 2019-07-09 02:26
I can confirm this happen to me as well now in Windows 10. What a nightmare. I have 30 folders and under these 30 folders I have several test suites with testcases. Whenever I tried to click anything like keyword or scroll down and my entire vm is totally freezing. I had to wait for at least 2-5 minutes to get it okay back. My other collageaus use windows 7 for their VMs and they don't experience this freezing issue.

**Comment by Temizzi** [comment] 2019-07-09 02:29
I can confirm this happen to me as well now in Windows 10. What a nightmare. I have more than 200 folders and under these 200 folders it contains several test suites with testcases. Whenever I tried to click anything like keyword or scroll down/up the the left pane, then my entire vm is totally freezing. I had to wait for at least 2-5 minutes to get it okay back, but it will keep happening again. My other collageaus use windows 7 for their VMs and they don't experience this freezing issue.

**Comment by HW71** [comment] 2019-07-09 04:40
@Temizzi You might want to give the Java re-implementation of RIDE ("Snowride") a try: https://github.com/Soothsilver/snowride
I use it for quite some days now and didn't encounter this "freezing" bug any more. There was just a minor issue with our special naming of directories in order to get them sorted, but @Soothsilver fixed this one within hours!

**Comment by Temizzi** [comment] 2019-07-09 14:01
@HW71 Thanks, will give a try.

**Comment by jai-yadav** [comment] 2019-07-11 18:57
Snowride looked very promising at first then it didn't load the library xmls and no error msg as well. We need a fix of this windows problem ASAP :(

**Comment by Soothsilver** [comment] 2019-07-12 20:54
@jai-yadav Snowride certainly has a lot of downsides, but it does load library XMLs. Put the path to the folder with the library XMLs into Snowride in Tools - Settings. If it doesn't work anyway, run Snowride from the command line and the reason why the library XML file was rejected will be printed on standard error output.

**Comment by jpmusico** [comment] 2019-07-30 21:16
I was having this exactly issue with Ride... but looks like a simple workaround solved my problem... usually when the issue happens, opening task manager was making it to unfreeze... so what I did was to leave task manager always opened... and Ride never freezes again. 
My suite has more than 2200 scripts and this was a pain when expanding a few suites.

**Comment by Nyral** [comment] 2019-07-30 21:27
@jpmusico Not working for me. What OS are you using?

**Comment by jpmusico** [comment] 2019-07-30 21:31
I'm using Windows 10 Enterprise, 64, with 16 GB of RAM

**Comment by jpmusico** [comment] 2019-07-30 21:40
sorry... actually I just tried expanding all suites and it's not good :(, but for the ones I usually open it's better than before

**Comment by Nyral** [comment] 2019-07-30 21:47
Ah, okay.

**Comment by gjungberg** [comment] 2019-09-17 22:11
Any updates on this issue?. I still have the same problem on the latest code I build today.

**Comment by pakal** [comment] 2019-09-20 13:16
i'm very unsure it's related, but this bugfix might help for the big freeze when collapsing treeview items : Please have a look at https://github.com/robotframework/RIDE/issues/2017 and tell if this bugfix works in your case

**Comment by Nyral** [comment] 2019-09-20 19:40
The fix mentioned by pakal is not related to this issue.

@pakal Please don't comment on issues if you're unsure that they're related.

**Comment by sfdcselenium01** [comment] 2020-03-16 22:39
I've experienced same issue - RIDE freeze on Windows 7 before, and now it freeze on Windows 10, too. I have 1500+ test cases. It seem related with tree view - it happen almost every day when I navigate from test case to test case under different folders

**Comment by HelioGuilherme66** [comment] 2020-03-17 00:43
@sfdcselenium01 We now have on the development version, the possibility to hide the project explorer/tree view (in one attempt to help on this issue).  So, there are some "workarounds" to attempt  to reduce the long waiting time. Only open a test suite at the time. Not the full folder structure. You can easily open a folder or test suite, by right-clicking on the File explorer. If you use python3 then you can try the current development version. Thanks.

**Comment by sfdcselenium01** [comment] 2020-03-18 16:06
@HelioGuilherme66 , I download development version and try it, still have same issue. RIDE freeze windows 10

**Comment by Nyral** [comment] 2020-03-21 21:57
@sfdcselenium01 Read my comment [here](https://github.com/robotframework/RIDE/issues/1668#issuecomment-565640555).

**Comment by valeriobruno** [comment] 2020-05-03 14:46
Are you able to replicate the issue systematically?

**Comment by cbeytas** [comment] 2020-05-10 21:20
Most likely related to https://github.com/wxWidgets/Phoenix/issues/1633
The tree widget has many child windows added to it, all based of the `_ActionHandler` class. They appear to be invisible (?) but are still valid widgets that need to be handled by the scrolled window. Likely they are causing the slowdown.

**Comment by Tim-QA** [comment] 2020-05-12 08:19
This issue affects also Windows Server 2019 and not Windows Server 2008 R2.

**Comment by dinesh16kr** [comment] 2020-05-26 08:39
Hi @Soothsilver,
Can you please let me know how to install/use Snowride. I have existing Ride setup with lots of cases in that. What all changes I need to make to use Snowride.
Thanks.

**Comment by HelioGuilherme66** [comment] 2020-05-26 13:59
@dinesh16kr Why don't you see the instructions at [he's project](https://github.com/Soothsilver/snowride)? It is just a Java app :).

**Comment by Soothsilver** [comment] 2020-05-26 15:17
@dinesh16kr There's a download link in the readme of the repository @HelioGuilherme66 pointed you to. Then double-click it or use the command "java -jar snowride.jar"

**Comment by cbeytas** [comment] 2020-06-06 18:04
As a stab in the dark, is it necessary for `_ActionHandler` to be based off `wx.Window`?
If so, do they need to be children of the tree? You could possibly make them children of the parent of the tree:
In `treenodehandlers.py` line 91:
`wx.Window.__init__(self, tree.GetParent())`

No idea what kind of side-effects this could have, but it fixes the issue for me. Seems like adding too many children to a window is an operating system limit that must be avoided.

**Comment by HelioGuilherme66** [comment] 2020-06-06 19:25
@cbeytas Please make a Pull Request with you complete fix or implementation. That way we can validate if it fixes and does not break other functions. It would be really good if more people contribute with code. Thanks.

**Closed** 2020-07-16 22:05 UTC
Labels: enhancement, help_wanted, prio-high
