### ISSUE TITLE
RIDE produces Validation error when renaming test cases (removing characters)

### ISSUE THREAD

**Issue by technigirl** [robotframework/RIDE#1823] opened 2019-02-06 21:35 UTC
When renaming a test case, Ride displays an error in the GUI (see attached screenshot).  The name that is saying already exists, is the *new* name I am giving the keyword.

Example:
1.  Create a keyword such as the one in the screenshot.
2.  Right click and click, "Rename"
3.  Remove some characters from the keyword
4.  You should see a similar error to that shown in the screenshot.

Sometimes, RIDE might crash completely.  I am not sure what triggers a crash vs. just a validation error.  The crash results in a segmentation fault.

Environment:
MAC OSX (Mojave)
RIDE 1.74dev
Python 3.7
![screen shot 2019-02-06 at 3 28 04 pm](https://user-images.githubusercontent.com/6920990/52375223-c2637d00-2a24-11e9-97bc-6f670ab9d741.png)

**Comment by Nyral** [comment] 2019-06-01 19:38
@HelioGuilherme66 Reported first by #1741. Can we merge these 2 tickets?

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:08
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:08 UTC
Labels: pending
