### ISSUE TITLE
RIDE will not run in ubuntu 16.04

### ISSUE THREAD

**Issue by rcabreros** [robotframework/RIDE#1629] opened 2016-04-28 07:43 UTC
Running ride.py in the terminal will give me this error below:
+++++++++++++++++++++++++++++
Wrong wxPython version.
You need to install wxPython 2.8.12.1 with unicode support to run RIDE.
wxPython 2.8.12.1 can be downloaded from http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/
+++++++++++++++++++++++++++++

I already re-installed wxPython 2.8.12.1 but still ride.py will not run/launch.

**Comment by timjohncurtis** [comment] 2016-05-03 13:27
I know the wxpython development is currently in progress, however I have made a small change as a workaround, you will get the untested warning as it is not full support, but the change passes all unit tests, feel free to throw the change away if the package owner does not feel it is appropriate to pull this change in. 

https://github.com/robotframework/RIDE/pull/1632/files

**Comment by mdontsov** [comment] 2016-05-12 12:55
sudo apt-get autoremove python-wx*
sudo pip uninstall robotframework-ride
sudo dpkg -i /<downloads_dir>/python-wxversion_2.8.12.1+dfsg-2ubuntu2_all.deb
sudo dpkg -i /<downloads_dir>/libwxgtk-media2.8-0_2.8.12.1+dfsg-2ubuntu2_amd64.deb
sudo dpkg -i /<downloads_dir>/python-wxgtk2.8_2.8.12.1+dfsg-2ubuntu2_amd64.deb
pip install robotframework-ride
ride.py

**Comment by divfor** [comment] 2016-05-17 06:57
see ride's installation instructions: on Linux you should use 'sudo apt-get install python-wxgtk2.8' to install wxpython.

**Comment by Th33x1l3** [comment] 2016-06-21 16:27
@divfor problem is that package doesn't exist in ubuntu normal repos. You must use older repos, or a ppa. 

Also i have this error too. Tried to install using a older repo, with add it to apt, install with 'sudo apt-get install python-wxgtk2.8'. It installed with all required packages. But ride will not open

**Comment by sdesbure** [comment] 2016-06-30 09:13
hello,
same issue with debian stretch (and I totally prefer using GTK3 so the pull proposition makes me happier ;) )

**Comment by shadow1163** [comment] 2016-07-01 17:58
Any solution with the issue?

**Comment by sdesbure** [comment] 2016-07-02 12:15
Hi, according to the comment in push request, it seems to b e solved on the
beta version:

We have this fixed in PR #1610. You may install from
https://github.com/HelioGuilherme66/RIDE/releases/tag/v2.0a2with command:
pip install -U
https://github.com/HelioGuilherme66/RIDE/archive/v2.0a2.tar.gz

**Comment by YogeshSomawar** [comment] 2016-07-05 08:44
This will resolve the issue : 
http://askubuntu.com/questions/789302/install-python-wxgtk2-8-on-ubuntu-16-04

**Comment by sdesbure** [comment] 2016-07-05 08:47
@YogeshSomawar I think your proposal is not good as you'll have packages that won't have upgrades and may break. Proposal from Hélio seems more future proof IMHO

**Comment by YogeshSomawar** [comment] 2016-07-05 08:50
@sdesbure , I have tried 
pip install -U https://github.com/HelioGuilherme66/RIDE/archive/v2.0a2.tar.gz 

It is giving error : 
{code}
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-cGfVVP-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Drq50g-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-cGfVVP-build/
{code}

As there is no solution to use robot on ubuntu 16.04, time being my solution works...

**Comment by HelioGuilherme66** [comment] 2016-07-05 13:14
I don't know why you are having errors, maybe you could try to download the package and install with sudo. For example:
`wget https://github.com/HelioGuilherme66/RIDE/archive/v2.0a2.tar.gz`
`sudo pip install -U the "path to file name"`   (probably ./RIDE-2.0a2.tar.gz )

Other thing that comes to mind, is Python the 2.7 variant? If you have both Python 3.4 and 2.7, then use the correct pip to install RIDE.

**Comment by mdontsov** [comment] 2016-10-14 09:27
Executing this particular sequence of steps should make RIDE work under Ubuntu 16.04.1
Install:
1) python-wxversion_2.8.12.1+dfsg-2ubuntu2_all.deb
2a) libgstreamer0.10-0_0.10.36-1.5_amd64.deb
2b) libgstreamer-plugins-base0.10-0_0.10.36-1_amd64.deb
2c) libwxbase2.8-0_2.8.12.1+dfsg-2ubuntu2_amd64.deb
2d) libtiff4_3.9.6-11+deb7u1_amd64.deb
2e) libwxgtk2.8-0_2.8.12.1+dfsg-2ubuntu2_amd64.deb
3) libwxgtk-media2.8-0_2.8.12.1+dfsg-2ubuntu2_amd64.deb
4) python-wxgtk2.8_2.8.12.1+dfsg-2ubuntu2_amd64.deb
Then:
ride.py

**Comment by k1-hedayati** [comment] 2016-11-09 07:53
@mdontsov freeze isn't working,

```
Collecting wxPython==2.8.12.1 (from -r requirements.txt (line 8))
  Could not find a version that satisfies the requirement wxPython==2.8.12.1 (from -r requirements.txt (line 8)) (from versions: )
No matching distribution found for wxPython==2.8.12.1 (from -r requirements.txt (line 8))
```

Waiting for xenial support

**Comment by mdontsov** [comment] 2016-11-09 08:01
@k1-hedayati 

what is your 'pip freeze' output?

**Comment by k1-hedayati** [comment] 2016-11-09 09:14
@mdontsov 

```
--> cat requirements.txt
adium-theme-ubuntu==0.3.4
decorator==4.0.10
robotframework==3.0
robotframework-ride==1.5.2.1
robotframework-selenium2library==1.8.0
selenium==3.0.0
unity-lens-photos==1.0
wxPython==2.8.12.1
wxPython-common==2.8.12.1
--> pip install -Ur requirements.txt
Collecting adium-theme-ubuntu==0.3.4 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement adium-theme-ubuntu==0.3.4 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for adium-theme-ubuntu==0.3.4 (from -r requirements.txt (line 1))
```

**Comment by HelioGuilherme66** [comment] 2016-11-09 10:23
Where did you get those requirements.txt from?
As alternative to `pip freeze` you may use `pip list`. Post here the output.

Are you sure you are using Python 2.7? Try to use `pip2` instead of `pip`.

**Comment by HelioGuilherme66** [comment] 2019-05-09 22:50
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Closed by HelioGuilherme66** 2019-05-09 22:50 UTC
