### ISSUE TITLE
Neither Contextmenu nor popup are visible under Windows

### ISSUE THREAD

**Issue by sbruhn** [robotframework/RIDE#1467] opened 2015-06-10 08:21 UTC
System is Windows 7 Ultimate 64bit:

RIDE 1.4b2 running on Python 2.7.8. 

When rightclicking on a tree entry (testcase or userkeyword) no contectmenu is visible. 
It is possible to see the frame starts to be dissplayed, but it immedeatly disappears. 

Same behavior for keywords in tests and Ctrl-Blank for keywork completion. 

OT:
Menu bar works as expected.

**Comment by yanne** [comment] 2015-06-11 13:37
Do you get any errors in the Command Prompt? Are there any errors in RIDE Log? (Tools | Ride Log)

I cannot reproduce this in my Windows 7 Professional virtual machine.

**Comment by sbruhn** [comment] 2015-06-15 10:41
No i don't receive anything in the console window. 
Also RIDE Log is clean:
20150615 12:29:25.372 [INFO]: Started RIDE 1.4b3 using python version 2.7.8 with wx version 2.8.12.1 in win32.
Found Robot Framework version 2.8.7 from C:\Python27\lib\site-packages\robot

But maybe this is the rootcause, wx python 32bit on a 64 bit windows installation. 

I'll try to set it up on a 32bit Windows maschine

**Comment by sbruhn** [comment] 2015-06-17 13:09
This was an installation problem. 
There was an old wxPython installation (2.8.11.0) under %USERPROFILE%\AppData\Roaming\Python\Python27\site-packages. 
I installed the required 2.8.12.1 under c:\Python27\libs\site-packages ...
After that the ride started without error message.
But is it possible that it loaded the old wxPython?
Is it possible, that for the check of the wxpython version at the startup of the ride, the one under c:\Python27 was used, but for running the ride under AppData?  

Anyhow, after deleting the wxPython installation under AppData, everything works properly.

**Comment by yanne** [comment] 2015-06-27 12:58
Actually, RIDE already check that it is running with 2.8.12.1 and gives a warning if older version is used.

I am still unsure about the root cause of your problem, but it's probably not anything that needs to fixed in RIDE, so I'll close this issue.

**Closed by yanne** 2015-06-27 12:58 UTC

**Comment by shamaho** [comment] 2015-10-30 18:30
I'm having the exact same issue.
