### ISSUE TITLE
Error fatal error occurred when RIDE ran case

### ISSUE THREAD

**Issue by happymaof** [robotframework/RIDE#1760] opened 2018-07-17 10:44 UTC
python 2.7.1.4
robotframework (2.8.5)
robotframework-ride (1.5.2.1)
robotframework-selenium2library (1.7.4)
robotframework-seleniumlibrary (3.1.1)
wxpthon 2.8.1

environment variable:
c:\Python27;c:\Python\Scripts;C:\Python27\Lib\site-packages

ERROR MESSAGE:Run when

command: pybot.bat --argumentfile c:\users\admini~1\appdata\local\temp\RIDE9q4hgq.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:51138:False C:\Python27\test\test.txt
[Error 2] 

There are many ways to try not to eliminate error2

**Comment by happymaof** [comment] 2018-07-18 01:53
pybot.bat C:\Python27\test\test.txt is OK
==============================================================================
Test
==============================================================================
Test.111
==============================================================================
12                                                                    | PASS |
------------------------------------------------------------------------------
Test.111                                                              | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Test                                                                  | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\Python27\Scripts\output.xml
Log:     C:\Python27\Scripts\log.html
Report:  C:\Python27\Scripts\report.html

The test Document content ：
*** Test Cases ***
12
    ${tem}    get time
    log    ${tem}

**Comment by HelioGuilherme66** [comment] 2018-07-18 12:43
Could not reproduce your error. You could try to execute in RIDE with the option ` --loglevel TRACE`.
Another thing you can try is to copy `test.txt` to a different folder not under C:\Python27.

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:02
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:02 UTC
Labels: pending
