### ISSUE TITLE
Windows Installation instructions / PyPI downloads are incorrect.

### ISSUE THREAD

**Issue by emanlove** [robotframework/RIDE#1659] opened 2016-10-04 16:02 UTC
The latest instructions for the installation of RIDE are confusing in that the latest version on PyPI, [1.5.2.1](https://pypi.python.org/pypi/robotframework-ride/), does not include the Windows Installer, only the source in a tar gzipped archive. That last version on PyPI which has the windows installer is [1.5](https://pypi.python.org/pypi/robotframework-ride/1.5). Those who are not familar with installation can (and have) been confused by this. Also the windows installer adds a nice shortcut which one can not get from pip installing the source.

**Comment by HelioGuilherme66** [comment] 2016-10-04 21:15
The problem with the installer is already solved from PR #1597. I hope it will be merged to the next release.
I agree in having only `pip` as installation manager.  If we could have a new release this year, maybe we could remove the windows installer from PyPI.

**Comment by Nyral** [comment] 2019-06-01 18:07
@HelioGuilherme66 PR #1597 changes have been merged a long time, so this ticket can be closed.

**Comment by HelioGuilherme66** [comment] 2019-06-01 20:29
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)

**Closed by HelioGuilherme66** 2019-06-01 20:29 UTC
Labels: invalid
