### ISSUE TITLE
[RIDE RObot Framework] SSLError: bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)

### ISSUE THREAD

**Issue by rashtrapathy** [robotframework/RIDE#1637] opened 2016-06-08 05:33 UTC
Getting below error while executing the test case in RIDE robot framework

20160608 11:00:20.634 :  FAIL : SSLError: bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)

**\* Settings ***
Library           C:\Python27\Lib\site-packages\RequestsLibrary\RequestsKeywords.py

**\* Test Cases ***
TESTSTEP2
    Create Session    HANDLE    https://${IP}:4343/swarm.cgi    verify=False
    &{params}    Create Dictionary    hostname=RIDE_TEST
    ${resp}    Post Request    HANDLE    action=${params}
    Should Be Equal As Strings    ${resp.status_code}    200

**Comment by HelioGuilherme66** [comment] 2016-07-14 23:33
This error is not related with RIDE but with Robot Framework keywords/libraries.
@rashtrapathy please close this issue. Thanks.

**Comment by HelioGuilherme66** [comment] 2019-05-09 22:48
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Closed by HelioGuilherme66** 2019-05-09 22:48 UTC
