### ISSUE TITLE
RIDE console cannot display any result when Chinese need to be displayed.

### ISSUE THREAD

**Issue by hidebear** [robotframework/RIDE#1646] opened 2016-08-16 02:22 UTC
I am using Chinese inside the test case documentation and some keywords which may be displayed on console result like "Should Be Equal" when it's failed, I found RIDE console cannot display the test case result as below:
![image](https://cloud.githubusercontent.com/assets/21049399/17685751/90100160-6399-11e6-93c9-c18f8228e680.png)

however I used the same arguments of pybot from above to execute with command line, it is fine:

![image](https://cloud.githubusercontent.com/assets/21049399/17685795/ebb1a10e-6399-11e6-9a29-871d75b9ba32.png)

**Environment:**
(1) Win 10
(2) RIDE 1.5.2.1 running on Python 2.7.12. 
(3) Robot Framework 3.0 (Python 2.7.12 on win32)

**Test Case content:**
[test.txt](https://github.com/robotframework/RIDE/files/419362/test.txt)

**Comment by HelioGuilherme66** [comment] 2016-08-17 09:20
On my windows 7 machine with Python 2.7.11 (64bit) the output is acceptable (chars replaced by ?):

![chinese_test_win7](https://cloud.githubusercontent.com/assets/2866630/17731153/ffa353fe-6463-11e6-9d1a-c3b51495319e.png)

**Comment by simplezhang1990** [comment] 2017-03-03 01:48
hi @hidebear , does this issue fixed?

**Comment by hidebear** [comment] 2017-03-06 05:57
Hi @simplezhang1990 , still not.
Even I tried Win7 + Python 2.7.11 (64 bit), still cannot display it on RIDE console.

**Comment by Nyral** [comment] 2019-06-01 17:28
@hidebear Try adding `PYTHONIOENCODING=UTF-8` to your environmental variables.

![58673508-4505a480-8354-11e9-864a-a5cd4ae81412](https://user-images.githubusercontent.com/39315668/58751762-c91e7000-84ab-11e9-9482-3deaa655aa11.png)

**Comment by HelioGuilherme66** [comment] 2019-12-01 18:26
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 18:26 UTC
Labels: pending
