### ISSUE TITLE
Ride could not be runned with UnicodeDecodeError("utf8")

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1334] opened 2015-06-03 07:53 UTC
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1296) by kimhongs... on 17 Oct 2013_

It is impossible to run RIDE with below Error log
(it is produced everytime)

++++++++++++++++++++++++++++++++log&lt;Start&gt;++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplug
in.py", line 390, in OnTimer
    out_buffer, err_buffer = self._test_runner.get_output_and_errors()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py"
, line 240, in get_output_and_errors
    return self._process.get_output(), self._process.get_errors()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py"
, line 293, in get_errors
    return self._error_stream.pop()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py"
, line 380, in pop
    return result.decode('UTF-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 11: invalid
start byte
++++++++++++++++++++++++++++++++log&lt;end&gt;++++++++++++++++++++++++++++++++++

+++++++++++++++++++&lt;S/W version&gt;+++++++++++++++++++
Python 2.7.5
RIDE 1.2.1  
+++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by robotframework-ride** [comment] 2015-06-03 07:53
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1296#c1) by @mkorpela on 21 Oct 2013*


thanks for the report.

**Comment by robotframework-ride** [comment] 2015-06-03 07:53
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1296#c2) by @mkorpela on 25 Oct 2013*


I can't reproduce the problem with the given stack trace.

What operating system are you using?
What is the default encoding in that operating system?
Can you give a short example case where this problem occurs?

**Comment by robotframework-ride** [comment] 2015-06-03 07:53
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1296#c3) by kimhongs... on 26 Oct 2013*


My OS is WinXP.
Where can I check my default encoding in OS???

**Comment by robotframework-ride** [comment] 2015-06-03 07:53
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1296#c4) by @mkorpela on 28 Oct 2013*


From Control Panel open Regional and Language Options and check the Regional Options (language that is chosen).

**Comment by robotframework-ride** [comment] 2015-06-03 07:53
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1296#c5) by kimhongs... on 28 Oct 2013*


Language is Korean

**Comment by robotframework-ride** [comment] 2015-06-03 07:53
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1296#c6) by yihui.wang.yh on 11 Apr 2014*


Hi, the same error happens to me:
I am using RIDE 1.3 on win7 32-bit platform. 
robotframework 2.7.6
python 2.7.3
wxPython 2.8.12.1 (unicode) for python 2.7

**Comment by robotframework-ride** [comment] 2015-06-03 07:53
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1296#c7) by ben.gott... on 29 Jan 2015*


I ran into this as well. The error appears in the console from which RIDE was started (not within the RIDE interface).

To reproduce it:
- open the attached test suite utf8.tsv
- in the Run tab:
  - choose the execution profile 'custom script'
  - in the 'Script to run tests' field, specify the attached script custom-script.bat
  - make sure the 'Arguments' field is empty
- run the test

The attached test suite ascii.tsv does not trigger the error, despite being nearly identical to utf8.tsv.  The difference is that utf8.tsv contains a non-ASCII character in a test name, while ascii.tsv consists entirely of ASCII characters.

My setup:
Windows 7, 64-bit
python 2.7.3, 64-bit
wxPython2.8-win64-unicode-2.8.12.1-py27.exe
RIDE 1.3

**Comment by StephanMath** [comment] 2015-08-27 11:53
Hi
Same problem with these versions installed on Windows 7 x64 French

    python-2.7.10
    wxPython2.8-win32-unicode-2.8.12.1-py27
    robotframework-2.9.py32bit
    robotframework-ride-1.4.1.win-amd64
    robotframework-selenium2library-1.7.3.win32
    selenium-2.47.1

Any issue at this time ?

**Comment by tristanriu** [comment] 2017-03-23 12:42
Hi guys,
I still encounter this issue with similar environment. Can anybody share the latest status on this problem ?


Cheers, Tristan

**Comment by ccrampet** [comment] 2018-03-12 08:11
Hello,

I encounter the same issue with:
Windows 10 (French language)
Python 2.7.14
RIDE 1.5.2.1
wxPython2.8-win32-unicode-2.8.12.1-py27.exe

**When executing following test through ride:**
-------------------
*** Test Cases ***
hello
    Log    HELLO
--------------------

**following error occurs in console:**
---------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 367, in OnTimer
    self.OnProcessEnded(None)
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 334, in OnProcessEnded
    self.get_current_profile())
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 251, in get_output_and_errors
    self._process.get_errors(), self._process.get_returncode()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 308, in get_errors
    return self._error_stream.pop()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 400, in pop
    return result.decode('UTF-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 84: invalid start byte
---------------------------------------------------------------------------------------------------

Can anybody help me solving this issue?

Thanks,

Christelle

**Comment by HelioGuilherme66** [comment] 2018-03-12 13:56
@ccrampet The root cause for that error is the Include or Exclude tags having utf-8 characters. To solve this edit your settings file (or remove it, if you are willing to go to default settings).
On Windows the file is at:
`C:\Users\<your username>\AppData\Roaming\RobotFramework\ride\settings.cfg` 

Locate `[[Test Runner]]` and edit the settings, `robot_include_tags` and `robot_exclude_tags`, removing the offending characters.

I am not sure if this would be solved by trying to install my development branch of RIDE with:
```
pip install -U https://github.com/HelioGuilherme66/RIDE/archive/neweditor.zip
```
(If you do this, please see the Wiki on my fork and report Issues there. Thanks)

**Comment by ccrampet** [comment] 2018-03-12 15:13
@HelioGuilherme66, thanks for your answer but I don't use tag in my basic test.
Forthermore, I cannot fin offending characters in "C:\Users\<your username>\AppData\Roaming\RobotFramework\ride\settings.cfg" file:
I have removed the file and file is generated with following "[[Test Runner]]" section:
+++++++++++++++++++++++
[[Test Runner]]
show_message_log = True
profile = 'pybot'
sash_position = 200
runprofiles = [('jybot', 'jybot.bat')]
auto_save = False
_enabled = True
+++++++++++++++++++++++
And error stil occurs...

I have installed your development branch of RIDE and following error occurs now:
+++++++++++++++++++++++++++++
 File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 268, in OnRun
    command = self._create_command()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 291, in _create_command
    self.get_current_profile(),
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 633, in get_current_profile
    return self._test_runner.get_profile(self.choice.GetStringSelection())
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 102, in get_profile
    return self.profiles[name]
KeyError: u''
+++++++++++++++++++++++++++++

**Comment by HelioGuilherme66** [comment] 2018-03-12 15:25
1 - Remove again the settings.cfg and start RIDE.
2 - If that did not do, edit settings.cfg and change
[[Test Runner]]
show_message_log = True
profile = '*robot*'
3 - If still not running, then start RIDE using some filename has argument, like:
ride.py xyz.robot
(if it worked, then go change some settings)

**Comment by ccrampet** [comment] 2018-03-12 15:33
It works now, thanks a lot!

**Comment by Brian-Pai** [comment] 2018-04-02 08:59
Hello @HelioGuilherme66 
I also have this issue and follow your STEP 1, 2, 3. It still have the problem as below,
the same issue with: 
Windows 10, 64-bit
python 2.7.3, 64-bit
wxPython-4.0.0b2
Robot Framework 3.0.3rc1 (Python 2.7.14 on win32)
RIDE 2.0a1

When executing following test through ride:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 366, in OnTimer
    self.OnProcessEnded(None)
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 333, in OnProcessEnded
    self.get_current_profile())
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 251, in get_output_and_errors
    stdout, stderr, returncode = self._process.get_output(), \
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 308, in get_errors
    def get_errors(self):
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 400, in pop
    pass
  File "C:\Python27\lib\encodings\utf_8.py", line 17, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa4 in position 12: invalid start byte

Could you please help me solving this issue?

Thanks,

Brian Pai

**Comment by HelioGuilherme66** [comment] 2018-04-02 10:14
@Brian-Pai You are not using the development branch of RIDE:
```
pip install -U https://github.com/HelioGuilherme66/RIDE/archive/neweditor.zip
```
And there is a newer wxPython.
```
pip install -U wxPython
```
After doing those installations, you should see if you have any tags in inclusion/exclusion options, that contains unicode chars. Again try to reset the settings of RIDE before starting.

Better join our Slack channels for requesting more help.

**Comment by Brian-Pai** [comment] 2018-04-03 01:30
@HelioGuilherme66  
I follow your step, 

 reinstall ride
> 1. pip install -U https://github.com/HelioGuilherme66/RIDE/archive/neweditor.zip
> Successfully installed robotframework-ride-1.7.2.dev0

reinstall wxPython
> 2. pip install -U wxPython
> Successfully installed wxPython-4.0.1

Then I execute "ride.py", have the error message as below:
> C:\Python27\Scripts>python ride.py
> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\robotide\application\application.py", line 56, in OnInit
>     coreplugins.get_core_plugins())
>   File "C:\Python27\lib\site-packages\robotide\context\coreplugins.py", line 22, in get_core_plugins
>     from robotide.editor.texteditor import TextEditorPlugin
>   File "C:\Python27\lib\site-packages\robotide\editor\texteditor.py", line 41, in <module>
>     from . import robotframeworklexer
>   File "C:\Python27\lib\site-packages\robotide\editor\robotframeworklexer.py", line 17, in <module>
>     from pygments.lexer import Lexer
> ImportError: No module named pygments.lexer
> OnInit returned false, exiting...

Why I used this RIDE version, will have this issue? Could you please help me solving this issue?

Thanks,
Brian Pai

**Comment by Brian-Pai** [comment] 2018-04-03 08:19
Hi @HelioGuilherme66 
I have another problem.
I change another computer OS: win7 64 bit to try again and run command as below:

1.  install Python36-32
2. Install pip
    $python -m pip install -U pip
3. Install Robot Framework.
    $ python -m pip install robotframework
4. Install selenium2library
    $ python -m pip install robotframework-selenium2library
5. Install wxPython
   $ pip install -U wxPython
6. Install ride
   $pip install -U https://github.com/HelioGuilherme66/RIDE/archive/neweditor.zip

But I fail at "Install ride", the error message:

> Running setup.py install for robotframework-ride ... error
> Exception:
> Traceback (most recent call last):
>   File "c:\program files (x86)\python36-32\lib\site-packages\pip\compat\__init__
> .py", line 73, in console_to_str
>     return s.decode(sys.__stdout__.encoding)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 13: invalid
>  start byte
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\program files (x86)\python36-32\lib\site-packages\pip\basecommand.py"
> , line 215, in main
>     status = self.run(options, args)
>   File "c:\program files (x86)\python36-32\lib\site-packages\pip\commands\instal
> l.py", line 342, in run
>     prefix=options.prefix_path,
>   File "c:\program files (x86)\python36-32\lib\site-packages\pip\req\req_set.py"
> , line 784, in install
>     **kwargs
>   File "c:\program files (x86)\python36-32\lib\site-packages\pip\req\req_install
> .py", line 878, in install
>     spinner=spinner,
>   File "c:\program files (x86)\python36-32\lib\site-packages\pip\utils\__init__.
> py", line 676, in call_subprocess
>     line = console_to_str(proc.stdout.readline())
>   File "c:\program files (x86)\python36-32\lib\site-packages\pip\compat\__init__
> .py", line 75, in console_to_str
>     return s.decode('utf_8')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 13: invalid
>  start byte
>

Could you please help me solving this issue?

Thanks,
Brian Pai

**Comment by HelioGuilherme66** [comment] 2018-04-03 09:18
The second install problem is with `pip` see [This Issue](https://github.com/pypa/pip/issues/4110).
Try to downgrade `pip` (why you updated it?).

The first problem maybe is fixed with `pip install -U Pygments`.

**Comment by Brian-Pai** [comment] 2018-04-09 01:44
Hi @HelioGuilherme66 ,
Sorry late to reply.

Both problems fixed.
It working now, thanks a lot!

**Comment by Nyral** [comment] 2019-05-22 20:07
@HelioGuilherme66 Fixed?

**Comment by HelioGuilherme66** [comment] 2019-05-23 22:30
@Nyral This is the first issue reported since 2013, regarding chinese (or even latin) characters not being properly encoded in UTF-8. Current version of RIDE had already fixed some related issues, but it is not completely fixed. It will remain Open, since it serves as reference.

**Comment by HelioGuilherme66** [comment] 2023-04-09 11:22
Issue fixed:
Screen capture of RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors):
![image](https://user-images.githubusercontent.com/2866630/230769389-47508133-67c0-4c8b-bdef-2e9d38cbf4bb.png)

Test file
```robot
*** Test Cases ***
Test Case 1
    [Documentation]    測試案例1
    [Tags]    測試案例1    tesrf    LAND    gggg    hjghhh    hhhh    mkkkk    jjjjj    njh    ªas    €uro    # testing tags
    No Operation

Gonna test debug 4
    [Tags]    D    LORD
    Sleep    5 seconds
    Comment    PAUSE
    FOR    ${a}    IN RANGE    1    100
        Log    ${a}
    END
    Comment    #Pause from this line to debug changed to a very big line so we can see the wordwrap
    Comment    test

Test Case 2
    [Documentation]    Test Case 2
    [Tags]    non_critical    Áçãoµ    L
    Should Not Be Equal    中文    英文
    FOR    ${index}    IN    1    2
        Log    ${index}
    END

測試案例 3
    [Tags]    china    LANDLORD
    No Operation
    Log To Console    This is Chinese 測試案例 and isto é Português
    Log Variables
    Log To Console    Do fail the test by using arguments here
    Log Many    ${CURDIR}    ${EXECDIR}
    Set Suite Documentation    test

Test Corean Comment :)
    [Tags]    L
    Log    Hi
    Log    하이 > OK
    Log    Hi
    Comment    Pause here    teste
    Comment    하이 > UnicodeEncodeError
    Log    Last one
    FOR    ${a}    IN RANGE    1    2
        Comment    Teste is Really supposed to save position
        No Operation
        Log    ${a}
    END
    FOR    ${a}    IN RANGE    1    2
        Comment    Teste is Really supposed to save position more content
        No Operation
        Log    ${a}
    END
```

**Closed by HelioGuilherme66** 2023-04-09 11:22 UTC
Labels: prio-medium, bug, fixed
