### ISSUE TITLE
Postinstall script failed

### ISSUE THREAD

**Issue by mdlampi** [robotframework/RIDE#1506] opened 2015-08-24 17:12 UTC
On Windows 7 the robotframework-ride-1.5a1 installation results in a Setup error message:

Postinstall script finished
Click the Finish button to exit the Setup wizard.

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 38, in <module>
    import FixTk
  File "C:\Python27\lib\lib-tk\FixTk.py", line 65, in <module>
    import _tkinter
ImportError: DLL load failed: %1 is not a valid Win32 application.

Note the above error appears prior to clicking on the Finish button.

**Comment by yanne** [comment] 2015-08-28 04:26
This seems really strange, I think that's a problem with the installer dialog. Did the installation succeed?

**Comment by mdlampi** [comment] 2015-08-28 16:52
It appears to have successfully installed.

**Comment by yanne** [comment] 2015-09-02 17:30
I'll close this for, because I have no idea what's causing the problem, and no idea how to even reproduce it.

**Closed by yanne** 2015-09-02 17:30 UTC
