### ISSUE TITLE
RIDE crash when add a library

### ISSUE THREAD

**Issue by siul72** [robotframework/RIDE#1652] opened 2016-09-12 14:04 UTC
When import a library and click ok core dump occurs: 

(python:11367): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.32.4/./gobject/gsignal.c:2576: instance `0xa769210' has no handler with id`11529'
Segmentation fault (core dumped)

RIDE 1.5.2.1 running on Python 2.7.3. 

lcoelho@ubuntu-VirtualBox:~/Downloads/wxPython-src-3.0.2.0$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise

uname -a
Linux ubuntu-VirtualBox 3.2.0-24-generic-pae #39-Ubuntu SMP Mon May 21 18:54:21 UTC 2012 i686 i686 i386 GNU/Linux

 lcoelho@ubuntu-VirtualBox:~/Downloads/RIDE-master$ pip freeze
Warning: cannot find svn location for distribute==0.6.24dev-r0
Brlapi==0.5.6
GnuPGInterface==0.3.2
Mako==0.5.0
MarkupSafe==0.15
PAM==0.4.2
PIL==1.1.7
Pygments==2.1.3
Twisted-Core==11.1.0
Twisted-Names==11.1.0
Twisted-Web==11.1.0
adium-theme-ubuntu==0.3.2
apt-xapian-index==0.44
apturl==0.5.1ubuntu3
argparse==1.2.1
chardet==2.0.1
command-not-found==0.2.44
configglue==1.0
configobj==4.7.2
d-feet==0.1.14
dbus-python==1.2.4
debtagshw==0.1
decorator==3.3.2
defer==1.0.2
dirspec==3.0.0
## FIXME: could not find svn URL in dependency_links for this package:

distribute==0.6.24dev-r0
docutils==0.12
dulwich==0.8.5
duplicity==0.6.18
fastimport==0.9.0
httplib2==0.7.2
ipython==0.12.1
jockey==0.9.7
keyring==0.9.2
language-selector==0.1
launchpadlib==1.9.12
lazr.restfulclient==0.12.0
lazr.uri==1.0.3
louis==2.3.0
mysql-connector-python==0.3.2-devel
nvidia-common==0.0.0
oauth==1.0.1
onboard==0.97.1
oneconf==0.2.8.1
paramiko==1.7.7.1
pexpect==2.3
piston-mini-client==0.7.2
protobuf==2.4.1
pyOpenSSL==0.12
pycrypto==2.4.1
pycups==1.9.61
pycurl==7.19.0
pyinotify==0.9.2
pyserial==2.5
pysmbc==1.0.13
pysqlite==2.6.3
python-apt==0.8.3ubuntu7.3
python-dateutil==1.5
python-debian==0.1.21ubuntu1
python-virtkey==0.60.0
pyxdg==0.19
rabbitvcs==0.16.0
reportlab==2.5
rhythmbox-ubuntuone==4.2.0
robotframework==3.0
robotframework-ride==1.5.2.1
robotframework-selenium2library==1.7.4
scapy==2.3.1
selenium==2.53.2
sessioninstaller==0.0.0
simplegeneric==0.7
simplejson==2.3.2
software-center-aptd-plugins==0.0.0
system-service==0.1.6
ubuntuone-couch==0.3.0
ubuntuone-installer==3.0.2
ubuntuone-storage-protocol==3.0.2
ufw==0.31.1-1
unattended-upgrades==0.1
unity-lens-video==0.3.5
unity-scope-video-remote==0.3.5
usb-creator==0.2.23
wadllib==1.3.0
wsgiref==0.1.2
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xdiagnose==2.5.3
xkit==0.0.0
zope.interface==3.6.1

Thanks in advance

**Comment by Nyral** [comment] 2019-06-01 17:31
@siul72 Does this still happen with latest release?

**Comment by HelioGuilherme66** [comment] 2019-12-01 18:26
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 18:26 UTC
Labels: pending
