### ISSUE TITLE
Doesn't work hotkey 'ctrl+up' (Move Up test)

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1327] opened 2015-06-03 07:50 UTC
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1289) by rkhozi... on 8 Oct 2013*

Environment:
 - Python 2.7.4
 - RIDE 1.2.1

Doesn't move a test in the test list when I type the hotkey 'Ctrl+Up' or 'Ctrl+Down'. But this work when I use mouse 'right-click menu' and select 'Move UP' or 'Move Down'.

**Comment by robotframework-ride** [comment] 2015-06-03 07:50
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1289#c1) by @mkorpela on 25 Oct 2013*


Thanks for the report!
This is problem doesn't occur in Windows (only in linux) --&gt; Priority Low.

**Comment by robotframework-ride** [comment] 2015-06-03 07:50
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1289#c2) by @yanne on 28 May 2015*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1337" title="Ctrl + Up don't work on Ubuntu"> Issue 1337 </a> has been merged into this issue.

**Comment by yanne** [comment] 2015-06-07 09:09
This is a duplicate of #1377

**Closed by yanne** 2015-06-07 09:09 UTC
Labels: bug, prio-low
