### ISSUE TITLE
robotframework ryde issu on ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by remicharleslageixarena** [robotframework/RIDE#1961] opened 2019-06-28 08:48 UTC
can someone help me?
****
on ubuntu 18.04.2 LTS, I installed robotframework and ride.
the installation was with no error.
but when I launch ryde.py, 
the RIDE 's GUI is not open and the ERROR MESSAGE below is displaying on the screen.

the configuration is:
*****************************
*** ubuntu 18.04.2 LTS.**
*****************************
***python --version**
          Python 2.7.15+
*****************************
***robot --version**
          Robot Framework 3.1.2 (Python 2.7.15+ on linux2)
*****************************
*pip list
          ...
          robotframework                  3.1.2       
          robotframework-ride             1.7.4b1.dev1
          robotframework-selenium2library 3.0.0       
          robotframework-seleniumlibrary  3.3.1       
          ...
*****************************
**sudo aptitude search python-wxgtk2.8**
          ...
          i   python-wxgtk2.8                              - wxWidgets Cross-platform C++ GUI toolkit (wxPython bin
         ...
*****************************
**sudo aptitude search python-wxversion**
          i A python-wxversion  
*****************************

**this is the ERROR  MESSAGE when I launch ride.py**
$ ride.py
message
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/robotide/__init__.py", line 83, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/local/lib/python2.7/dist-packages/robotide/__init__.py", line 112, in _run
    ride = RIDE(inpath, updatecheck)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/application.py", line 45, in __init__
    wx.App.__init__(self, redirect=False)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/application.py", line 55, in OnInit
    self.frame = RideFrame(self, self._controller)
  File "/usr/local/lib/python2.7/dist-packages/robotide/ui/mainframe.py", line 173, in __init__
    self.Bind(wx.EVT_DIRCTRL_FILEACTIVATED, self.OnOpenFile)
AttributeError: 'module' object has no attribute 'EVT_DIRCTRL_FILEACTIVATED'

Use --help to get usage information.

**Comment by HelioGuilherme66** [comment] 2019-06-28 09:01
Please uninstall wxPython 2.8 (and wxversion because is not needed), and install newer wxPython. Go to wxpython.org and locate the Linux packages for wxPython 4.0.6.

**Comment by remicharleslageixarena** [comment] 2019-06-28 10:07
Thank you very much.
your solution is OK.

I launch the following commands:

**sudo pip install pathlib2** (this is necessary, otherwise _"the Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error"_

### sudo -H pip install wxPython==4.0.6

**Comment by HelioGuilherme66** [comment] 2019-06-28 14:52
@remicharleslageixarena Well, I was not expecting you to build the .whl, but to download existing one.

Closing since the problem is solved.

**Closed by HelioGuilherme66** 2019-06-28 14:52 UTC
