### ISSUE TITLE
Dictionary not found

### ISSUE THREAD

**Issue by sonitameas** [robotframework/RIDE#2010] opened 2019-09-16 10:20 UTC
Im dout why dictionary in my test suit is alway not found when I try to access it but I have declared it already. can any help me.

**Comment by HelioGuilherme66** [comment] 2019-09-16 12:43
@sonitameas You don't give enough info. Please show us an example of the declaration of the dictionary and then where you are using it. Also info about the RIDE version and OS should be mentioned.

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:51
Closing because we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:51 UTC
Labels: pending
