### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xca in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by warom1996** [robotframework/RIDE#1938] opened 2019-06-05 05:43 UTC
Traceback (most recent call last):
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 370, in OnTimer
    self._test_runner.get_output_and_errors(self.get_current_profile())
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 250, in get_output_and_errors
    stdout, stderr, returncode = self._process.get_output(), \
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 305, in get_output
    return self._output_stream.pop()
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 400, in pop
    return result.decode('UTF-8')
  File "D:\AutoTest\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 25: invalid start byte
Traceback (most recent call last):
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 370, in OnTimer
    self._test_runner.get_output_and_errors(self.get_current_profile())
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 250, in get_output_and_errors
    stdout, stderr, returncode = self._process.get_output(), \
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 305, in get_output
    return self._output_stream.pop()
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 400, in pop
    return result.decode('UTF-8')
  File "D:\AutoTest\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 0: invalid start byte
Traceback (most recent call last):
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 370, in OnTimer
    self._test_runner.get_output_and_errors(self.get_current_profile())
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 250, in get_output_and_errors
    stdout, stderr, returncode = self._process.get_output(), \
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 305, in get_output
    return self._output_stream.pop()
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 400, in pop
    return result.decode('UTF-8')
  File "D:\AutoTest\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcf in position 39: invalid continuation byte
Traceback (most recent call last):
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 370, in OnTimer
    self._test_runner.get_output_and_errors(self.get_current_profile())
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 250, in get_output_and_errors
    stdout, stderr, returncode = self._process.get_output(), \
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 305, in get_output
    return self._output_stream.pop()
  File "D:\AutoTest\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 400, in pop
    return result.decode('UTF-8')
  File "D:\AutoTest\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xca in position 0: invalid continuation byte

Can you help me with this difficulty? I have been looking for the anser for a long time,but there is no way?
Python 2.7.14
Windows 10

**Comment by karofsky** [comment] 2019-06-05 08:34
having the same problem here, this version did not support Chinese well
I downgrade to 1.5.2

**Comment by warom1996** [comment] 2019-06-05 08:45
> having the same problem here, this version did not support Chinese well
> I downgrade to 1

**Comment by HelioGuilherme66** [comment] 2019-06-05 09:08
@warom1996 and @karofsky Improvements have been made to allow running Chinese content test suites. But it is difficult for us to test and confirm that *everyone* would be satisfied with the solution. This is what we want to assure:
- Test suites can be edited fine with RIDE
- Running test suites will work, even if the path contains Chinese chars, or --include --exclude tags
- The results are from `robot` and they are *always* OK, even if the output window, or log does not show correct characters

Using python 2.7 is more problematic than with python 3.6+.  What can you do to help us:
- Install python 3.7, wxPython 4.0.6, robotframework and other needed libraries
- Install future RIDE Beta (1.7.4b1) with `pip install -U https://github.com/robotframework/RIDE/archive/master.zip`
- Test usage, and if not happy, change the env var PYTHONIOENCODING='UTF-8' 
- Attach a small test suite example for us to reproduce (if with folders, use a .zip archive)

**Comment by Nyral** [comment] 2019-06-05 17:10
@warom1996 On which RIDE version did you encounter the error?

**Comment by karofsky** [comment] 2019-06-06 03:25
> @warom1996 and @karofsky Improvements have been made to allow running Chinese content test suites. But it is difficult for us to test and confirm that _everyone_ would be satisfied with the solution. This is what we want to assure:
> 
> * Test suites can be edited fine with RIDE
> * Running test suites will work, even if the path contains Chinese chars, or --include --exclude tags
> * The results are from `robot` and they are _always_ OK, even if the output window, or log does not show correct characters
> 
> Using python 2.7 is more problematic than with python 3.6+. What can you do to help us:
> 
> * Install python 3.7, wxPython 4.0.6, robotframework and other needed libraries
> * Install future RIDE Beta (1.7.4b1) with `pip install -U https://github.com/robotframework/RIDE/archive/master.zip`
> * Test usage, and if not happy, change the env var PYTHONIOENCODING='UTF-8'
> * Attach a small test suite example for us to reproduce (if with folders, use a .zip archive)

Hi @HelioGuilherme66 , glad to help but i have some quesions
    1. You ask for small test suite to reproduce, however my suite use remote lib to call ruby function, so it's may not be easy to reproduce for you.
    2. 1.7.4b1 needs python3.7, does it still support python 2.7?

**Comment by HelioGuilherme66** [comment] 2019-06-06 10:54
@karofsky 1. We just need to see some examples of failing output (keyword names, test names, test file names, directories names, text output).
2. Current beta of 1.7.4 still supports 2.7 too.

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:43
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:43 UTC
Labels: pending
