### ISSUE TITLE
Crashed after clicking a keyword in edit tab(MacOS and RIDE 2.x)

### ISSUE THREAD

**Issue by AndrewLu3335** [robotframework/RIDE#2561] opened 2023-03-14 07:55 UTC
After clicking the keyword in edit tab(trying to jump to the selected keyword page) ,  RIDE crashed every time.
RIDE 2.x all have this problem. 

MacOS 11.3.1
python 3.8.5
RIDE 2.0

**Comment by HelioGuilherme66** [comment] 2023-03-14 19:48
@AndrewLu3335 I can't reproduce your problem. I tried in macOS Catalina, 10.15.7, wxPython 4.1.1 and Python 3.8.5. Latest release of RIDE, 2.0.

You need to attach a sample test suite, with minimal reproducible case.
Where is the keyword defined? In the same file, or in an external resource file?
Is is a keyword from a Library (RIDE can't jump on those, but should not crash).

**Comment by AndrewLu3335** [comment] 2023-03-15 02:14
I have tried every kinds of keywords either in external resource file or in the same file. Even double clicking the blank cells in edit tab can cause crash. My wxPython version is 4.1.1. 

Here is my crash log:
Process:               Python [40536]
Path:                  /Library/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.8.5 (3.8.5)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
User ID:               503

Date/Time:             2023-03-15 10:11:17.587 +0800
OS Version:            macOS 11.3.1 (20E241)
Report Version:        12
Anonymous UUID:        78695901-8FF0-6911-194E-5208664E607A

Sleep/Wake UUID:       45E5900C-E945-40B7-A561-B0D15DAC95E5

Time Awake Since Boot: 70000 seconds
Time Since Wake:       56000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [40536]

VM Regions Near 0:
--> 
    __TEXT                      106ee5000-106ee6000    [    4K] r-x/rwx SM=COW  /Library/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libwx_osx_cocoau_adv-3.0.0.4.0.dylib	0x000000010963845f wxGridCellEditor::Show(bool, wxGridCellAttr*) + 111
1   _grid.cpython-38-darwin.so    	0x0000000109791f95 sipwxGridCellEditor::Show(bool, wxGridCellAttr*) + 117
2   libwx_osx_cocoau_adv-3.0.0.4.0.dylib	0x000000010962057e wxGrid::ShowCellEditControl() + 1630
3   libwx_osx_cocoau_adv-3.0.0.4.0.dylib	0x000000010961fe93 wxGrid::EnableCellEditControl(bool) + 291
4   libwx_osx_cocoau_adv-3.0.0.4.0.dylib	0x000000010961fcb8 wxGrid::DoGridCellLeftUp(wxMouseEvent&, wxGridCellCoords const&) + 552
5   libwx_osx_cocoau_adv-3.0.0.4.0.dylib	0x0000000109617f8a wxGrid::ProcessGridCellMouseEvent(wxMouseEvent&) + 762
6   libwx_baseu-3.0.0.4.0.dylib   	0x000000010866bc80 wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) + 464
7   libwx_baseu-3.0.0.4.0.dylib   	0x000000010866cf9d wxEvtHandler::ProcessEventLocally(wxEvent&) + 93
8   libwx_baseu-3.0.0.4.0.dylib   	0x000000010866ce24 wxEvtHandler::ProcessEvent(wxEvent&) + 100
9   libwx_baseu-3.0.0.4.0.dylib   	0x000000010866d29c wxEvtHandler::SafelyProcessEvent(wxEvent&) + 12
10  libwx_osx_cocoau_core-3.0.0.4.0.dylib	0x000000010804f31d wxWidgetCocoaImpl::DoHandleMouseEvent(NSEvent*) + 77
11  libwx_osx_cocoau_core-3.0.0.4.0.dylib	0x000000010804b517 wxWidgetCocoaImpl::mouseEvent(NSEvent*, NSView*, void*) + 167
12  com.apple.AppKit              	0x00007fff22e87035 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2719
13  com.apple.AppKit              	0x00007fff22e86376 -[NSWindow(NSEventRouting) sendEvent:] + 347
14  libwx_osx_cocoau_core-3.0.0.4.0.dylib	0x00000001080388cb -[wxNSWindow sendEvent:] + 123
15  com.apple.AppKit              	0x00007fff22e84784 -[NSApplication(NSEvent) sendEvent:] + 352
16  libwx_osx_cocoau_core-3.0.0.4.0.dylib	0x0000000107f82b42 -[wxNSApplication sendEvent:] + 98
17  com.apple.AppKit              	0x00007fff2315d979 -[NSApplication _handleEvent:] + 65
18  com.apple.AppKit              	0x00007fff22ced69e -[NSApplication run] + 623
19  libwx_osx_cocoau_core-3.0.0.4.0.dylib	0x000000010802ed6f wxGUIEventLoop::OSXDoRun() + 207
20  libwx_baseu-3.0.0.4.0.dylib   	0x0000000108646091 wxCFEventLoop::DoRun() + 49
21  libwx_baseu-3.0.0.4.0.dylib   	0x00000001085961a2 wxEventLoopBase::Run() + 162
22  libwx_baseu-3.0.0.4.0.dylib   	0x000000010855f093 wxAppConsoleBase::MainLoop() + 99
23  _core.cpython-38-darwin.so    	0x00000001075369b1 wxPyApp::MainLoop() + 81
24  _core.cpython-38-darwin.so    	0x00000001075393f3 meth_wxPyApp_MainLoop(_object*, _object*) + 147
25  org.python.python             	0x0000000106f12622 cfunction_call_varargs + 290
26  org.python.python             	0x0000000106f11fe5 _PyObject_MakeTpCall + 373
27  org.python.python             	0x0000000106fe0995 call_function + 533
28  org.python.python             	0x0000000106fdd79e _PyEval_EvalFrameDefault + 25678
29  org.python.python             	0x0000000106f12930 function_code_fastcall + 128
30  org.python.python             	0x0000000106fe093c call_function + 444
31  org.python.python             	0x0000000106fdd77a _PyEval_EvalFrameDefault + 25642
32  org.python.python             	0x0000000106fe1784 _PyEval_EvalCodeWithName + 2804
33  org.python.python             	0x0000000106f12ace _PyFunction_Vectorcall + 270
34  org.python.python             	0x0000000106fe093c call_function + 444
35  org.python.python             	0x0000000106fdd835 _PyEval_EvalFrameDefault + 25829
36  org.python.python             	0x0000000106fe1784 _PyEval_EvalCodeWithName + 2804
37  org.python.python             	0x0000000106f12ace _PyFunction_Vectorcall + 270
38  org.python.python             	0x0000000106f1230d PyVectorcall_Call + 109
39  org.python.python             	0x0000000106fddca8 _PyEval_EvalFrameDefault + 26968
40  org.python.python             	0x0000000106fe1784 _PyEval_EvalCodeWithName + 2804
41  org.python.python             	0x0000000106fd7274 PyEval_EvalCode + 100
42  org.python.python             	0x0000000106fd4662 builtin_exec + 626
43  org.python.python             	0x0000000106f4e90f cfunction_vectorcall_FASTCALL + 175
44  org.python.python             	0x0000000106fe093c call_function + 444
45  org.python.python             	0x0000000106fdd835 _PyEval_EvalFrameDefault + 25829
46  org.python.python             	0x0000000106fe1784 _PyEval_EvalCodeWithName + 2804
47  org.python.python             	0x0000000106f12ace _PyFunction_Vectorcall + 270
48  org.python.python             	0x0000000106fe093c call_function + 444
49  org.python.python             	0x0000000106fdd835 _PyEval_EvalFrameDefault + 25829
50  org.python.python             	0x0000000106fe1784 _PyEval_EvalCodeWithName + 2804
51  org.python.python             	0x0000000106f12ace _PyFunction_Vectorcall + 270
52  org.python.python             	0x0000000106f1230d PyVectorcall_Call + 109
53  org.python.python             	0x0000000107044106 pymain_run_module + 182
54  org.python.python             	0x00000001070437e5 Py_RunMain + 1413
55  org.python.python             	0x0000000107043e3f pymain_main + 223
56  org.python.python             	0x000000010704403b Py_BytesMain + 43
57  libdyld.dylib                 	0x00007fff20424f3d start + 1

**Comment by HelioGuilherme66** [comment] 2023-07-24 15:51
Closing because of not possible for me to do any action, or the issue is fixed in newer versions.

**Closed by HelioGuilherme66** 2023-07-24 15:51 UTC
Labels: pending, os: mac, Python3.8
