### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by aksheysar** [robotframework/RIDE#1784] opened 2018-11-29 16:29 UTC
C:\Users\Vinaykoudi>ride.py
Traceback (most recent call last):
  File "C:\Users\Vinaykoudi\AppData\Local\Programs\Python\Python37-32\Scripts\ride.py", line 20, in <module>
    from robotide import main
  File "c:\users\vinaykoudi\appdata\local\programs\python\python37-32\lib\site-packages\robotide\__init__.py", line 35, in <module>
    from robotide.utils import basestring, unicode
  File "c:\users\vinaykoudi\appdata\local\programs\python\python37-32\lib\site-packages\robotide\utils\__init__.py", line 28, in <module>
    from .eventhandler import RideEventHandler
  File "c:\users\vinaykoudi\appdata\local\programs\python\python37-32\lib\site-packages\robotide\utils\eventhandler.py", line 15, in <module>
    import wx
  File "c:\users\vinaykoudi\appdata\local\programs\python\python37-32\lib\site-packages\wx\__init__.py", line 17, in <module>
    from wx.core import *
  File "c:\users\vinaykoudi\appdata\local\programs\python\python37-32\lib\site-packages\wx\core.py", line 12, in <module>
    from ._core import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by aksheysar** [comment] 2018-11-29 16:30
Package             Version
------------------- -------
pip                 18.1
Pygments            2.3.0
Pypubsub            4.0.0
robotframework      3.0.4
robotframework-ride 1.7.1
setuptools          39.0.1
six                 1.11.0
wxPython            4.0.3

**Comment by aksheysar** [comment] 2018-11-29 16:32
System Information
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.15063 N/A Build 15063
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
System Manufacturer:       Dell Inc.
System Model:              Inspiron 3543
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 61 Stepping 4 GenuineIntel ~2000 Mhz

**Comment by aksheysar** [comment] 2018-11-29 16:33
Python 3.7.1 Version

**Comment by aksheysar** [comment] 2018-11-29 16:34
Can someone help me on this error as ride.py is not working on command prompt.
ImportError: DLL load failed: The specified module could not be found.

**Comment by HelioGuilherme66** [comment] 2018-11-29 16:52
RIDE 1.5.2.1 is not compatible with Python 3.  I am sure you did not search the Issue tracker, for example:
[this search](https://github.com/robotframework/RIDE/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Python+3)

There is an experimental version compatible with Python 3:
```
pip install -U https://github.com/HelioGuilherme66/RIDE/archive/release.zip
```

Please Close this Issue. Thanks.

**Comment by ravihuang** [comment] 2019-01-08 10:36
add api-ms-win-crt-utility-l1-1-0.dll and msvcp140.dll to system directory

**Comment by HelioGuilherme66** [comment] 2019-05-23 23:56
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Closed by HelioGuilherme66** 2019-05-23 23:56 UTC
