### ISSUE TITLE
I am not able to open ride.py

### ISSUE THREAD

**Issue by Ishrat1401** [robotframework/RIDE#1855] opened 2019-03-23 08:49 UTC
![image](https://user-images.githubusercontent.com/24873115/54864012-4f188f00-4d76-11e9-865c-6b82c36a4802.png)
I have python version 3.7.2
C:\Users\Ishrat>pip freeze
Pillow==5.4.1
Pygments==2.3.1
PyPubSub==3.3.0
pywin32==224
robotframework==3.1.1
robotframework-ride==1.7.3.1
robotframeworklexer==1.1
selenium==3.141.0
six==1.12.0
urllib3==1.24.1
wxPython==4.0.4

**Comment by yjagdale** [comment] 2019-03-27 12:19
This is on windows 10?

**Comment by Ishrat1401** [comment] 2019-03-27 12:23
yes on windows 10

**Comment by zerazeon** [comment] 2019-03-27 16:33
Have you set default app for .py?

**Comment by HelioGuilherme66** [comment] 2019-05-16 23:06
@Ishrat1401 Is your problem solved by now? If so, please close this issue. Thanks.

**Comment by Nyral** [comment] 2019-06-01 16:54
@Ishrat1401 That's because you're trying to open ride.py instead of executing it.
The error appears because you don't have a text editor associated with that file type.
Correct command is: `python ride.py`

**Comment by HelioGuilherme66** [comment] 2019-06-01 20:33
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)

**Closed by HelioGuilherme66** 2019-06-01 20:33 UTC
Labels: invalid
