### ISSUE TITLE
Ride on Centos 6 issues

### ISSUE THREAD

**Issue by ChthonicOne** [robotframework/RIDE#1693] opened 2017-04-28 22:27 UTC
At my workplace we work on government programs, and the government has not moved past Centos 6 yet. As a result I'm having numerous issues installing an using RobotFramework-Ride on these systems.

I have gotten it to work in one configuration:
Python 2.6.6 (Had to edit some of the source files for RIDE to accommodate this)
wxPython 2.8.12.0 (Only version I can get installed on Centos 6, runs with warnings)

My problem with this setup is that I had to edit the source files for RIDE to include a number inside brackets that are found in strings. This is not something I can automate and deploy on dozens of systems for our testers. As such I have worked towards an altinstall of Python 2.7. However once I accomplished this and got everything I needed installed properly for RIDE, when I run it, I get a segmentation fault, immediately.

`cesi@onesaf-v86-gold:~/Downloads/setuptools-1.4.2$ ride.py
Creating librarykeywords database to "/home/cesi/.robotframework/ride/librarykeywords.db"
Segmentation fault (core dumped)`

I understand you only support wxPython version 2.8.12.1, but no matter what I do, I cannot get it to install. wxWidgets install all fine. It seems to be a bunch of CPP compiling errors like "expected < before foo" or "expected ( before bar". There's too many for me to count.

I appreciate all the help I can get here.

**Comment by HelioGuilherme66** [comment] 2017-04-29 19:51
@ChthonicOne I know your pain. Me too have RedHat based systems (Fedora 22 and CentOS 7), and cannot get wxPython 2.8.12.1. Once I managed to compile and install, but lost the config, so now can't even validate my changes. This project is somehow "abandoned". I have been trying to port to new wxPython and will do porting to Python 3. I have released RIDE with my changes [on my fork releases page](https://github.com/HelioGuilherme66/RIDE/releases), but I do not consider them stable enough for production (although I use it at work with wxPython 3.0.2).
Now we have wxPython 4 (alpha), which works with Python 3, and later Python 2.7 will end support, so the investment (my time) is focused on those versions.
To solve your concrete problems, you can install wxPython 3.0.2 (there is official RPM) and use a modified version of RIDE (like from my fork).
(maybe your could join me and others on the #ride channel at Slack get the registration [here](http://robotframework.org/#support), look for Slack)

**Comment by ChthonicOne** [comment] 2017-05-04 19:45
Thank you for your response! I managed to install wxPython 3.0.2 somehow. It was a struggle as there were some libraries that were not named the same in yum as in apt-get and I had thought they were installed, and some path issues for some libraries as well, they were installed, but apparently setup.py wanted to look elsewhere for them rather than look in /usr/lib64/

I'm pretty new to this version of Linux, or really Linux in general so bear with me.

Even with the new version of wxPython, the mainline RIDE chooses to segfault. Clearly that is not the problem with it. Yours however runs. Here is the problem though: It may be that we cannot use your version as it's not mainline and not a release. I have to ask my boss and see. Unless I get a go ahead from him or his boss, I cannot consider this problem solved yet. Working through government regulations and all is aggravating to say the least.

If I cannot use yours for the reason that it is not a mainline build, this can be fixed maybe by you completely splitting from Robot-IDE and making it a new project IDE. Just a thought, and might be important if you ever want to roll your changes into the mainline, but they aren't around.

**Comment by ChthonicOne** [comment] 2017-05-10 19:39
I'm leaving this issue open for tracking as it's valid for the main branch of RIDE. HelioGuilherme66's branch corrects this and other problems and should be merged into the main branch as soon as other bugs are resolved.

**Comment by HelioGuilherme66** [comment] 2019-05-09 00:16
@ChthonicOne I am closing this now, please open a new one if there are any severe bugs (apart the known ones ;) )
Latest released version is 1.7.3.1, and 1.7.4 is being prepared.
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Closed by HelioGuilherme66** 2019-05-09 00:16 UTC
