### ISSUE TITLE
Cyrillic symbols from documentation are not displayed

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#2052] opened 2019-11-15 11:24 UTC
Whenever there's a Russian/Ukrainian text in documentation it's not displayed properly:
https://imgur.com/a/gZWaUOB

**Comment by HelioGuilherme66** [comment] 2019-11-15 11:34
That is not documentation, but command window output.
You need to give info on what versions of RIDE, system and python.
There are several issues related to characters (like Chinese).

**Comment by povar81** [comment] 2019-11-15 12:30
Windows 7.
Python 3.7.4,
robotframework==3.1.2,
robotframework-ride==1.7.4b1.dev1 (I'm usring dev1 version because it's the last one supporting the old for loop syntax)

**Comment by povar81** [comment] 2019-11-15 12:52
wxPython==4.0.6

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:55
Closing because we cannot reproduce in current development version.

**Closed by HelioGuilherme66** 2019-12-01 19:55 UTC
Labels: fixed

**Comment by povar81** [comment] 2024-03-11 10:06
Cyrillic text is shown properly
in RIDE v2.0.8.1 running on Python 3.7.4.
thank you
