### ISSUE TITLE
chinese keywords can't run success

### ISSUE THREAD

**Issue by floatice** [robotframework/RIDE#1860] opened 2019-03-29 07:51 UTC
![image](https://user-images.githubusercontent.com/18067441/55217362-50e0c780-523a-11e9-9e3d-fa197d7d09dd.png)

**Comment by floatice** [comment] 2019-03-29 07:53
windows 7 and windows 10 has the issue all

**Comment by floatice** [comment] 2019-03-29 07:54
1.7.3.1 version

**Comment by HelioGuilherme66** [comment] 2019-03-29 10:21
This happens only in Windows and with Python 2.7.

You can help me testing if it is fixed by installing current development version from my fork.
Please try:
```
pip install -U https://github.com/HelioGuilherme66/RIDE/archive/pre_release_win.zip
```

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:29
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:29 UTC
Labels: pending
