### ISSUE TITLE
Double click: Edit mode fails if user clicks mouse button too quickly

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1349] opened 2015-06-03 08:49 UTC
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1309) by aki.sivula on 2 Dec 2013_

Ride's grid has feature that allows edit cell contents after double click.

By some reason this feature doesn't work reliably and quite often F2 is only way to edit cell quickly. 
1. Click cell quickly 2 - 3 times in row.
   -&gt; Cell is yellow. User cannot edit it and double click again doesn't change cell to edit mode.

After that cell editing is possible only with F2 or user must click another cell and then double click again to the wanted cell. 

Ride version 1.2.2

**Comment by robotframework-ride** [comment] 2015-06-03 08:49
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1309#c1) by @mkorpela on 3 Dec 2013*


What operating system you are using?

**Comment by robotframework-ride** [comment] 2015-06-03 08:49
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1309#c2) by aki.sivula on 3 Dec 2013*


Windows 7 64bit SP1

**Comment by robotframework-ride** [comment] 2015-06-03 08:49
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1309#c3) by @mkorpela on 11 Dec 2013*


I can not reproduce the problem with my 64 bit Windows 7.

@&#8288;aki.sivula: Could you post what is written to your RIDE log (Tools / View RIDE Log)?

**Comment by robotframework-ride** [comment] 2015-06-03 08:49
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1309#c4) by aki.sivula on 12 Dec 2013*


Unfortunately it is not allowed to post RIDE log. Tested it a bit more and noticed that edit mode works always when moving to wanted cell but there is minor glitch that causes feeling that edit mode is not on. 

Glitch is that speed of double click changes behavior of the text painting. When double clicking slowly the text is painted but when quickly the text paint disappears. F2 paints text always.

1. Click to cell nearby
2. Double click quickly the cell you want to edit
--&gt; Text in the cell just flashes and "paint" disappears. This happens occasionally.

If user clicks F2 the cell text is always painted. So conclusion is that this is minor glitch.

**Comment by robotframework-ride** [comment] 2015-06-03 08:50
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1309#c5) by @mkorpela on 16 Dec 2013*


Ok.

Could you check what wx version you are currently using?

from command line start python:
python
&gt;&gt; import wx
&gt;&gt; print wx.__version__

**Comment by robotframework-ride** [comment] 2015-06-03 08:50
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1309#c6) by aki.sivula on 16 Dec 2013*


2.8.12.1

**Comment by HelioGuilherme66** [comment] 2019-12-01 17:56
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 17:56 UTC
Labels: bug, pending, prio-medium
