### ISSUE TITLE
Browser not launching in Ride, does not throw any error as well.

### ISSUE THREAD

**Issue by Ankita-29-UI** [robotframework/RIDE#2890] opened 2024-09-24 10:04 UTC
I am trying install Robot Framework with Ride and after installing, when i try to run the tests in the IDE, the browser is not launching.
I tried with multiple Browsers and none of it is being launched.

My installation details:
<img width="245" alt="robotframework_install" src="https://github.com/user-attachments/assets/6f0f7816-a125-4b6f-87ab-789df7696351">
I have installed python version : 3.9.2.

Can anyone help me resolve this issue.

Thanks in advance 
Ankita

**Comment by HelioGuilherme66** [comment] 2024-09-24 10:39
@Ankita-29-UI First, you  have conditions to install the new pre-release of RIDE, version 2.1b1.
Please try to upgrade your current version with:
`pip install -U --pre robotframework-ride`

About your problem:
RIDE only opens the browser, when you click the Report or Log buttons in the Run tab, **after a successful** test run.

Seems that your problem is not related with RIDE, but with some test case, probably using SeleniumLibrary.
This issue report is very low quality, because it does not give much information for me to investigate. You may see #2097 where I talk about good reporting of problems (although is a bit outdated).

**Comment by HelioGuilherme66** [comment] 2024-10-13 11:45
Closing because not something we can work on, and reproduce. New release v2.1 is out, user should test on it.

**Closed by HelioGuilherme66** 2024-10-13 11:45 UTC
Labels: pending, BAD_ISSUE_REPORT
