### ISSUE TITLE
Pressing on a test case should jump to the correct place on Text Edit tab

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1291] opened 2015-06-03 07:35 UTC
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1253) by MeitalBo... on 20 May 2013_

When pressing on different test cases on Text Edit tab, it will be very helpful if it'll "jumps" to the place of the current test case that we choose.

**Comment by HelioGuilherme66** [comment] 2023-09-23 14:12
This is working in Linux, but in Windows only jumps for the first time. When Grid Editor plugin is disabled, seems to work fine.
RIDE v2.0.8.dev14

**Comment by HelioGuilherme66** [comment] 2023-09-23 19:59
Duplicate of #986

**Comment by HelioGuilherme66** [comment] 2023-10-18 20:14
Fixed in 2023!!!!
Ten years after creation!
v2.0.8dev24

**Closed by HelioGuilherme66** 2023-10-18 20:14 UTC
Labels: enhancement, prio-medium, duplicate, fixed
