### ISSUE TITLE
PIP Installation on MacOS failed

### ISSUE THREAD

**Issue by TimurNurlygayanov** [robotframework/RIDE#1774] opened 2018-10-16 09:52 UTC
I've tried to install it with pip:

pip install robotframework-ride

and got the following error:

```
Collecting robotframework-ride
  Downloading https://files.pythonhosted.org/packages/3c/14/a5f97f5cf5e981f01e8c0b4c405b0dfc9bc86500cabb044d2c462f73004a/robotframework-ride-1.5.2.1.tar.gz (576kB)
    100% |████████████████████████████████| 583kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-i8rkc4ax/robotframework-ride/setup.py", line 20, in <module>
        execfile(join(ROOT_DIR, 'src', 'robotide', 'version.py'))
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-i8rkc4ax/robotframework-ride/
```

**Comment by TimurNurlygayanov** [comment] 2018-10-16 09:54
found the workaround:

python -m pip install robotframework-ride

**Comment by HelioGuilherme66** [comment] 2018-10-16 21:15
And you managed to install wxPython 2.8.12.1 in MacOS?
@TimurNurlygayanov Please close the issue if the problem is solved. Thanks.

**Comment by AshoneA** [comment] 2018-12-06 03:52
@HelioGuilherme66 I download file wxPython2.8-osx-unicode-2.8.12.1-universal-py2.7.dmg from http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/, but it can't finish installed, my macOS version is 10.14.1

**Comment by HelioGuilherme66** [comment] 2019-05-23 23:54
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Closed by HelioGuilherme66** 2019-05-23 23:54 UTC
