### ISSUE TITLE
RIDE-1.5.2.1 is working some as 1.7.3.1 if I install 1.7.3.1 and reinstall 1.5.2.1 version 

### ISSUE THREAD

**Issue by Carlzkh** [robotframework/RIDE#1911] opened 2019-05-15 10:01 UTC
It works the same way as 1.7.3.1
for example I can't show my selection in the grid, although the selection works

**Comment by HelioGuilherme66** [comment] 2019-05-15 19:33
Was the selection it working before?
Is that Windows 10, with wxPython 2.8.12.1?

**Comment by Carlzkh** [comment] 2019-05-16 01:09
> Was the selection it working before?
> Is that Windows 10, with wxPython 2.8.12.1?

yes，the selection it working before
it's windows10 with wxPython 2.8.12.1,and robotframework is 3.0.2

**Comment by HelioGuilherme66** [comment] 2019-06-04 22:50
@Carlzkh In your screenshot the last command is using python3 to install ExcelLibrary. Looks like it is not compatible because is calling execfile().

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:57
Closing because we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:57 UTC
Labels: pending
