### ISSUE TITLE
ride.py return error when directory has Chinese

### ISSUE THREAD

**Issue by simplezhang1990** [robotframework/RIDE#1686] opened 2017-02-20 10:07 UTC
when my project directory has Chinese, below error will appears.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 370, in OnTimer
    self._test_runner.get_output_and_errors(self.get_current_profile())
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 249, in get_output_and_errors
    stdout, stderr, returncode = self._process.get_output(), \
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 304, in get_output
    return self._output_stream.pop()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 399, in pop
    return result.decode('UTF-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 349: invalid continuation byte

![image](https://cloud.githubusercontent.com/assets/16640362/23120449/5ccede38-f797-11e6-8c66-6e28f23e1b88.png)

**Comment by Nyral** [comment] 2019-06-01 18:34
@simplezhang1990 Do you still get this issue with latest release?

**Comment by HelioGuilherme66** [comment] 2019-12-01 18:28
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 18:28 UTC
Labels: pending
