### ISSUE TITLE
RIDE should load the system's robot-framework library if present

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1431] opened 2015-06-03 09:22 UTC
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1391) by edbran... on 2 Dec 2014*

Steps to reproduce:

1. execute "pip install -U robotframework"
2. Install RIDE via the Windows EXE Installer
3. Make a test suite with the line "Library     DateTime"

Expected result:

The library is imported and understood by RIDE

Observed result:

The following appears in the RIDE log:

20141202 10:42:50.902 [WARN]: Importing test library "DateTime" failed

Traceback (most recent call last):
Importing test library 'DateTime' failed: ImportError: No module named DateTime
Traceback (most recent call last):
  None
PYTHONPATH:
  c:\Python27\lib\site-packages\robotide\lib\robot\libraries
  c:\Python27\lib\site-packages\robotide\lib
  c:\Python27\lib\site-packages\wx-2.8-msw-unicode
  c:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\Scripts
  c:\Python27\lib\site-packages\fabric-1.5.2-py2.7.egg
  c:\Python27\lib\site-packages\paramiko-1.9.0-py2.7.egg
  c:\Python27\lib\site-packages\shovel-0.1.9-py2.7.egg
  c:\Python27\lib\site-packages\chaco-4.3.0-py2.7-win32.egg
  c:\Python27\lib\site-packages\pyparsing-2.0.1-py2.7-win32.egg
  c:\Python27\lib\site-packages\tornado-3.1.1-py2.7.egg
  c:\Python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
  c:\Python27\lib\site-packages\pyreadline-2.0-py2.7-win32.egg
  c:\Python27\lib\site-packages\jrnl-1.5.6-py2.7.egg
  c:\Python27\lib\site-packages\nikola-6.1.1-py2.7.egg
  c:\Python27\lib\site-packages\configparser-3.3.0r2-py2.7.egg
  c:\Python27\lib\site-packages\logbook-0.6.0-py2.7.egg
  c:\Python27\lib\site-packages\pyrss2gen-1.1-py2.7.egg
  c:\Python27\lib\site-packages\yapsy-1.10.2_pythons2n3-py2.7.egg
  c:\Python27\lib\site-packages\lxml-3.2.3-py2.7-win32.egg
  c:\Python27\lib\site-packages\unidecode-0.04.14-py2.7.egg
  c:\Python27\lib\site-packages\pillow-2.2.1-py2.7-win32.egg
  c:\Python27\lib\site-packages\doit-0.23.0-py2.7.egg
  c:\Python27\lib\site-packages\livereload-1.0.1-py2.7.egg
  c:\Python27\lib\site-packages\docopt-0.6.1-py2.7.egg
  c:\Python27\lib\site-packages\ipython-1.1.0-py2.7.egg
  c:\Python27\lib\site-packages\pil-1.1.7-py2.7-win32.egg
  c:\Python27\lib\site-packages\pyinstaller-2.1-py2.7.egg
  c:\Python27\lib\site-packages\jsonwatch-0.1.2-py2.7.egg
  c:\Python27\lib\site-packages\ghp_import-0.4.1-py2.7.egg
  c:\Python27\lib\site-packages\robotframework_sshlibrary-2.0.2-py2.7.egg
  c:\Python27\lib\site-packages\robotframework_sudslibrary-0.8-py2.7-win32.egg
  c:\Python27\lib\site-packages\suds-0.4-py2.7.egg
  c:\Python27\lib\site-packages\robotframework_databaselibrary-0.6-py2.7.egg
  c:\Python27\lib\site-packages\robotframework_oap_phase2library_0.1_py2.7-0.1-py2.7.egg
  c:\dev\github\mkdocs
  c:\dev\oa\src\rideplugins
  C:\Windows\system32\python27.zip
  c:\Python27\DLLs
  c:\Python27\lib
  c:\Python27\lib\plat-win
  c:\Python27\lib\lib-tk
  c:\Python27
  c:\Python27\lib\site-packages
  c:\Python27\lib\site-packages\win32
  c:\Python27\lib\site-packages\win32\lib
  c:\Python27\lib\site-packages\Pythonwin
  .
  C:\dev\redacted-directory-where-i-ran-ride.py
  c:\Python27\lib\site-packages\robotide\spec
  File "c:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 76, in _fetch_keywords
    return get_import_result(path, library_args)
  File "c:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = TestLibrary(path, args)
  File "c:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 37, in TestLibrary
    libcode = importer.import_class_or_module(name)
  File "c:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 64, in import_class_or_module
    self._raise_import_failed(name, err)
  File "c:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 102, in _raise_import_failed
    raise DataError('\n'.join(msg))

Tests that rely on the DateTime library still execute correctly.

**Comment by yanne** [comment] 2015-06-04 04:17
This is a duplicate of #1371

**Closed by yanne** 2015-06-04 04:17 UTC
Labels: duplicate, enhancement, prio-high
