### ISSUE TITLE
Focus jumps to the test case being run 

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#2729] opened 2024-03-11 09:25 UTC
RIDE v2.0.8.1 running on Python 3.7.4. 
(the same behaviour was on RIDE 1.7.4.2 running on Python 3.7.0)

I have a long list of cases,keywords in a suite.
I run 1 (or several cases) and start editing another keyword or case, located way lower/upper than the case being run.
When I start moving around other cases/keywords - the focus always jumps back to the current case being run.

And if there are several test cases being run in order- whenever 1 cases is finished and the next one is starting - the focus jumps back to the current run case.

For example:
I'm editing keyword "parse json data" and I want focus to stay on it (to able to see keywords/cases next to it)
![image](https://github.com/robotframework/RIDE/assets/7736848/8b72a8cb-622c-4a13-8862-9adf7980a1ac)

but when I click to a neighbouring keyword "find match" and want to go back to editing "parse json data"  - it jumps back to the current run case 
![image](https://github.com/robotframework/RIDE/assets/7736848/0381b92c-be2f-4d12-b7bf-72a1f7cb9e2b)

and now in order to get back to editing "parse json data" I have to scroll all the way down again.

This behaviour was different on older versions (RIDE 1.2.2 running on Python 2.7.0.) - focus stayed at the same place and didn't jump

**Comment by HelioGuilherme66** [comment] 2024-03-11 14:11
>(the same behaviour was on RIDE 1.7.4.2 running on Python 3.7.0)
Good, then it is not a new bug (or missing functionality) ;)
>This behavior was different on older versions (RIDE 1.2.2 running on Python 2.7.0.) - focus stayed at the same place and didn't jump
Well, many things changed since then, especially the ability to run in Python 3.

Current RIDE, selects the actual running test to show that it is running, with an animated GIF. Maybe in the past, it only selected the test when it completed.

As a workaround, you should try to see if the Navigation actions (Back) move to the **previous selected item**.  It is linked to the items in the Project Explorer (Tree), not to the editing history.

Anyway, this would be a new feature, and with low priority, because there are things more urgent to fix in RIDE.

**Comment by povar81** [comment] 2024-03-12 09:23
Navigation actions work but with the same problem: 
when I click green back/forward buttons they move to  the previous/next keyword as expected, but
focus still jumps all the way up to the currently run case.

**Comment by HelioGuilherme66** [comment] 2024-04-02 12:18
@povar81 I cannot reproduce this (in current development version). When tests are running, the Editor remains in the same file.
Please add a recording of this behavior.

**Comment by HelioGuilherme66** [comment] 2024-10-13 19:39
Closing because we have now a new release v2.1, and users should try it.
Use the command:
`pip install -U robotframework-ride`
Or from RIDE, **Help->Check for Upgrade**.

**Closed by HelioGuilherme66** 2024-10-13 19:39 UTC
Labels: prio-low
