### ISSUE TITLE
An error occurs when the project name contains Chinese characters

### ISSUE THREAD

**Issue by wangboxy2008** [robotframework/RIDE#2754] opened 2024-04-22 03:47 UTC
![2024-04-22_112451](https://github.com/robotframework/RIDE/assets/23701840/89133dac-7230-46ac-a81e-3fe8e69c4102)

Cannot enumerate files 'D:\webAutoTest\????V1.7.1-???-???\*' (error 123: the filename,directory name, or volume label syntax is incorrect)

**Comment by HelioGuilherme66** [comment] 2024-04-22 09:07
@wangboxy2008 You need to give more information:

- Python, wxPython and *RIDE* versions
- OS we can see it is Windows
- What action did you did to see the error?

**Comment by HelioGuilherme66** [comment] 2024-10-13 11:44
Closing because not something we can work on, and reproduce. New release v2.1 is out, user should test on it.

**Closed by HelioGuilherme66** 2024-10-13 11:44 UTC
Labels: pending, BAD_ISSUE_REPORT
