### ISSUE TITLE
Ride not running on stop and start inbetween a case.

### ISSUE THREAD

**Issue by adityakoganti** [robotframework/RIDE#1674] opened 2017-01-06 05:54 UTC
Hi i have found an issue with the latest version of Ride, If a case in stuck and if you are forced to stop the case and again start it, ride wont run unless you restart it. I dont know exactly whether the issue is with my PC or Ride, i haven't faced this issue in previous release so i hope problem is with RIDE.  If anyone facing the same issue support my post so the developers can look into it.

**Comment by tianyueguang** [comment] 2017-01-23 03:54
I have the same problem.

**Comment by Nyral** [comment] 2019-06-01 18:20
@adityakoganti @tianyueguang Is this issue still happening with latest release?

**Comment by HelioGuilherme66** [comment] 2019-12-01 18:27
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 18:27 UTC
Labels: pending
