### ISSUE TITLE
Cannot activate AutoItLibrary - Class not registered

### ISSUE THREAD

**Issue by Harm10** [robotframework/RIDE#2374] opened 2021-04-01 05:43 UTC
According to AutoItLibrary support this error needs to be adressed by RIDE:
When activating Autoitlibrary I get these messages (Klasse is niet geregistreerd = Class not registered):
```
Initializing test library 'AutoItLibrary' with no arguments failed: com_error: (-2147221164, 'Klasse is niet geregistreerd', None, None) 
Traceback (most recent call last):
File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 167, in _get_instance return libcode(*self.positional_args, **dict(self.named_args))
File "D:\Program Files\Python\lib\site-packages\AutoItLibrary\__init__.py", line 91, in __init__ self._AutoIt = win32com.client.Dispatch("AutoItX3.Control") File "D:\Program Files\Python\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
File "D:\Program Files\Python\lib\site-packages\win32com\client\dynamic.py", line 98, in _GetGoodDispatchAndUserName return (_GetGoodDispatch(IDispatch, clsctx), userName) File "D:\Program Files\Python\lib\site-packages\win32com\client\dynamic.py", line 83, in _GetGoodDispatch IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
File "D:\Program Files\Python\lib\site-packages\robotide\spec\librarymanager.py", line 82, in _fetch_keywords return get_import_result(path, library_args)
File "D:\Program Files\Python\lib\site-packages\robotide\spec\libraryfetcher.py", line 21, in get_import_result lib = robotapi.TestLibrary(path, args)
File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 54, in TestLibrary lib.create_handlers()
File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 100, in create_handlers self._create_handlers(self.get_instance())
File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 159, in get_instance self._libinst = self._get_instance(self._libcode)
File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 169, in _get_instance self._raise_creating_instance_failed()
File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 314, in _raise_creating_instance_failed % (self.name, args_text, msg, details))
```

Is this indeed a RIDE problem? I am on RIDE 2.0b1 and Python 3.7.9

**Comment by HelioGuilherme66** [comment] 2021-04-01 16:57
Missing information about the version of Robot Framework.
Please paste the RIDE->Tools->RIDE Log output. Also confirm is Windows and Python are 64bit (most probably is, but still).

**Comment by Harm10** [comment] 2021-04-01 22:36
Windows 10 (64bit). Robot Framework 3.2.2
`20210402 00:34:55.188 [INFO]: Found Robot Framework version 3.2.2 from D:\Program Files\Python\lib\site-packages\robot.

20210402 00:34:55.188 [INFO]: Started RIDE v2.0b1 using python version 3.7.9 with wx version 4.0.7.post2 in win32.

20210402 00:35:08.297 [WARN]: Importing test library "AutoItLibrary" failed

Traceback (most recent call last):
Initializing test library 'AutoItLibrary' with no arguments failed: com_error: (-2147221164, 'Klasse is niet geregistreerd', None, None)
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 167, in _get_instance
    return libcode(*self.positional_args, **dict(self.named_args))
  File "D:\Program Files\Python\lib\site-packages\AutoItLibrary\__init__.py", line 91, in __init__
    self._AutoIt = win32com.client.Dispatch("AutoItX3.Control")
  File "D:\Program Files\Python\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "D:\Program Files\Python\lib\site-packages\win32com\client\dynamic.py", line 98, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "D:\Program Files\Python\lib\site-packages\win32com\client\dynamic.py", line 83, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
  File "D:\Program Files\Python\lib\site-packages\robotide\spec\librarymanager.py", line 82, in _fetch_keywords
    return get_import_result(path, library_args)
  File "D:\Program Files\Python\lib\site-packages\robotide\spec\libraryfetcher.py", line 21, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 54, in TestLibrary
    lib.create_handlers()
  File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 100, in create_handlers
    self._create_handlers(self.get_instance())
  File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 159, in get_instance
    self._libinst = self._get_instance(self._libcode)
  File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 169, in _get_instance
    self._raise_creating_instance_failed()
  File "D:\Program Files\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 314, in _raise_creating_instance_failed
    % (self.name, args_text, msg, details))`

**Comment by HelioGuilherme66** [comment] 2021-04-07 15:29
@JFoederer Please try to analyse this bug :)

**Comment by JFoederer** [comment] 2021-04-08 17:34
Hoi @Harm10 ,
I think I was able to reproduce your issue, but I was not able to link it to an issue in RIDE. I used autoitlibrary 1.2.7, and got a slightly different error (and in English rather than Dutch ;-) `com_error: (-2147221005, 'Invalid class string', None, None)` with a nearly identical traceback.

It could be that the installation of the AutoIt library was not completed successfully. During installation a dll is copied to `C:\RobotFramework\Extensions\AutoItLibrary\AutoItX3.dll` and then registered. I get this error when the registration part fails.

To fix this:
- Open Windows Explorer (verkenner)
- right click on the DLL and choose **open with...**
- Click _Look for an other app on this PC_ and select `C:\Windows\System32\regsvr32.exe`
- You should get a pop-up telling you the DLL was registered. Click Ok
- Restart RIDE

Can you please check to see if this resolves your issue?

**Comment by Harm10** [comment] 2021-04-08 19:18
Hi JFoederer!
First of all the location of AutoItX3.dll is not the folder you specify. Mine is D:\Program Files\Python\Lib\site-packages\RobotFramework\Extensions\AutoItLibrary (so part of the Python installation).
I followed your instructions but that gave me an 0x80070005 error which is mostly associated with authorization.
So I opened a raised cmd box and successfully executed the command
`regsvr32.exe "D:\Program Files\Python\Lib\site-packages\RobotFramework\Extensions\AutoItLibrary\AutoItX3.dll"`

I restarted RIDE and activated AutoItLibrary to get the same error messages.
I assume the registration does not need a reboot?

And is it OK that my Extensions are in a different place?

**Comment by JFoederer** [comment] 2021-04-09 14:30
Interesting point and it turns out that we are both right. The dll is actually installed twice and both appear to be relevant. The location in C:\RobotFramework is also mentioned in the [documentation of the library](https://github.com/nokia/robotframework-autoitlibrary).

Unregistering the one from site packages also yields the `Class  not registered` error on my system, so that is getting closer to your error than what I had before. I do get a line number that is off by one, so could you please verify we are using the same AutoItLibrary version? (1.2.7) 

I also made the issue a bit smaller. After a regular successful installation of the library I am able to load the library directly from a Python prompt:
```
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import AutoItLibrary
>>> AutoItLibrary.AutoItLibrary()
*INFO* AutoIt: Running File: c:\python38\lib\site-packages\AutoItLibrary\__init__.py, Version: 1.1
*INFO* AutoIt: Running AutoItX 3.3.14.2 (COM object)
<AutoItLibrary.AutoItLibrary object at 0x000001EE45050AF0>
```

Unregistering the dll (`C:\Windows\System32\regsvr32.exe /U C:\RobotFramework\Extensions\AutoItLibrary\AutoItX3.dll`) also yields the error here.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python38\lib\site-packages\AutoItLibrary\__init__.py", line 91, in __init__
    self._AutoIt = win32com.client.Dispatch("AutoItX3.Control")
  File "c:\python38\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "c:\python38\lib\site-packages\win32com\client\dynamic.py", line 98, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "c:\python38\lib\site-packages\win32com\client\dynamic.py", line 83, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221164, 'Class not registered', None, None)
```

All in all this increases my thought that this is more likely to be an issue with the AutoItLibrary than an issue in RIDE. Did you try to run a test case that uses this library? My guess is that also Robot (or any other tool) will not be able to load the library on your system in its current state.

**Comment by Harm10** [comment] 2021-04-09 20:12
I uninstalled the package and reinstalled it. The extensions folder still gets created under site-packages on my D disc. So not on the C disc. Is your Python installation also on your C disc?
I asked to reopen the issue on GitHub: [https://github.com/nokia/robotframework-autoitlibrary/issues/31](url)

I did not try running a test case. As soon as I open the suite that contains the library I get the error described.
I might add that AutoIt itself is running OK on my system (I only created the Hello world examples described as described in their documentation)

I agree that it looks more like a package problem than a RIDE problem.

Suppose I copy the content of D:\Program Files\Python\Lib\site-packages\RobotFramework\Extensions\AutoItLibrary to C:\RobotFramework\Extensions\AutoItLibrary and register the dll again? Would that narrow the problem?

**Comment by Harm10** [comment] 2021-04-10 14:34
This might be relevant. If I do command "where python" I get
`D:\Program Files\Python\python.exe
C:\Users\Harm\AppData\Local\Microsoft\WindowsApps\python.exe`
I installed Python on D disc. So what's this C reference about?

**Comment by Harm10** [comment] 2021-04-11 10:31
AutoItLibrary support has found it is a bug on their side. So they say they are going to fix it.

**Comment by JFoederer** [comment] 2021-04-11 11:30
Thank for the update @Harm10, with this info I will close the issue here.

**Closed by JFoederer** 2021-04-11 11:30 UTC
Labels: not-a-bug, os: windows
