### ISSUE TITLE
Comment line of test case that applies a Template is removed upon closing/reopening RIDE

### ISSUE THREAD

**Issue by MichaelHallik** [robotframework/RIDE#1528] opened 2015-09-23 16:45 UTC
Setup:
- Win7
- Python 2.7.10
- RF 2.9.1
- RIDE 1.5a2

Preconditions & actions:
- Open RIDE.
- Create a data-driven test case as, for instance, in the following screen shot:

![before](https://cloud.githubusercontent.com/assets/1413615/10051551/65b2296c-6222-11e5-8779-3121cbe5f079.jpg)
- Please make sure to add something like line 1 (see screen shot aboce).
- Save and close RIDE.
- Open RIDE and inspect the test case of step 2.

Expected result:

The test case has not been changed in any way.

Actual result:

The line with the comments has been removed and has been added to the 'Template' line of the test case settings. As follows:

![after](https://cloud.githubusercontent.com/assets/1413615/10051624/ccd4971a-6222-11e5-90a3-3be191c2c7eb.jpg)

**Comment by yanne** [comment] 2015-10-21 04:22
This is probably a `feature` of RF parser, have to investigate can it be resolved in RIDE.

**Comment by HelioGuilherme66** [comment] 2016-03-03 23:00
Could you please retest with newest versions? 
I cannot reproduce with:
Robot Framework version 3.0
RIDE 1.5.2.1 using python version 2.7.10 with wx version 2.8.12.1 in linux2 (Fedora 22 x64).

**Closed** 2019-08-25 23:19 UTC
Labels: bug, fixed, prio-medium
