### ISSUE TITLE
Simplified-Chinese displayed incorrect coding in RIDE output 

### ISSUE THREAD

**Issue by hyanx** [robotframework/RIDE#2339] opened 2020-11-18 08:51 UTC
Simplified-Chinese  displayed incorrect coding in RIDE output， but log file  displayed good

![image](https://user-images.githubusercontent.com/9844339/99506618-4948d600-29bd-11eb-8e4d-e6f4106cce10.png)

![image](https://user-images.githubusercontent.com/9844339/99506649-51a11100-29bd-11eb-9951-d6934fe263f2.png)

My system environment:

> Windows 10 2004 professional

My Python environments:
```
PS C:\Python37\Scripts> python --version
Python 3.7.9
PS C:\Python38\Scripts> pip list
Package             Version
------------------- -----------
numpy               1.19.4
Pillow              8.0.1
pip                 20.2.4
Pygments            2.7.2
Pypubsub            4.0.3
pywin32             228
robotframework      3.2.2
robotframework-ride 1.7.4.2
setuptools          41.2.0
six                 1.15.0
wxPython            4.0.7.post2
```
I changed some charset coding setting of `unic()` function in `C:\Python37\Lib\site-packages\robot\utils\unic.py` file, but have no changed in result.

**Comment by HelioGuilherme66** [comment] 2020-11-18 12:06
@hyanx First you should open a command window, and run the test there, to confirm Robot Framework shows everything OK.
This problem has been reported many times, and we don't have a satisfactory solution for all cases. See this [FAQ question](https://github.com/robotframework/RIDE/wiki/F.A.Q.#5-q-on-windows-when-running-test-suites-with-asian-characters-on-filenames-or-paths-the-output-and-log-panels-show-those-characters-with--how-to-fix).

Other thing, it that you have two Python installations and that may cause confusion.

This [Search](https://github.com/robotframework/RIDE/issues?q=is%3Aissue+Chinese) here on issue tracker shows some of the history of this problem.

Maybe you find some configuration useful to you.
You could try to install current Beta 1, or development version of RIDE.

**Comment by hyanx** [comment] 2020-12-04 09:26
I resolved this problem simply,  just update `testrunnerplugin.py` in Python3 install folder  in `\Lib\site-packages\robotide\contrib\testrunner` , modified line 565 from `textctrl.AppendTextRaw(bytes(string, encoding['SYSTEM'])) ` into `textctrl.AppendTextRaw(bytes(string, encoding['OUTPUT']))`

refer: https://blog.csdn.net/sun_977759/article/details/107785661   :satisfied:

**Comment by HelioGuilherme66** [comment] 2020-12-04 18:42
@hyanx Thank you for the solution. Let's just  hope if that fix works for you and does not break for other users and systems.

**Comment by jnhyperion** [comment] 2020-12-11 08:47
Tested with latest RIDE version, this issue does not reproduce.

@hyanx  please try `pip install -U https://github.com/robotframework/RIDE/archive/master.zip`

@HelioGuilherme66 your commit looks like not nessesary

**Comment by hyanx** [comment] 2020-12-12 09:04
@jnhyperion Thank you, I installed RIDE version 2.0b2.dev1 that I run the scripts well. 

But one more thing. I recently ran another robot script file, that cannot display character perfectly well in modified `testrunnerplugin.py` file. In 2.0b2.dev1 also have similar result but not absolutely alike.

In modified `testrunnerplugin.py` file in 1.7.4.2 ：
![image](https://user-images.githubusercontent.com/9844339/101979855-a32a7c00-3c9b-11eb-92c8-dc039b1e9249.png)



In 2.0b2.dev1 ：
![image](https://user-images.githubusercontent.com/9844339/101979789-07007500-3c9b-11eb-86b4-583a9e41bab3.png)

**Comment by jnhyperion** [comment] 2020-12-15 08:02
@hyanx please help verify on my PR: https://github.com/robotframework/RIDE/pull/2349

**Comment by hyanx** [comment] 2020-12-15 13:20
@jnhyperion Yes, I just used your PR version to ran my robot scripts, it worked well.  兄弟，牛逼！ :grin:

![image](https://user-images.githubusercontent.com/9844339/102219975-286f9400-3f1b-11eb-99bd-5ae696279218.png)

**Comment by jnhyperion** [comment] 2020-12-16 02:24
@hyanx 谢谢 😁

**Comment by HelioGuilherme66** [comment] 2023-09-21 23:09
Closing because no more complaints about broken characters :D

**Closed by HelioGuilherme66** 2023-09-21 23:09 UTC
Labels: duplicate, fixed
