### ISSUE TITLE
Run and edit pages are overlapping

### ISSUE THREAD

**Issue by bipin05el** [robotframework/RIDE#2622] opened 2023-08-23 14:21 UTC
Open RIDE and saw that edit page and run page are overlapping. 
![Capture](https://github.com/robotframework/RIDE/assets/143006156/e495d747-fd79-4334-a153-dd7b316b887d)

**Comment by HelioGuilherme66** [comment] 2023-12-11 16:59
Closing because (OR statements):
- Issue report is does not have enough or relevant info
- No follow up from reporter
- Not anything we can reproduce
- Reducing the number of opened issues

**Closed by HelioGuilherme66** 2023-12-11 16:59 UTC
Labels: BAD_ISSUE_REPORT
