### ISSUE TITLE
Problem with opening two ride 

### ISSUE THREAD

**Issue by MarcinJan** [robotframework/RIDE#1548] opened 2015-12-10 10:54 UTC
In previous releases I could open as many ride as I want. Now when I'm trying open second ride, error appears:

$ /cygdrive/d/Python27/python.exe -c "from robotide import main; main()"
Traceback (most recent call last):
  File "D:\Python27\Lib\site-packages\robotide\__init__.py", line 73, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "D:\Python27\Lib\site-packages\robotide\__init__.py", line 99, in _run
    ride = RIDE(inpath, updatecheck)
  File "D:\Python27\Lib\site-packages\robotide\application\application.py", line 42, in __init__
    wx.App.__init__(self, redirect=False)
  File "D:\Python27\Lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "D:\Python27\Lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "D:\Python27\Lib\site-packages\robotide\application\application.py", line 55, in OnInit
    coreplugins.get_core_plugins())
  File "D:\Python27\Lib\site-packages\robotide\application\pluginloader.py", line 30, in __init__
    standard_classes + self._find_classes(load_dirs) ]
  File "D:\Python27\Lib\site-packages\robotide\application\pluginconnector.py", line 23, in PluginFactory
    return BrokenPlugin(utils.get_error_details(), plugin_class)
  File "D:\Python27\Lib\site-packages\robotide\application\pluginconnector.py", line 69, in __init__
    + 'Error: ' + error
TypeError: cannot concatenate 'str' and 'tuple' objects

Use --help to get usage information. 

BR
Marcin

**Comment by yanne** [comment] 2015-12-11 06:42
Which RIDE version you are using?

**Comment by MarcinJan** [comment] 2015-12-14 10:24
Hello Janne

Thanks for your answer and sorry for my late – you mail landed in my junk email folder.

I’m using:

RIDE 1.5 running on Python 2.7.10 – believe this is the newest one?

Best Regards
Marcin

**Comment by HelioGuilherme66** [comment] 2015-12-14 11:28
I believe that this problem is already fixed in current master. Could you download and install it?

**Comment by luisxiaomai** [comment] 2015-12-23 04:04
yes, I also met when I close ride. It can't be open again. 
RIDE version 1.5 in python 27.

**Comment by sknauth** [comment] 2016-01-05 13:03
Hi, got the same problem on a multiuser system (server) with Ride1.5.
The shipped log plugin is the root cause. It tries to delete *-ride.log file from /tmp directory within a try/except IOError clause. But attempt of removing files will raise OSError. So OSError should be "catched" as well. The /tmp dir got it's sticky bit set, so only root and file owner are allowed to remove files. Hope this helps.

**Comment by HelioGuilherme66** [comment] 2016-01-05 23:30
This problem has been fixed, but not yet released in the official build (looks that Janne has been very busy lately).

You may try the package with the fix at https://github.com/HelioGuilherme66/RIDE/releases/tag/v1.6a1

**Closed** 2016-01-14 16:56 UTC
