### ISSUE TITLE
Argument defaults not shown in keyword documentation

### ISSUE THREAD

**Issue by HaaiHenkie** [robotframework/RIDE#2169] opened 2020-03-24 21:38 UTC
When displaying keyword documentation in RIDE v1.7.4.1 the default values for arguments are not shown. Arguments are displayed as argument=argument in stead of argument=default. The keyword Open Browser in SeleniumLibrary,  for example, should show browser=firefox, but it shows browser=browser.

**Comment by HelioGuilherme66** [comment] 2020-03-24 23:56
@HaaiHenkie This is a duplicate of #2134. If you use Python 3, you can install current master. If you use Python 2.7, you can do the edit on your installed file.

**Closed by HelioGuilherme66** 2020-03-24 23:56 UTC
Labels: duplicate, fixed
