### ISSUE TITLE
Ride.py not working

### ISSUE THREAD

**Issue by sheetalbachu** [robotframework/RIDE#1642] opened 2016-07-12 04:23 UTC
I downloaded RIDE from https://pypi.python.org/pypi/robotframework-ride
After Installation of robotframework-ride-1.5.2.1 successfully. I want to make Ride Editor shortcut on windows desktop and working using GUI. I am trying to execute ride.py from command Line and I am facing an error like:
C:\Users\ssuri>robot --version
Robot Framework 3.0 (Python 2.7.12 on win32)

C:\Users\ssuri>ride.py
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide__init__.py", line 73, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide__init__.py", line 92, in _run
    from robotide.application import RIDE
  File "C:\Python27\lib\site-packages\robotide\application__init__.py", line 15, in <module>
    from application import RIDE, Project
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line 20, in <module
    from robotide.controller import Project
  File "C:\Python27\lib\site-packages\robotide\controller\__init__.py", line 15, in <module>
    from project import Project
  File "C:\Python27\lib\site-packages\robotide\controller\project.py", line 19, in <module>
    from robotide.context import LOG
  File "C:\Python27\lib\site-packages\robotide\context__init__.py", line 34, in <module>
    os.environ['APPDATA'], 'RobotFramework', 'ride')
  File "C:\Python27\lib\os.py", line 425, in **getitem**
    return self.data[key.upper()]
KeyError: 'APPDATA'

Please help me to get rid of this error.

**Comment by HelioGuilherme66** [comment] 2016-07-12 09:12
This is the first time we have report of this error. I suspect it is due to the newest version of Python, 2.7.12.
You mentioned that you have downloaded from PyPy. Did you install using `pip install path_to_ride`?
Please send more info, like:
Operative System version,
Python architecture (32 bit or 64bit) (just start Python interactive and copy text)
wxPython version and architecture as above

Thanks

**Comment by sheetalbachu** [comment] 2016-07-13 04:45
I start Installation as: After Python installation of Python 2.7.12 (v2.7.12:d33e0cf91556), then perform actions 
**1> cd c:\Python27\Scripts
2> 'python -m pip install --upgrade pip' command.
3> pip.exe install --upgrade  --trusted-host wxpython.org --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix
4> python -m pip install "C:\Sheetal_Tools\Automation_Tools\RobotFramework\robotframework-3.0\robotframework-3.0"  --upgrade
5> pip install "C:\Sheetal_Tools\Automation_Tools\RobotFramework\dist\robotframework-ride-1.5.2.1"
6> ride.py**

**Comment by HelioGuilherme66** [comment] 2016-07-13 08:55
Thanks for the info, but still don't know what is Python's architecture.
The wrong step is 3. You installed a not yet released wxPython. You should install wxPython 2.8.12.1 (or 3.0.2), matching Python's architecture (this is a windows installer not a pip package).

Where did you get the installation instructions from? The recommended installation instructions are at https://github.com/robotframework/RIDE/wiki/Installation-Instructions.

There is a good installer for Windows, that installs RIDE (you may select the official or an experimental release), at https://github.com/joao-carloto/RF_Install_Script.

Please, don't forget to close this Issue after successful install of RIDE.
Thanks.

**Comment by sheetalbachu** [comment] 2016-07-14 13:17
I tried to install RobotFramework with RF_Install.ps1 (RF_Install_Script) script also and it installs wxPython 3.0. But script still gets hanged at RIDE.py installation as:

A Python version compatible with the Robot Framework is already installed: Pyth
on 2.7.11
PIP is installed with version: pip 8.1.2 from c:\python27\lib\site-packages (py
thon 2.7)
Upgrading pip  if needed.
Robot Framework is installed with version: Robot Framework 3.0 (Python 2.7.11 o
n win32)
Checking if the Robot Framework is up to date...
Package robotframework is up to date
The Selenium2library seems to be installed
Checking if the The Selenium2library is up to date...
Package robotframework-selenium2library is up to date
Started InternetExplorerDriver server (32-bit)
2.53.1.0
Listening on port 5555
Only local connections are allowed
The Selenium IE driver is installed.
The Selenium Chrome driver is installed
PhantomJS is installed
Browser is False
Checking if wxPython is installed...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named wx
wxPython doesn't seem to be installed
Downloading wxPython...
Installing wxPython...
Please use the default actions of the Installer...
WARNING! At the end, close the wxPython README file so the script can continue.
Checking if Pywin32 is installed...
pywin32 seems to be installed
Trying to open RIDE...
RIDE doesn't seem to be installed
Installing RIDE...
Installing RIDE from https://github.com/HelioGuilherme66/RIDE/
←[31mException:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 299, in run

    requirement_set.prepare_files(finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_
files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 587, in _prepare
_file
    session=self.session, hashes=hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 810, in unpack_url
    hashes=hashes
  File "c:\python27\lib\site-packages\pip\download.py", line 649, in unpack_http
_url
    hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 871, in _download_h
ttp_url
    _download_url(resp, link, content_file, hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 597, in _download_u
rl
    consume(downloaded_chunks)
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 860, in consu
me
    deque(iterator, maxlen=0)
  File "c:\python27\lib\site-packages\pip\download.py", line 563, in written_chu
nks
    for chunk in chunks:
  File "c:\python27\lib\site-packages\pip\utils\ui.py", line 139, in iter
    for x in it:
  File "c:\python27\lib\site-packages\pip\download.py", line 552, in resp_read
    decode_content=False):
  File "c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\resp
onse.py", line 349, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\resp
onse.py", line 526, in read_chunked
    self._original_response.close()
  File "c:\python27\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\resp
onse.py", line 242, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='codeload.github.com', port=443): Rea
d timed out.←[0m
Opening RIDE...
Start-Process : This command cannot be executed due to the error: Application n
ot found.
At C:\Sheetal_Tools\Automation_Tools\RF_Install_Script-master\RF_Install.ps1:64
0 char:22
+         Start-Process <<<<  ride.py --version
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOp
   erationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.C
   ommands.StartProcessCommand

Everything is concluded
Press Enter to close this shell...: 

Please help me out to get rid of this error. I can't proceed to continue my work.
Quick help is required.

**Comment by HelioGuilherme66** [comment] 2016-07-14 15:40
I suspect that was a `pip` failure (maybe due to new python version). You could try RF_install in a different time of the day. Maybe we can chat on slack, see the main page.

**Comment by sheetalbachu** [comment] 2016-07-14 17:38
How can I connect you on Slack. I installed the app and it is asking for teamdomain.slack.com

**Comment by HelioGuilherme66** [comment] 2016-07-14 22:01
As I told you, "see the main page", this is the content:

> RIDE is a development environment for Robot Framework test cases.

>NEW Join RIDE discussion in Robot Framework Slack: https://robotframework.slack.com (signup page: https://robotframework-slack.herokuapp.com)

Click the signup link to create an account.

**Comment by sai1718** [comment] 2018-03-16 03:39
I installed wxpython,robotframework and ride all are installed smoothly but in command prompt when i am typing ride.py it doesn't gives any error but i am not getting any gui.

**Comment by bhajojo** [comment] 2018-03-16 03:48
Go to to path where ride.py is located and run the command python ride.py
in the command prompt

**Comment by srinu584** [comment] 2018-08-21 10:59
Ride GUI not opening when hit the ride.py command in command line prompt, opening below file when  hit the same

![image](https://user-images.githubusercontent.com/28533620/44397761-21a90000-a55f-11e8-8d4a-c2a0c5b686d7.png)

**using the latest version of python 3.7.0, WX version:4.0.3, Robot framework 3.0.4, PIP: 18.0**

**Comment by HelioGuilherme66** [comment] 2018-08-21 12:29
This official RIDE version (1.5.2.1) will not run with your python and wxpython versions.

Python is not correctly registered as the starting command for .py scripts.

You could try:
```
python -m robotide.__init__
```

**Comment by srinu584** [comment] 2018-08-21 12:39
Thanks for the reply 

I have change the default selected program to python from notepad for .py files 
Then its working fine

**Comment by wishkraft** [comment] 2018-09-11 14:55
`RIDE 1.4 running on Python 2.7.9. "Failed to run filename...."`
I'm using the above configuration on win10. when I attempt to launch an application get an error with the "Failed to run filename...." indicating the path does not match any files.
I know this is not correct as I am running the exact same test on other machines. could this be a permission issue?

**Comment by wishkraft** [comment] 2018-09-12 15:58
@HelioGuilherme66, thanks for your prompt response. it turns out this was a permission issue that required UAC to be completely disabled beyond the slider option in control panel. 
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableLUA ==0`

**Comment by rishipatil1095** [comment] 2019-01-29 12:13
@HelioGuilherme66 I am getting a Syntax error on executing ride.py. I tried launching ride with wxPython 2.8.12.1 as well as 3.0.2. Still getting the exact same response. 

C:\Python27\Scripts>ride.py
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 83, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 102, in _run
    from robotide.application import RIDE
  File "C:\Python27\lib\site-packages\robotide\application\__init__.py", line 16, in <module>
    from .application import RIDE, Project
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line 22, in <module>
    from robotide.namespace import Namespace
  File "C:\Python27\lib\site-packages\robotide\namespace\__init__.py", line 16, in <module>
    from .namespace import Namespace
  File "C:\Python27\lib\site-packages\robotide\namespace\namespace.py", line 31, in <module>
    from robotide.publish import PUBLISHER, RideSettingsChanged, RideLogMessage
  File "C:\Python27\lib\site-packages\robotide\publish\__init__.py", line 123, in <module>
    from .messages import *
  File "C:\Python27\lib\site-packages\robotide\publish\messages.py", line 21, in <module>
    from .messages2 import *
  File "C:\Python27\lib\site-packages\robotide\publish\messages2.py", line 24, in <module>
    from robotide.publish import publisher
  File "C:\Python27\lib\site-packages\robotide\publish\publisher.py", line 24, in <module>
    from pubsub import pub
  File "C:\Python27\lib\site-packages\pubsub\pub.py", line 146
    def getDefaultPublisher() -> Publisher:
                              ^
SyntaxError: invalid syntax

These are my versions ---
Pillow==5.4.1
Pygments==2.3.1
Pypubsub==4.0.0
pywin32==224
robotframework==3.1.1
robotframework-ride==1.7.3.1
robotframeworklexer==1.1
six==1.12.0
typing==3.6.6
wxPython==4.0.4

Also, I initially installed wxPython 3.0.2, and then uninstalled it and installed wxPython 2.8.12.1, yet I get wxPython as 4.0.4 as mentioned above. Can u kindly help?

**Comment by drfunjohn** [comment] 2019-01-29 15:46
for python 2.7 pypubsub should be 3.3.0, is not?

**Comment by rishipatil1095** [comment] 2019-01-30 04:21
@drfunjohn Yes, thanks for the solution. I installed pypubsub 3.3.0 and it is working properly now.

**Comment by RRohitGrover** [comment] 2019-02-18 17:18
Yes @rishipatil1095 You are right ,I was also facing the same issue, as i was installing wxPython 2.8.12.1,Automatically pypubsub 4.4.0 was installing. To uninstall pypubsub 4.4.0 , use command pip uninstall pypubsub and install pip install pypubsub==3.3.0.

**Comment by nutan110125** [comment] 2019-04-26 11:43
hello guys i want to install wxPython 2.8.12.1 in mac

**Comment by HelioGuilherme66** [comment] 2019-05-08 20:45
@nutan110125 Only by chance I saw your message. Even when there was MacOS 8, installing wxPython 2.8.12.1 was a very difficult task. There are a lot of limitations. Unless you are really wanting to install that version, you can try to see the Wiki and the BUILD.rst documents.
But why would you install that version?

**Comment by HelioGuilherme66** [comment] 2019-05-08 20:49
@axelfollay Did you by now solved your problem? If not the updated README.rst page has the correct link.

To all users, this and a lot of Issues, will be cleaned after releasing RIDE 1.7.4.

**Comment by axelfollay** [comment] 2019-05-16 13:24
thx @HelioGuilherme66 to worry about me ;)
and sorry to answer u later.
I solved my problem.
C u

**Comment by HelioGuilherme66** [comment] 2019-05-23 23:37
Closing sooner than 1.7.4 :)

Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Closed by HelioGuilherme66** 2019-05-23 23:37 UTC

**Comment by RamyaSriy** [comment] 2019-06-21 07:34
Hi ,

Below are my versions , 

robotframework==3.1.2
robotframework-databaselibrary==1.2
robotframework-ride==1.7.4b1.dev1
robotframeworklexer==1.1
wxPython==4.0.6
Python 2.7.5
PyPubSub==3.3.0

ride.py  doesn't gives any error but i am not getting any gui.

ride.py
Creating librarykeywords database to "/root/.robotframework/ride/librarykeywords.db"
^C

and i also tried python ride.py , but still not working . please help on this , how to i get gui .

**Comment by RakshithaAM** [comment] 2019-06-21 14:16
@RamyaSriy , Please downgrade wxPython to 2.8.12.1 and give a try :)

**Comment by swarajdevops** [comment] 2019-06-27 06:04
> This official RIDE version (1.5.2.1) will not run with your python and wxpython versions.
> 
> Python is not correctly registered as the starting command for .py scripts.
> 
> You could try:
> 
> ```
> python -m robotide.__init__
> ```

Super Thanks!!!

**Comment by pradhan41** [comment] 2019-07-21 16:13
Navigating to python script folder and running command "python ride.py" solved the issue for :)
