### ISSUE TITLE
[BUG]In Ride, if the code in the teardown is too long, the excess part will appear at the end of the test case. 

### ISSUE THREAD

**Issue by didiyou** [robotframework/RIDE#2860] opened 2024-08-23 02:30 UTC
- before

![image](https://github.com/user-attachments/assets/8a5c5fa8-44a8-4afa-a486-cc0f59925a36)

- after (reopen ride)

![image](https://github.com/user-attachments/assets/46deae7f-d7ce-49bd-998a-c91db23e09f7)

**Comment by HelioGuilherme66** [comment] 2024-08-24 21:48
@didiyou It would be nice to have an example Teardown in text mode, so we could copy and paste in RIDE to reproduce.
Also, when the version of RIDE is not mentioned, we assume it is the latest released, which is **2.0.8.1**.

**Comment by HelioGuilherme66** [comment] 2024-10-27 22:35
This is duplicate of #2727.

**Comment by HelioGuilherme66** [comment] 2024-11-01 18:39
Fixed in `develop` future 2.1.1.
Colorization of arguments will not be fixed.

**Closed by HelioGuilherme66** 2024-11-01 18:39 UTC
Labels: duplicate, fixed, analyze
