### ISSUE TITLE
Issue with font?

### ISSUE THREAD

**Issue by mbrucco** [robotframework/RIDE#2149] opened 2020-02-28 08:55 UTC
I'm running RIDE on MacOS Catalina.

when I start it I receive a lot of message like:
2020-02-28 09:49:37.658 Python[9186:4924657] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

**Comment by HelioGuilherme66** [comment] 2020-03-07 00:25
@mbrucco If you change font in Tools -Preferences on Grid and Text editors to a different font, and then restart RIDE, would it make the messages disappear?

**Comment by mbrucco** [comment] 2020-03-07 08:45
No

Inviato da iPhone

**Comment by HelioGuilherme66** [comment] 2020-03-08 01:08
Well there are some reports of users complaining with the same error. For example [this](https://apple.stackexchange.com/questions/377873/when-launching-python-coretext-note-client-requested-name-sfnsmono-regular) and [this](https://stackoverflow.com/questions/58706570/how-can-i-find-the-source-of-this-font-related-coretext-warning-in-ios13).

@mbrucco Can you try to install SF Mono fonts, as is suggested [here](https://osxdaily.com/2018/01/07/use-sf-mono-font-mac/)?

**Comment by mbrucco** [comment] 2020-03-08 19:46
It didn’t solved the issue.

When I run it I receive:
maurizio@Maurizio-MacBook bin % 2020-03-08 20:44:11.472 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:11.472 Python[77359:7181064] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2020-03-08 20:44:11.682 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:11.682 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:11.682 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:11.683 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:11.683 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:11.709 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:11.747 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:11.752 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:11.835 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.228 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.228 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.229 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.229 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.234 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.235 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.372 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.533 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.537 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.543 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.549 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.554 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.560 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.568 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.961 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.965 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.984 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:12.993 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:13.003 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:13.012 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-08 20:44:13.020 Python[77359:7181064] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

**Comment by tomtastic** [comment] 2020-08-14 12:52
https://bugs.openjdk.java.net/browse/JDK-8234916

**Comment by HelioGuilherme66** [comment] 2020-08-26 16:45
@tomtastic Thanks. 

I see the reported problem is with JDK, I wonder why Python shows the same.

@mbrucco Can you confirm that the problem is gone in recent updates of MacOS or Python?
This is nothing we can do from RIDE side.

Would like to get feedback from you before closing. Thanks.

**Comment by mbrucco** [comment] 2020-08-27 07:15
Hi,
Sorry… I don’t use it any more… it never worked on my Mac, so I installed eclipse plugin.

BR
Maurizio

**Closed** 2020-08-27 11:57 UTC
Labels: not-a-bug, os: mac
