### ISSUE TITLE
RIDE Console  Output Size Limit?

### ISSUE THREAD

**Issue by Farb** [robotframework/RIDE#1687] opened 2017-02-28 08:04 UTC
I met a strange problem when I used RIDE to call a .exe program by `Process` library.And the program output some logs,then I used the `Log ` output the infos to the console of RIDE.My case is as follows:
·${dailyJob}       RYP2P.Schedule.exe jobkey:dailydatajob runParams:startdate=2017-1-01$runmode=test$userid=-1 autoclose:true  
·
```
    RunDailyJob
    [Documentation]    test Job
    OperateConfigInfo    update ry_modulesign set Online=1;
    Log Many    ensure my Job offline
    ${result}    Run Process    ${dailyJob}    shell=true    cwd=RyP2P.Schedule    stdout=${CURDIR}/stdout.txt
    Log    ${result.stdout}
```

The .exe program will execute a very complicated business logic.For example,it will loop through a year,the step length is one day.In every day,the program
will outputs a words like 'today is ${today}'。Therefore,the progarm will outputs lots of content finally.In my program,the problem is that the case cannot stop.
If you write the log to the file in the program,you will find the loop will pause in some stage such as the very day of half year.However，when you click the stop button
of RIDE，the loop will continue running to the end of the program.If I comment the `Log    ${result.stdout}`,the case will end quickly.I guess that if RIDE has a limit over 
the console size or it is a bug of RIDE?

Thanks in advance!

**Comment by Casalis** [comment] 2017-03-17 09:14
Have you still got this problem? 
How many lines does the ".exe" return for each day?
Is the Log file longer that the RIDE console log?

**Comment by HelioGuilherme66** [comment] 2019-12-01 18:30
Closing because is too old and we cannot reproduce, or lack of information.

**Comment by Nyral** [comment] 2019-12-01 23:08
You can use the test in this suite to reproduce the issue. It should crash after 300 iterations or so.
[MessageLog.txt](https://github.com/robotframework/RIDE/files/3908836/MessageLog.txt)

To sum it up, we need to add character limit for each line and also maybe periodically clear memory log and console if number of lines/chars reach a certain size.

**Comment by HelioGuilherme66** [comment] 2019-12-02 14:57
@Nyral With your example, I cannot reproduce (today's development version):
![image](https://user-images.githubusercontent.com/2866630/69969290-0f649280-1514-11ea-967f-6c6471e0c4bb.png)

**Comment by HelioGuilherme66** [comment] 2022-05-08 15:04
This is fixed by stopping the log when a memory limit is reached. The following message is shown in the log:
```
Messages log exceeded 80% of process memory, stopping for now...
```

**Closed by HelioGuilherme66** 2022-05-08 15:04 UTC
Labels: prio-medium, bug, fixed
