### ISSUE TITLE
Slow performance using RIDE 1.7.3 and up on Windows 10

### ISSUE THREAD

**Issue by jsonpcwt** [robotframework/RIDE#1916] opened 2019-05-17 09:52 UTC
OS: Windows10
wxPython 2.8.12.1

I reverted on using 1.5.2.1 which is faster, however, "go to definition" doesnt work

**Comment by Nyral** [comment] 2019-05-18 20:40
Be more specific.

**Comment by rainydew** [comment] 2019-06-18 11:51
slow in folding/expand suite treeview, mainly about redrawing
1.5.2.1 slow too, I use IntelliBot plugin of PyCharm but long time no update

**Comment by Nyral** [comment] 2019-06-18 20:57
@rainydew Give me some numbers. How many suites/resources are there loaded? How slow is it? (i.e. how long does it takes to redraw, make a rought estimate) And anything else you might think important.

**Comment by rainydew** [comment] 2019-06-21 13:33
> @rainydew Give me some numbers please. How many suites/resources are there loaded? How long does it takes to redraw (a rough estimate) + anything else you might think to be important.

65 suites and 448 tests, with 121 library files. Often need 10+ s to redraw when I fold/ unfold the main archive

**Comment by pakal** [comment] 2019-09-20 13:14
Please have a look at https://github.com/robotframework/RIDE/issues/2017 and tell if this bugfix works in your case

**Comment by Nyral** [comment] 2019-09-20 19:37
@HelioGuilherme66  The slow folding/expanding has been fixed through the PRs from this issue #1958. I didn't realize that this issue was on the same thing because of the title.

@jsonpcwt Please upgrade to the latest version and confirm if the issue is gone.

**Comment by HelioGuilherme66** [comment] 2019-12-01 19:39
Closing because is too old and we cannot reproduce, or lack of information.

**Closed by HelioGuilherme66** 2019-12-01 19:39 UTC
Labels: pending
